import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "The normal resting heart rate for an adult is:",
    explanation: "Normal adult resting heart rate is 60-100 beats per minute.",
    options: ["60-100 bpm", "40-60 bpm", "100-120 bpm", "120-150 bpm"],
    answer: 0,
  },
  {
    prompt: "The SA node is located in:",
    explanation: "The sinoatrial (SA) node is located in the right atrium near the superior vena cava and is the natural pacemaker.",
    options: ["Right atrium near SVC", "Left atrium near pulmonary veins", "Interventricular septum", "Right ventricle"],
    answer: 0,
  },
  {
    prompt: "Which artery supplies the anterior wall of the left ventricle?",
    explanation: "The left anterior descending (LAD) artery (anterior interventricular branch of left coronary) supplies the anterior LV wall.",
    options: ["Left anterior descending (LAD)", "Right coronary artery", "Circumflex artery", "Posterior descending artery"],
    answer: 0,
  },
  {
    prompt: "Myocardial infarction of the inferior wall is most commonly caused by occlusion of:",
    explanation: "The right coronary artery (RCA) supplies the inferior wall of the left ventricle in ~85% of people (right-dominant circulation).",
    options: ["Right coronary artery (RCA)", "Left anterior descending (LAD)", "Left circumflex artery", "Left main coronary artery"],
    answer: 0,
  },
  {
    prompt: "The cardiac output is calculated as:",
    explanation: "Cardiac Output (CO) = Heart Rate (HR) x Stroke Volume (SV). Normal CO is approximately 5 L/min.",
    options: ["Heart rate x Stroke volume", "Blood pressure x Heart rate", "Stroke volume / Heart rate", "Blood pressure x Cardiac index"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the most common cause of heart failure worldwide?",
    explanation: "Coronary artery disease (ischemic heart disease) is the most common cause of heart failure worldwide.",
    options: ["Coronary artery disease", "Hypertension", "Valvular heart disease", "Dilated cardiomyopathy"],
    answer: 0,
  },
  {
    prompt: "The Frank-Starling mechanism states that:",
    explanation: "The Frank-Starling law states that increased venous return (preload) leads to increased stroke volume via greater myocardial stretch.",
    options: ["Increased preload increases stroke volume", "Increased afterload increases stroke volume", "Decreased heart rate increases stroke volume", "Decreased contractility increases stroke volume"],
    answer: 0,
  },
  {
    prompt: "Aortic stenosis is most commonly caused by:",
    explanation: "Calcific aortic stenosis is the most common cause in adults over 65 years, previously bicuspid aortic valve in younger adults.",
    options: ["Calcific degeneration", "Rheumatic heart disease", "Infective endocarditis", "Congenital bicuspid valve (all ages)"],
    answer: 0,
  },
  {
    prompt: "The murmur of mitral regurgitation is best heard at:",
    explanation: "The murmur of mitral regurgitation is a pansystolic (holosystolic) murmur heard best at the apex, radiating to the axilla.",
    options: ["Apex, radiating to axilla", "Left sternal border", "Right upper sternal border", "Aortic area"],
    answer: 0,
  },
  {
    prompt: "Which electrolyte imbalance is most dangerous in a patient on digoxin?",
    explanation: "Hypokalemia potentiates digoxin toxicity because K+ competes with digoxin for binding to Na+/K+ ATPase.",
    options: ["Hypokalemia", "Hyperkalemia", "Hypernatremia", "Hypocalcemia"],
    answer: 0,
  },
  {
    prompt: "The most common cardiac arrhythmia is:",
    explanation: "Atrial fibrillation (AF) is the most common sustained cardiac arrhythmia, especially in the elderly.",
    options: ["Atrial fibrillation", "Ventricular tachycardia", "Heart block", "Supraventricular tachycardia"],
    answer: 0,
  },
  {
    prompt: "Deep vein thrombosis (DVT) most commonly occurs in:",
    explanation: "DVT most commonly affects the deep veins of the lower extremities (popliteal, femoral, iliac veins).",
    options: ["Deep veins of lower extremities", "Deep veins of upper extremities", "Jugular veins", "Portal vein"],
    answer: 0,
  },
  {
    prompt: "The JVP (jugular venous pressure) reflects:",
    explanation: "JVP reflects right atrial pressure and provides information about right heart function and fluid status.",
    options: ["Right atrial pressure", "Left atrial pressure", "Aortic pressure", "Pulmonary artery pressure"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of cardiac tamponade?",
    explanation: "Beck's triad: hypotension, muffled heart sounds, and jugular venous distension (JVD). Also includes pulsus paradoxus.",
    options: ["Beck's triad (hypotension, muffled heart sounds, JVD)", "Loud systolic murmur", "Bounding pulse", "Wide pulse pressure"],
    answer: 0,
  },
  {
    prompt: "The ECG finding in acute myocardial infarction is:",
    explanation: "ST-segment elevation (STEMI) or ST depression/T-wave inversion (NSTEMI) are key ECG findings in acute MI.",
    options: ["ST-segment elevation or depression", "Prolonged PR interval", "Tall T waves only", "Normal ECG"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the primary target of beta-blockers in heart failure?",
    explanation: "Beta-blockers reduce heart rate and myocardial oxygen demand, blocking the harmful chronic sympathetic activation in heart failure.",
    options: ["Reduce heart rate and sympathetic overactivity", "Increase cardiac output directly", "Dilate blood vessels only", "Increase heart rate"],
    answer: 0,
  },
  {
    prompt: "Pulse pressure is defined as:",
    explanation: "Pulse pressure = Systolic BP - Diastolic BP. Wide pulse pressure (>40 mmHg) can indicate aortic regurgitation or atherosclerosis.",
    options: ["Systolic BP minus Diastolic BP", "Mean arterial pressure", "Diastolic BP only", "Systolic BP only"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the most common valvular disease in developing countries?",
    explanation: "Rheumatic heart disease (particularly mitral stenosis) remains the most common valvular disease in developing countries.",
    options: ["Mitral stenosis (rheumatic)", "Aortic stenosis", "Mitral regurgitation", "Tricuspid regurgitation"],
    answer: 0,
  },
  {
    prompt: "Hypertrophic cardiomyopathy (HCM) is characterized by:",
    explanation: "HCM features asymmetric septal hypertrophy, systolic anterior motion (SAM) of the mitral valve, and LVOT obstruction.",
    options: ["Asymmetric septal hypertrophy with LVOT obstruction", "Dilation of all four chambers", "Thickening of all ventricular walls equally", "Restrictive filling pattern"],
    answer: 0,
  },
  {
    prompt: "The Allen test is used to assess:",
    explanation: "The Allen test evaluates the adequacy of ulnar artery blood supply to the hand before radial artery catheterization.",
    options: ["Ulnar artery patency for radial artery cannulation", "Carpal tunnel syndrome", "Raynaud's phenomenon", "Peripheral vascular disease"],
    answer: 0,
  },
  {
    prompt: "Pericarditis typically presents with:",
    explanation: "Pericarditis presents with sharp chest pain that worsens with inspiration and improves when leaning forward, with a pericardial friction rub.",
    options: ["Sharp pain worsening with inspiration, friction rub", "Pressure-like pain radiating to arm", "Painless enlargement", "No symptoms"],
    answer: 0,
  },
  {
    prompt: "The most common congenital heart defect is:",
    explanation: "Ventricular septal defect (VSD) is the most common congenital heart defect, accounting for ~25% of congenital heart disease.",
    options: ["Ventricular septal defect (VSD)", "Atrial septal defect (ASD)", "Patent ductus arteriosus (PDA)", "Tetralogy of Fallot"],
    answer: 0,
  },
  {
    prompt: "In cardiogenic shock, the primary problem is:",
    explanation: "Cardiogenic shock results from severe left ventricular failure with inadequate cardiac output despite adequate intravascular volume.",
    options: ["Inadequate cardiac output from pump failure", "Decreased venous return", "Vasodilation", "Blood loss"],
    answer: 0,
  },
  {
    prompt: "Warfarin is monitored using which laboratory test?",
    explanation: "Warfarin therapy is monitored using INR (International Normalized Ratio) derived from PT (prothrombin time).",
    options: ["INR / PT (prothrombin time)", "aPTT", "Platelet count", "Bleeding time"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a complication of chronic hypertension?",
    explanation: "Chronic hypertension leads to left ventricular hypertrophy (LVH), heart failure, stroke, kidney disease, and retinopathy.",
    options: ["Left ventricular hypertrophy (LVH)", "Decreased heart size", "Low blood pressure", "Bradycardia"],
    answer: 0,
  },
  {
    prompt: "An S3 heart sound is associated with:",
    explanation: "An S3 gallop is associated with ventricular volume overload and is a sign of heart failure in adults.",
    options: ["Ventricular volume overload / heart failure", "Aortic stenosis", "Mitral regurgitation", "Hypertension"],
    answer: 0,
  },
  {
    prompt: "Coronary artery bypass grafting (CABG) is most indicated for:",
    explanation: "CABG is most beneficial for left main coronary artery disease, three-vessel disease, or two-vessel disease with reduced LV function.",
    options: ["Left main or multi-vessel coronary disease", "Single-vessel disease", "Stable angina only", "Heart failure without CAD"],
    answer: 0,
  },
  {
    prompt: "The normal ejection fraction (EF) of the left ventricle is:",
    explanation: "Normal LVEF is 55-70%. Heart failure with reduced EF (HFrEF) is defined as EF ≤40%.",
    options: ["55-70%", "30-40%", "80-90%", "15-25%"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the most common cause of sudden cardiac death?",
    explanation: "Ventricular fibrillation (VF) is the most common rhythm in sudden cardiac death, usually initiated by ventricular tachycardia.",
    options: ["Ventricular fibrillation", "Asystole", "Pulseless electrical activity", "Complete heart block"],
    answer: 0,
  },
  {
    prompt: "Abdominal aortic aneurysm (AAA) screening is recommended for men aged:",
    explanation: "One-time ultrasound screening for AAA is recommended for men aged 65-75 who have ever smoked.",
    options: ["65-75 years (smokers)", "40-50 years", "50-60 years", "All men over 40"],
    answer: 0,
  },
  {
    prompt: "The pathophysiology of angina pectoris involves:",
    explanation: "Angina results from myocardial ischemia due to an imbalance between oxygen supply (coronary blood flow) and demand.",
    options: ["Myocardial oxygen supply-demand mismatch", "Coronary thrombosis", "Heart muscle infection", "Valve dysfunction"],
    answer: 0,
  },
];
