import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "Which of the following is a synonym for 'hypertension'?",
    explanation: "Hypertension means high blood pressure. Synonyms include elevated blood pressure, raised blood pressure.",
    options: ["Elevated blood pressure", "Low blood pressure", "Irregular heartbeat", "Chest pain"],
    answer: 0,
  },
  {
    prompt: "In medical writing, what does 'STAT' mean?",
    explanation: "STAT is derived from Latin 'statim' meaning immediately/without delay. It indicates an urgent order.",
    options: ["Immediately / without delay", "Once daily", "Before meals", "As needed"],
    answer: 0,
  },
  {
    prompt: "Which abbreviation stands for 'History of Present Illness'?",
    explanation: "HPI stands for History of Present Illness, a key component of medical history-taking.",
    options: ["HPI", "ROS", "PE", "CC"],
    answer: 0,
  },
  {
    prompt: "The medical term 'dyspnea' translates to which English phrase?",
    explanation: "Dys- (difficult) + -pnea (breathing) = difficulty breathing or shortness of breath.",
    options: ["Difficulty breathing", "Chest pain", "Rapid heartbeat", "Coughing"],
    answer: 0,
  },
  {
    prompt: "What does 'PRN' stand for in prescriptions?",
    explanation: "PRN stands for 'pro re nata' (Latin), meaning 'as needed' or 'when the circumstance arises'.",
    options: ["As needed (pro re nata)", "Every 8 hours", "Before meals", "At bedtime"],
    answer: 0,
  },
  {
    prompt: "Which of the following correctly uses 'bilateral' in a medical sentence?",
    explanation: "Bilateral means affecting both sides. 'Bateral lower extremity weakness' means weakness in both legs.",
    options: ["Bilateral lower extremity weakness", "Unilateral chest pain", "Acute right-sided headache", "Chronic left arm numbness"],
    answer: 0,
  },
  {
    prompt: "The abbreviation 'SOB' in clinical documentation stands for:",
    explanation: "SOB stands for Shortness of Breath, a common symptom reported by patients.",
    options: ["Shortness of Breath", "Sudden Onset Bleeding", "Severe Occipital Block", "Stable Orthostatic BP"],
    answer: 0,
  },
  {
    prompt: "What is the correct plural form of 'diagnosis'?",
    explanation: "The plural of diagnosis is diagnoses (Greek origin). Similarly, prognosis becomes prognoses.",
    options: ["Diagnoses", "Diagnosis's", "Diagnosises", "Diagnosii"],
    answer: 0,
  },
  {
    prompt: "Which word is the antonym of 'benign' in medical terminology?",
    explanation: "Benign means non-cancerous/harmless. The antonym is malignant (cancerous/harmful).",
    options: ["Malignant", "Chronic", "Acute", "Idiopathic"],
    answer: 0,
  },
  {
    prompt: "In a medical context, 'prognosis' refers to:",
    explanation: "Prognosis is the predicted outcome or course of a disease, including the likelihood of recovery.",
    options: ["Predicted outcome of a disease", "Cause of a disease", "Treatment for a disease", "Diagnostic procedure"],
    answer: 0,
  },
  {
    prompt: "What does the abbreviation 'CBC' stand for?",
    explanation: "CBC stands for Complete Blood Count, a common blood test evaluating red cells, white cells, and platelets.",
    options: ["Complete Blood Count", "Chronic Blood Culture", "Cardiac Blood Circuit", "Central Blood Compartment"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the correct medical spelling?",
    explanation: "'Hemorrhage' is the correct American English spelling (British: haemorrhage). 'Hemorage' is a common misspelling.",
    options: ["Hemorrhage", "Hemorage", "Haemorage", "Hemmorhage"],
    answer: 0,
  },
  {
    prompt: "The abbreviation 'NPO' stands for:",
    explanation: "NPO stands for 'nil per os' (Latin), meaning nothing by mouth. Used for patients before surgery or procedures.",
    options: ["Nothing by mouth (nil per os)", "Normal protein output", "No pulmonary obstruction", "Nasogastric placement only"],
    answer: 0,
  },
  {
    prompt: "What does 'idiopathic' mean in medical terminology?",
    explanation: "Idiopathic means arising from an unknown cause or of spontaneous origin.",
    options: ["Of unknown cause", "Contagious", "Hereditary", "Iatrogenic"],
    answer: 0,
  },
  {
    prompt: "Which sentence correctly uses medical terminology?",
    explanation: "Correct: 'The patient presents with acute onset of dyspnea and tachycardia.' Uses proper medical terms and grammar.",
    options: ["The patient presents with acute onset of dyspnea and tachycardia", "The patient has bad breathing and fast heart", "Breathing problems and racing heart happened", "Patient sick with breathing hard and heart fast"],
    answer: 0,
  },
  {
    prompt: "What does the abbreviation 'DNR' stand for?",
    explanation: "DNR stands for Do Not Resuscitate, a legal order indicating that CPR should not be performed.",
    options: ["Do Not Resuscitate", "Daily Nutritional Requirements", "Delayed Nephron Recovery", "Dynamic Neural Response"],
    answer: 0,
  },
  {
    prompt: "The word 'sequelae' refers to:",
    explanation: "Sequelae (singular: sequel) are conditions or symptoms that follow as a consequence of a disease or injury.",
    options: ["Conditions following a disease", "Initial symptoms of disease", "Diagnostic procedures", "Treatment protocols"],
    answer: 0,
  },
  {
    prompt: "Which abbreviation means 'three times a day'?",
    explanation: "TID (ter in die) or TDS means three times a day. BID = twice daily, QID = four times daily.",
    options: ["TID (ter in die)", "BID (bis in die)", "QID (quarter in die)", "QHS (quaque hora somni)"],
    answer: 0,
  },
  {
    prompt: "What is the correct term for 'a disease that is always present in a population'?",
    explanation: "Endemic means a disease that is constantly present in a population or geographic area.",
    options: ["Endemic", "Epidemic", "Pandemic", "Sporadic"],
    answer: 0,
  },
  {
    prompt: "Which of the following is an example of correct medical English?",
    explanation: "Medical writing should use precise terminology: 'myocardial infarction' rather than 'heart attack' in formal documentation.",
    options: ["Myocardial infarction", "Heart attack", "Bad heart event", "Heart stopped working"],
    answer: 0,
  },
  {
    prompt: "The abbreviation 'ROS' stands for:",
    explanation: "ROS stands for Review of Systems, a systematic checklist of body systems reviewed during patient history.",
    options: ["Review of Systems", "Range of Motion", "Rate of Sedimentation", "Rapid Onset Syndrome"],
    answer: 0,
  },
  {
    prompt: "What does 'i.e.' stand for in medical documentation?",
    explanation: "i.e. stands for 'id est' (that is/in other words). e.g. stands for 'exempli gratia' (for example).",
    options: ["That is (id est)", "For example (exempli gratia)", "And others (et cetera)", "Before food (ante cibum)"],
    answer: 0,
  },
  {
    prompt: "Which prefix means 'against' or 'opposed to'?",
    explanation: "Anti- means against or opposed to (e.g., antibiotic = against bacteria, anticoagulant = against clotting).",
    options: ["Anti-", "Pro-", "Pre-", "Post-"],
    answer: 0,
  },
  {
    prompt: "What is the correct way to write '100 milligrams' in medical notation?",
    explanation: "100 mg is the standard abbreviation. 'mg' (lowercase m, uppercase g) is the correct unit notation.",
    options: ["100 mg", "100 MG", "100 mgs", "100 MGM"],
    answer: 0,
  },
  {
    prompt: "The word 'prophylaxis' means:",
    explanation: "Prophylaxis means preventive treatment or measures taken to prevent disease before it occurs.",
    options: ["Preventive treatment", "Diagnostic test", "Therapeutic intervention", "Palliative care"],
    answer: 0,
  },
  {
    prompt: "What does 'bidirectional' communication mean in clinical settings?",
    explanation: "Bidirectional means two-way. In clinical contexts, it refers to communication or effects going in both directions.",
    options: ["Two-way", "One-way", "Rapid", "Delayed"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a correctly constructed medical compound word?",
    explanation: "Electrocardiogram = electro (electrical) + cardio (heart) + gram (record). Each root is properly combined.",
    options: ["Electrocardiogram", "Heartrecording", "EKGtest", "Cardiowriting"],
    answer: 0,
  },
  {
    prompt: "The abbreviation 'QID' in prescriptions means:",
    explanation: "QID (quarter in die) means four times a day. It is used in prescription writing for dosing frequency.",
    options: ["Four times a day", "Three times a day", "Twice a day", "Once a day"],
    answer: 0,
  },
  {
    prompt: "What does 'etiology' refer to in medicine?",
    explanation: "Etiology is the study of causes or origins of diseases (e.g., the etiology of tuberculosis is Mycobacterium tuberculosis).",
    options: ["Cause of a disease", "Course of a disease", "Treatment of a disease", "Prevention of a disease"],
    answer: 0,
  },
  {
    prompt: "The term 'contraindication' means:",
    explanation: "A contraindication is a condition or factor that makes a particular treatment or procedure inadvisable.",
    options: ["A reason NOT to use a treatment", "An indication for treatment", "A side effect of treatment", "A dose adjustment"],
    answer: 0,
  },
];
