import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "Which type of hypersensitivity is mediated by IgE antibodies?",
    explanation: "Type I (immediate) hypersensitivity is IgE-mediated, causing mast cell degranulation (e.g., anaphylaxis, allergic rhinitis, asthma).",
    options: ["Type I (IgE-mediated)", "Type II (Cytotoxic)", "Type III (Immune complex)", "Type IV (Delayed/Cell-mediated)"],
    answer: 0,
  },
  {
    prompt: "Which type of hypersensitivity is responsible for the tuberculin skin test reaction?",
    explanation: "Type IV (delayed-type) hypersensitivity is T-cell mediated, peaking at 48-72 hours (e.g., tuberculin test, contact dermatitis).",
    options: ["Type IV (Delayed/Cell-mediated)", "Type I (IgE-mediated)", "Type II (Cytotoxic)", "Type III (Immune complex)"],
    answer: 0,
  },
  {
    prompt: "The CD4+ T helper cells recognize antigens presented by:",
    explanation: "CD4+ T cells recognize antigens presented by MHC class II molecules on antigen-presenting cells (APCs).",
    options: ["MHC class II molecules", "MHC class I molecules", "MHC class III molecules", "No MHC required"],
    answer: 0,
  },
  {
    prompt: "Which organ is the primary site of T cell maturation?",
    explanation: "T cells mature in the thymus. Bone marrow is the site of B cell maturation (and T cell origin).",
    options: ["Thymus", "Bone marrow", "Spleen", "Lymph nodes"],
    answer: 0,
  },
  {
    prompt: "Complement component C3a functions as:",
    explanation: "C3a and C5a are anaphylatoxins that cause mast cell degranulation, smooth muscle contraction, and chemotaxis of inflammatory cells.",
    options: ["Anaphylatoxin (mast cell degranulation)", "Opsonin only", "Membrane attack complex", "Anti-inflammatory mediator"],
    answer: 0,
  },
  {
    prompt: "The most abundant immunoglobulin in serum is:",
    explanation: "IgG is the most abundant immunoglobulin in serum (~75-80%), and it crosses the placenta.",
    options: ["IgG", "IgM", "IgA", "IgE"],
    answer: 0,
  },
  {
    prompt: "Which cells are responsible for antibody-dependent cell-mediated cytotoxicity (ADCC)?",
    explanation: "Natural killer (NK) cells perform ADCC by binding antibody-coated target cells via Fc receptors and releasing cytotoxic granules.",
    options: ["NK cells", "Neutrophils", "Macrophages", "Platelets"],
    answer: 0,
  },
  {
    prompt: "Which of the following is an autoimmune disease?",
    explanation: "Systemic lupus erythematosus (SLE) is a systemic autoimmune disease characterized by autoantibodies against nuclear antigens.",
    options: ["Systemic lupus erythematosus (SLE)", "Tuberculosis", "Asthma", "Allergic rhinitis"],
    answer: 0,
  },
  {
    prompt: "HIV primarily infects which type of cell?",
    explanation: "HIV (Human Immunodeficiency Virus) primarily infects CD4+ T helper cells via the CD4 receptor and CCR5/CXCR4 co-receptors.",
    options: ["CD4+ T helper cells", "CD8+ T cytotoxic cells", "B lymphocytes", "NK cells"],
    answer: 0,
  },
  {
    prompt: "The main function of IgA is:",
    explanation: "Secretory IgA is the primary antibody of mucosal immunity, found in saliva, tears, breast milk, and GI/respiratory secretions.",
    options: ["Mucosal immunity (secretory)", "Opsonization", "Complement activation", "Neutralization in blood"],
    answer: 0,
  },
  {
    prompt: "Which type of anemia is caused by autoimmune destruction of red blood cells?",
    explanation: "Autoimmune hemolytic anemia (AIHA) results from autoantibodies against RBC surface antigens causing premature destruction.",
    options: ["Autoimmune hemolytic anemia", "Iron-deficiency anemia", "Megaloblastic anemia", "Thalassemia"],
    answer: 0,
  },
  {
    prompt: "Which of the following is an example of Type II hypersensitivity?",
    explanation: "Autoimmune hemolytic anemia, Graves' disease, and Goodpasture syndrome are Type II (antibody-mediated cytotoxic) hypersensitivity reactions.",
    options: ["Autoimmune hemolytic anemia", "Serum sickness", "Anaphylaxis", "Contact dermatitis"],
    answer: 0,
  },
  {
    prompt: "Major histocompatibility complex (MHC) molecules are also called:",
    explanation: "MHC molecules are called Human Leukocyte Antigens (HLA) in humans. They are essential for antigen presentation to T cells.",
    options: ["Human Leukocyte Antigens (HLA)", "Immunoglobulins", "Complement receptors", "Cytokines"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the most common primary immunodeficiency?",
    explanation: "Selective IgA deficiency is the most common primary immunodeficiency, affecting approximately 1 in 500-700 people.",
    options: ["Selective IgA deficiency", "Severe Combined Immunodeficiency (SCID)", "X-linked agammaglobulinemia", "Chronic granulomatous disease"],
    answer: 0,
  },
  {
    prompt: "Cytotoxic T lymphocytes (CD8+) kill target cells by releasing:",
    explanation: "CD8+ T cells release perforin (creates pores) and granzymes (induce apoptosis) to kill infected or abnormal cells.",
    options: ["Perforin and granzymes", "Antibodies", "Histamine", "Cytokines only"],
    answer: 0,
  },
  {
    prompt: "The spleen's primary immunological function is:",
    explanation: "The spleen filters blood-borne antigens and is the major site of antibody response to blood-borne pathogens.",
    options: ["Filtering blood-borne antigens and mounting immune response", "Producing red blood cells only", "Storing platelets only", "Producing bile"],
    answer: 0,
  },
  {
    prompt: "Which cytokine is the primary growth factor for T cells?",
    explanation: "Interleukin-2 (IL-2) is the primary T cell growth factor, essential for clonal expansion of activated T cells.",
    options: ["Interleukin-2 (IL-2)", "Interleukin-4 (IL-4)", "Interleukin-10 (IL-10)", "Transforming growth factor-beta (TGF-b)"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of X-linked agammaglobulinemia (Bruton's)?",
    explanation: "Bruton's agammaglobulinemia: absent B cells, very low all immunoglobulin classes, recurrent bacterial infections after 6 months.",
    options: ["Absent B cells and all immunoglobulin classes", "Low T cells only", "Normal B cells but no antibodies", "Low complement only"],
    answer: 0,
  },
  {
    prompt: "Graves' disease is an example of which hypersensitivity type?",
    explanation: "Graves' disease is Type II hypersensitivity where stimulating autoantibodies (TSI) activate TSH receptors causing hyperthyroidism.",
    options: ["Type II (Antibody-mediated stimulating)", "Type I (IgE-mediated)", "Type III (Immune complex)", "Type IV (Delayed)"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the main cell type in chronic inflammation?",
    explanation: "Macrophages and lymphocytes are the predominant cell types in chronic inflammation (vs. neutrophils in acute).",
    options: ["Macrophages and lymphocytes", "Neutrophils", "Eosinophils", "Mast cells"],
    answer: 0,
  },
  {
    prompt: "Systemic lupus erythematosus (SLE) is characterized by autoantibodies against:",
    explanation: "SLE features autoantibodies against nuclear antigens: anti-dsDNA, anti-Smith (Sm), anti-nuclear antibody (ANA).",
    options: ["Nuclear antigens (dsDNA, Smith)", "Cell surface receptors", "Extracellular matrix", "Mitochondrial antigens"],
    answer: 0,
  },
  {
    prompt: "The classical complement pathway is activated by:",
    explanation: "The classical pathway is activated by antigen-antibody complexes (IgG or IgM bound to antigen).",
    options: ["Antigen-antibody complexes", "Microbial surface molecules (MBL)", "Spontaneous C3 hydrolysis", "Foreign particles only"],
    answer: 0,
  },
  {
    prompt: "Which immunoglobulin is found as a dimer in secretions?",
    explanation: "Secretory IgA (sIgA) exists as a dimer with a secretory component, providing mucosal immunity.",
    options: ["IgA (dimer)", "IgG (monomer)", "IgM (pentamer)", "IgE (monomer)"],
    answer: 0,
  },
  {
    prompt: "Rheumatoid arthritis primarily affects which type of joint tissue?",
    explanation: "RA primarily targets the synovial membrane, causing pannus formation that erodes cartilage and bone.",
    options: ["Synovial membrane (pannus formation)", "Articular cartilage only", "Bone only", "Ligaments only"],
    answer: 0,
  },
  {
    prompt: "Which blood cells are increased during parasitic infections?",
    explanation: "Eosinophils are characteristically elevated in parasitic infections and allergic conditions.",
    options: ["Eosinophils", "Neutrophils", "Lymphocytes", "Monocytes"],
    answer: 0,
  },
  {
    prompt: "The most common cause of secondary immunodeficiency worldwide is:",
    explanation: "HIV/AIDS is the most common cause of secondary (acquired) immunodeficiency worldwide.",
    options: ["HIV/AIDS", "Malnutrition", "Diabetes", "Cancer"],
    answer: 0,
  },
  {
    prompt: "Which MHC class presents endogenous (intracellular) antigens to CD8+ T cells?",
    explanation: "MHC class I molecules present endogenous antigens (from intracellular pathogens, tumor cells) to CD8+ cytotoxic T cells.",
    options: ["MHC class I", "MHC class II", "MHC class III", "None - CD8 does not need MHC"],
    answer: 0,
  },
  {
    prompt: "Which type of immunity is provided by vaccination?",
    explanation: "Vaccination provides active artificial immunity by stimulating the adaptive immune system to produce memory cells and antibodies.",
    options: ["Active artificial immunity", "Passive natural immunity", "Active natural immunity", "Innate immunity"],
    answer: 0,
  },
  {
    prompt: "Tumor necrosis factor-alpha (TNF-a) is primarily produced by:",
    explanation: "TNF-a is primarily produced by activated macrophages and is a key pro-inflammatory cytokine in sepsis and autoimmunity.",
    options: ["Activated macrophages", "T cells only", "B cells only", "Platelets"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of Type III hypersensitivity?",
    explanation: "Type III hypersensitivity involves immune complex deposition in tissues (e.g., SLE nephritis, serum sickness, arthritis).",
    options: ["Immune complex deposition in tissues", "IgE-mediated mast cell degranulation", "Antibody-mediated cytotoxicity", "T-cell mediated tissue damage"],
    answer: 0,
  },
  {
    prompt: "Which cell type is responsible for presenting antigens to naive T cells in lymph nodes?",
    explanation: "Dendritic cells are the most potent antigen-presenting cells and are essential for activating naive T cells in lymph nodes.",
    options: ["Dendritic cells", "Red blood cells", "Platelets", "Fibroblasts"],
    answer: 0,
  },
];
