import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "The prefix 'hyper-' means:",
    explanation: "Hyper- is a medical prefix meaning 'above normal' or 'excessive' (e.g., hypertension = high blood pressure).",
    options: ["Excessive / above normal", "Below normal", "Within normal", "Against"],
    answer: 0,
  },
  {
    prompt: "The suffix '-itis' means:",
    explanation: "-itis is a suffix meaning 'inflammation of' (e.g., tonsillitis = inflammation of the tonsils).",
    options: ["Inflammation of", "Surgical removal of", "Pertaining to", "Formation of"],
    answer: 0,
  },
  {
    prompt: "The term 'Hepatomegaly' means:",
    explanation: "Hepato- (liver) + -megaly (enlargement) = enlargement of the liver.",
    options: ["Enlargement of the liver", "Inflammation of the liver", "Cancer of the liver", "Removal of the liver"],
    answer: 0,
  },
  {
    prompt: "Which root word refers to the stomach?",
    explanation: "The root 'gastro/o' or 'gastr/o' refers to the stomach (e.g., gastroscopy, gastritis).",
    options: ["Gastr/o", "Hepat/o", "Nephr/o", "Cardi/o"],
    answer: 0,
  },
  {
    prompt: "The suffix '-ectomy' means:",
    explanation: "-ectomy is a suffix meaning 'surgical removal' or 'excision' (e.g., appendectomy = removal of the appendix).",
    options: ["Surgical removal", "Surgical repair", "Inflammation", "Visual examination"],
    answer: 0,
  },
  {
    prompt: "What does the term 'Bradycardia' mean?",
    explanation: "Brady- (slow) + -cardia (heart) = abnormally slow heart rate (<60 bpm).",
    options: ["Slow heart rate", "Fast heart rate", "Irregular heart rhythm", "Chest pain"],
    answer: 0,
  },
  {
    prompt: "The prefix 'Dys-' indicates:",
    explanation: "Dys- is a prefix meaning 'difficult', 'painful', or 'abnormal' (e.g., dyspnea = difficult breathing).",
    options: ["Difficult / painful / abnormal", "Normal", "Excessive", "Absence of"],
    answer: 0,
  },
  {
    prompt: "The root 'Ren/o' or 'Nephr/o' refers to:",
    explanation: "Both ren/o and nephr/o refer to the kidney (e.g., renal = pertaining to kidney, nephritis = kidney inflammation).",
    options: ["Kidney", "Liver", "Heart", "Lung"],
    answer: 0,
  },
  {
    prompt: "What is the medical term for surgical repair of a joint?",
    explanation: "Arthro- (joint) + -plasty (surgical repair) = arthroplasty.",
    options: ["Arthroplasty", "Arthroscopy", "Arthrectomy", "Arthritis"],
    answer: 0,
  },
  {
    prompt: "The suffix '-penia' means:",
    explanation: "-penia is a suffix meaning 'deficiency' or 'decrease' (e.g., leukopenia = decrease in white blood cells).",
    options: ["Deficiency / decrease", "Excess / increase", "Pertaining to", "Formation of"],
    answer: 0,
  },
  {
    prompt: "The term 'Osteoporosis' literally means:",
    explanation: "Osteo- (bone) + -por- (porous) + -osis (condition) = a condition of porous bones.",
    options: ["Porous bones", "Bone cancer", "Bone inflammation", "Bone growth"],
    answer: 0,
  },
  {
    prompt: "Which prefix means 'around' or 'surrounding'?",
    explanation: "The prefix 'peri-' means around or surrounding (e.g., periosteum = around the bone, pericardium = around the heart).",
    options: ["Peri-", "Para-", "Meta-", "Epi-"],
    answer: 0,
  },
  {
    prompt: "The suffix '-scopy' means:",
    explanation: "-scopy means 'visual examination using an instrument' (e.g., endoscopy = examining the interior of the body with an endoscope).",
    options: ["Visual examination", "Surgical removal", "Disease condition", "Pertaining to"],
    answer: 0,
  },
  {
    prompt: "The medical term for inflammation of the stomach lining is:",
    explanation: "Gastr/o (stomach) + -itis (inflammation) = gastritis.",
    options: ["Gastritis", "Gastroscopy", "Gastrectomy", "Gastrostomy"],
    answer: 0,
  },
  {
    prompt: "What does 'Tachypnea' mean?",
    explanation: "Tachy- (rapid) + -pnea (breathing) = abnormally rapid breathing.",
    options: ["Rapid breathing", "Slow breathing", "Painful breathing", "Difficulty breathing"],
    answer: 0,
  },
  {
    prompt: "The root 'Cardi/o' refers to:",
    explanation: "Cardi/o refers to the heart (e.g., cardiology = study of the heart, cardiomyopathy = disease of the heart muscle).",
    options: ["Heart", "Stomach", "Brain", "Kidney"],
    answer: 0,
  },
  {
    prompt: "The prefix 'Sub-' means:",
    explanation: "Sub- means 'below' or 'under' (e.g., subcutaneous = beneath the skin).",
    options: ["Below / under", "Above / over", "Around", "Between"],
    answer: 0,
  },
  {
    prompt: "What is the meaning of 'Hemorrhage'?",
    explanation: "Hem/o (blood) + -rrhage (bursting forth) = a large or uncontrollable discharge of blood.",
    options: ["Heavy bleeding", "Blood clot", "Blood infection", "Low blood count"],
    answer: 0,
  },
  {
    prompt: "The suffix '-algia' means:",
    explanation: "-algia means 'pain' (e.g., neuralgia = nerve pain, arthralgia = joint pain).",
    options: ["Pain", "Inflammation", "Tumor", "Paralysis"],
    answer: 0,
  },
  {
    prompt: "The term 'Anesthesia' literally means:",
    explanation: "An- (without) + -esthesia (sensation) = absence of sensation or feeling.",
    options: ["Absence of sensation", "Painful sensation", "Increased sensation", "Numbness only"],
    answer: 0,
  },
  {
    prompt: "What does 'Bilateral' mean in medical terminology?",
    explanation: "Bi- (two) + -lateral (side) = affecting or occurring on both sides of the body.",
    options: ["Both sides of the body", "One side of the body", "The right side only", "The left side only"],
    answer: 0,
  },
  {
    prompt: "The prefix 'Endo-' means:",
    explanation: "Endo- means 'within' or 'inside' (e.g., endoscopy = visual examination of the interior of the body).",
    options: ["Within / inside", "Outside", "Before", "After"],
    answer: 0,
  },
  {
    prompt: "What is the medical term for difficulty swallowing?",
    explanation: "Dys- (difficult) + -phagia (swallowing) = dysphagia.",
    options: ["Dysphagia", "Dyspnea", "Dysuria", "Dyslexia"],
    answer: 0,
  },
  {
    prompt: "The root 'Pulmon/o' refers to:",
    explanation: "Pulmon/o refers to the lungs (e.g., pulmonology = study of the lungs, pneumonia = lung infection).",
    options: ["Lungs", "Heart", "Kidney", "Liver"],
    answer: 0,
  },
  {
    prompt: "The suffix '-ostomy' means:",
    explanation: "-ostomy means 'surgical opening' or 'creation of a stoma' (e.g., colostomy = surgical opening in the colon).",
    options: ["Surgical opening / stoma formation", "Surgical removal", "Inflammation", "Pain"],
    answer: 0,
  },
  {
    prompt: "What does the term 'Postoperative' mean?",
    explanation: "Post- (after) + operative (surgery) = occurring after a surgical procedure.",
    options: ["After surgery", "Before surgery", "During surgery", "Relating to surgery"],
    answer: 0,
  },
  {
    prompt: "The prefix 'Tachy-' means:",
    explanation: "Tachy- means 'rapid' or 'fast' (e.g., tachycardia = fast heart rate, tachypnea = rapid breathing).",
    options: ["Rapid / fast", "Slow", "Normal", "Difficult"],
    answer: 0,
  },
  {
    prompt: "The term 'Leukocytosis' means:",
    explanation: "Leuko- (white) + -cyto- (cell) + -sis (condition) = an increase in the number of white blood cells.",
    options: ["Increase in white blood cells", "Decrease in white blood cells", "White blood cell cancer", "Absence of white blood cells"],
    answer: 0,
  },
  {
    prompt: "What is the meaning of the suffix '-malacia'?",
    explanation: "-malacia means 'softening' (e.g., osteomalacia = softening of the bones, chondromalacia = softening of cartilage).",
    options: ["Softening", "Hardening", "Inflammation", "Destruction"],
    answer: 0,
  },
  {
    prompt: "The prefix 'Cyan-' refers to which color?",
    explanation: "Cyan- refers to blue color (e.g., cyanosis = bluish discoloration of the skin due to poor oxygenation).",
    options: ["Blue", "Red", "Yellow", "White"],
    answer: 0,
  },
  {
    prompt: "What does 'Anterior' mean in anatomical terminology?",
    explanation: "Anterior (or ventral) refers to the front or forward part of the body.",
    options: ["Front / forward", "Back / behind", "Above", "Below"],
    answer: 0,
  },
];
