import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "Which of the following is a hallmark of acute inflammation?",
    explanation: "The cardinal signs of acute inflammation are: rubor (redness), calor (heat), tumor (swelling), dolor (pain), and functio laesa (loss of function).",
    options: ["Neutrophilic infiltration", "Lymphocytic infiltration", "Granuloma formation", "Fibrosis"],
    answer: 0,
  },
  {
    prompt: "The most common type of bacterial pneumonia is caused by:",
    explanation: "Streptococcus pneumoniae is the most common cause of community-acquired pneumonia (CAP) in adults.",
    options: ["Streptococcus pneumoniae", "Staphylococcus aureus", "Klebsiella pneumoniae", "Pseudomonas aeruginosa"],
    answer: 0,
  },
  {
    prompt: "Hodgkin lymphoma is characterized by the presence of:",
    explanation: "Reed-Sternberg cells (large, binucleated or multinucleated cells) are pathognomonic of Hodgkin lymphoma.",
    options: ["Reed-Sternberg cells", "Langerhans cells", "Sternberg cells only", "Burkitt cells"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a tumor suppressor gene?",
    explanation: "p53 (TP53) is a tumor suppressor gene. Mutations in p53 are found in >50% of human cancers.",
    options: ["p53 (TP53)", "Ras", "Myc", "Bcl-2"],
    answer: 0,
  },
  {
    prompt: "The most common cause of death in burns patients is:",
    explanation: "Sepsis (infection) is the leading cause of death in burn patients, not the burn injury itself.",
    options: ["Sepsis", "Hypovolemic shock", "Inhalation injury", "ARDS"],
    answer: 0,
  },
  {
    prompt: "Which organism causes tuberculosis?",
    explanation: "Mycobacterium tuberculosis is an acid-fast bacillus (AFB) that causes tuberculosis.",
    options: ["Mycobacterium tuberculosis", "Mycobacterium leprae", "Nocardia asteroides", "Corynebacterium diphtheriae"],
    answer: 0,
  },
  {
    prompt: "Widal test is used for the diagnosis of:",
    explanation: "The Widal test detects agglutinating antibodies against Salmonella typhi O and H antigens for typhoid fever diagnosis.",
    options: ["Typhoid fever", "Brucellosis", "Malaria", "Hepatitis B"],
    answer: 0,
  },
  {
    prompt: "The most common site of metastasis for colorectal cancer is:",
    explanation: "The liver is the most common site of distant metastasis for colorectal cancer due to portal venous drainage.",
    options: ["Liver", "Lung", "Brain", "Bone"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of Type I hypersensitivity?",
    explanation: "Type I (immediate) hypersensitivity is IgE-mediated, causing mast cell degranulation (e.g., anaphylaxis, allergic rhinitis).",
    options: ["IgE-mediated mast cell degranulation", "IgG/IgM-mediated cytotoxicity", "Immune complex deposition", "T-cell mediated delayed reaction"],
    answer: 0,
  },
  {
    prompt: "Alzheimer disease pathology shows:",
    explanation: "Alzheimer disease is characterized by amyloid-beta plaques (extracellular) and neurofibrillary tangles (intracellular tau protein).",
    options: ["Amyloid plaques and tau tangles", "Lewy bodies", "Pick bodies", "Negri bodies"],
    answer: 0,
  },
  {
    prompt: "The most common cause of nephrotic syndrome in children is:",
    explanation: "Minimal change disease (MCD) is the most common cause of nephrotic syndrome in children (age 2-6 years).",
    options: ["Minimal change disease", "Membranous nephropathy", "Focal segmental glomerulosclerosis", "IgA nephropathy"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of iron-deficiency anemia on peripheral smear?",
    explanation: "Iron-deficiency anemia shows microcytic hypochromic RBCs with anisocytosis and poikilocytosis.",
    options: ["Microcytic hypochromic cells", "Macrocytic ovalocytes", "Spherocytes", "Target cells"],
    answer: 0,
  },
  {
    prompt: "The enzyme deficient in Phenylketonuria (PKU) is:",
    explanation: "Phenylketonuria is caused by deficiency of phenylalanine hydroxylase (PAH), leading to accumulation of phenylalanine.",
    options: ["Phenylalanine hydroxylase", "Galactose-1-phosphate uridylyltransferase", "Glucose-6-phosphate dehydrogenase", "Hexosaminidase A"],
    answer: 0,
  },
  {
    prompt: "Which virus is associated with cervical cancer?",
    explanation: "Human Papillomavirus (HPV), particularly types 16 and 18, is responsible for nearly all cases of cervical cancer.",
    options: ["HPV (types 16, 18)", "EBV", "HBV", "HHV-8"],
    answer: 0,
  },
  {
    prompt: "Lobar pneumonia is most commonly caused by:",
    explanation: "Streptococcus pneumoniae is the most common cause of lobar pneumonia, presenting with consolidation of an entire lobe.",
    options: ["Streptococcus pneumoniae", "Haemophilus influenzae", "Mycoplasma pneumoniae", "Staphylococcus aureus"],
    answer: 0,
  },
  {
    prompt: "The pathological hallmark of rheumatoid arthritis is:",
    explanation: "Rheumatoid arthritis is characterized by pannus formation (inflamed synovium) that erodes cartilage and bone.",
    options: ["Pannus formation", "Gouty tophi", "Osteophyte formation", "Cartilage calcification"],
    answer: 0,
  },
  {
    prompt: "Which of the following is an oncogene?",
    explanation: "Ras is a proto-oncogene that, when mutated, becomes constitutively active (oncogene) and drives uncontrolled cell proliferation.",
    options: ["Ras", "p53", "Rb", "BRCA1"],
    answer: 0,
  },
  {
    prompt: "The most common primary brain tumor in adults is:",
    explanation: "Glioblastoma multiforme (GBM) is the most common and most aggressive primary brain tumor in adults.",
    options: ["Glioblastoma multiforme", "Meningioma", "Astrocytoma (low grade)", "Oligodendroglioma"],
    answer: 0,
  },
  {
    prompt: "Hemoglobin electrophoresis in sickle cell disease shows:",
    explanation: "Sickle cell disease (HbSS) shows predominantly HbS with absent or decreased HbA on electrophoresis.",
    options: ["Predominant HbS, absent HbA", "Predominant HbF", "Elevated HbA2", "Presence of HbH"],
    answer: 0,
  },
  {
    prompt: "Which stain is used to identify acid-fast bacilli?",
    explanation: "Ziehl-Neelsen (ZN) stain or auramine-rhodamine stain are used to identify acid-fast bacilli like Mycobacterium tuberculosis.",
    options: ["Ziehl-Neelsen stain", "Gram stain", "Giemsa stain", "Periodic acid-Schiff (PAS)"],
    answer: 0,
  },
  {
    prompt: "The most common cause of cirrhosis worldwide is:",
    explanation: "Chronic hepatitis B and C infections are the most common causes of cirrhosis worldwide, while alcohol is the most common in Western countries.",
    options: ["Chronic viral hepatitis (B, C)", "Alcohol", "Non-alcoholic fatty liver disease", "Primary biliary cholangitis"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a granulomatous disease?",
    explanation: "Sarcoidosis is a systemic granulomatous disease characterized by non-caseating granulomas, most commonly affecting the lungs.",
    options: ["Sarcoidosis", "Rheumatoid arthritis", "Systemic lupus erythematosus", "Type 1 diabetes"],
    answer: 0,
  },
  {
    prompt: "The causative agent of leprosy is:",
    explanation: "Mycobacterium leprae is an obligate intracellular acid-fast bacillus that causes leprosy (Hansen's disease).",
    options: ["Mycobacterium leprae", "Mycobacterium tuberculosis", "Treponema pallidum", "Leishmania donovani"],
    answer: 0,
  },
  {
    prompt: "Which type of cell death is programmed and energy-dependent?",
    explanation: "Apoptosis is programmed cell death that requires energy (ATP) and is characterized by cell shrinkage, chromatin condensation, and membrane blebbing.",
    options: ["Apoptosis", "Necrosis", "Autolysis", "Coagulative necrosis"],
    answer: 0,
  },
  {
    prompt: "The most common site of osteosarcoma is:",
    explanation: "Osteosarcoma most commonly arises in the metaphysis of long bones, particularly around the knee (distal femur, proximal tibia).",
    options: ["Metaphysis of long bones (around knee)", "Diaphysis of femur", "Pelvis", "Vertebral bodies"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of Type 2 diabetes pathology?",
    explanation: "Type 2 diabetes is characterized by insulin resistance and relative insulin deficiency (beta-cell dysfunction), not absolute insulin deficiency.",
    options: ["Insulin resistance and beta-cell dysfunction", "Autoimmune beta-cell destruction", "Excess glucagon secretion", "Insulin receptor downregulation only"],
    answer: 0,
  },
  {
    prompt: "Prion diseases cause which pattern of brain pathology?",
    explanation: "Prion diseases (e.g., Creutzfeldt-Jakob disease) cause spongiform encephalopathy with neuronal loss and astrogliosis.",
    options: ["Spongiform encephalopathy", "Plaques and tangles", "Lewy body formation", "Demyelination"],
    answer: 0,
  },
  {
    prompt: "The Warburg effect refers to:",
    explanation: "The Warburg effect describes the preference of cancer cells for aerobic glycolysis (glycolysis in the presence of oxygen) over oxidative phosphorylation.",
    options: ["Aerobic glycolysis in cancer cells", "Increased oxidative phosphorylation", "Fatty acid oxidation", "Amino acid catabolism"],
    answer: 0,
  },
  {
    prompt: "Which of the following is NOT a feature of acute kidney injury (AKI)?",
    explanation: "AKI features: oliguria/anuria, elevated creatinine/BUN, hyperkalemia, metabolic acidosis. Anemia is a feature of CKD (chronic kidney disease), not AKI.",
    options: ["Anemia", "Oliguria", "Hyperkalemia", "Elevated serum creatinine"],
    answer: 0,
  },
  {
    prompt: "Aortic dissection typically occurs at:",
    explanation: "Aortic dissection most commonly involves the ascending aorta (Stanford type A) at the site of cystic medial degeneration.",
    options: ["Ascending aorta (Stanford type A)", "Abdominal aorta below renal arteries", "Aortic arch", "Descending thoracic aorta"],
    answer: 0,
  },
];
