import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "Which of the following is the mechanism of action of penicillin?",
    explanation: "Penicillin inhibits bacterial cell wall synthesis by blocking transpeptidase (penicillin-binding proteins).",
    options: ["Inhibition of cell wall synthesis", "Inhibition of protein synthesis", "Inhibition of DNA gyrase", "Inhibition of folic acid synthesis"],
    answer: 0,
  },
  {
    prompt: "Which receptor type is coupled to G-proteins?",
    explanation: "GPCRs (G-protein coupled receptors) are seven-transmembrane domain receptors that signal through heterotrimeric G-proteins.",
    options: ["GPCR (Metabotropic)", "Ionotropic receptors", "Nuclear receptors", "Receptor tyrosine kinases"],
    answer: 0,
  },
  {
    prompt: "The term 'therapeutic index' refers to:",
    explanation: "TI = TD50/ED50. A higher therapeutic index means a safer drug with a wider margin between effective and toxic doses.",
    options: ["Ratio of toxic dose to effective dose", "Time to reach steady state", "Duration of drug action", "Rate of drug absorption"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a competitive antagonist?",
    explanation: "Competitive antagonists bind the same site as the agonist and can be overcome by increasing agonist concentration (rightward shift of dose-response curve).",
    options: ["Atropine at muscarinic receptors", "Phenoxybenzamine at alpha receptors", "Succinylcholine at nicotinic receptors", "Diazepam at GABA receptors"],
    answer: 0,
  },
  {
    prompt: "First-pass metabolism occurs primarily in which organ?",
    explanation: "Orally administered drugs are absorbed from the GI tract and pass via the portal vein to the liver, where extensive metabolism may occur before reaching systemic circulation.",
    options: ["Liver", "Kidney", "Lung", "Small intestine"],
    answer: 0,
  },
  {
    prompt: "Which of the following drugs is a proton pump inhibitor?",
    explanation: "Omeprazole irreversibly inhibits H+/K+ ATPase on gastric parietal cells, reducing acid secretion.",
    options: ["Omeprazole", "Ranitidine", "Metoclopramide", "Ondansetron"],
    answer: 0,
  },
  {
    prompt: "The drug of choice for status epilepticus is:",
    explanation: "IV Lorazepam or Diazepam is the first-line treatment for status epilepticus due to their rapid onset of action at GABA-A receptors.",
    options: ["Lorazepam (IV)", "Phenytoin", "Valproic acid", "Carbamazepine"],
    answer: 0,
  },
  {
    prompt: "Which neurotransmitter is deficient in Parkinson's disease?",
    explanation: "Dopamine deficiency in the nigrostriatal pathway is the primary pathological mechanism of Parkinson's disease.",
    options: ["Dopamine", "Acetylcholine", "Serotonin", "GABA"],
    answer: 0,
  },
  {
    prompt: "Warfarin acts by inhibiting which enzyme?",
    explanation: "Warfarin inhibits vitamin K epoxide reductase (VKORC1), preventing the recycling of vitamin K needed for clotting factors II, VII, IX, X.",
    options: ["Vitamin K epoxide reductase", "Cyclooxygenase", "ACE", "HMG-CoA reductase"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a reversible inhibitor of MAO-A?",
    explanation: "Moclobemide is a reversible inhibitor of MAO-A (RIMA), unlike irreversible MAOIs like phenelzine.",
    options: ["Moclobemide", "Phenelzine", "Tranylcypromine", "Selegiline"],
    answer: 0,
  },
  {
    prompt: "The volume of distribution (Vd) of a drug that stays mainly in plasma is:",
    explanation: "Drugs with low Vd (< 1 L/kg) remain largely in plasma/extracellular fluid. High Vd indicates tissue distribution.",
    options: ["Low (< 1 L/kg)", "High (> 5 L/kg)", "Very high (> 10 L/kg)", "Equal to body weight"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a phase I metabolic reaction?",
    explanation: "Phase I reactions include oxidation, reduction, and hydrolysis (functionalization). Phase II reactions are conjugation reactions.",
    options: ["Oxidation (CYP450)", "Glucuronidation", "Sulfation", "Acetylation"],
    answer: 0,
  },
  {
    prompt: "Which adrenergic receptor mediates bronchodilation?",
    explanation: "Beta-2 (β2) adrenergic receptors on bronchial smooth muscle cause relaxation and bronchodilation when stimulated.",
    options: ["Beta-2 (β2)", "Alpha-1 (α1)", "Alpha-2 (α2)", "Beta-1 (β1)"],
    answer: 0,
  },
  {
    prompt: "Digoxin toxicity is exacerbated by:",
    explanation: "Hypokalemia increases digoxin toxicity because K+ and digoxin compete for the same binding site on Na+/K+ ATPase.",
    options: ["Hypokalemia", "Hyperkalemia", "Hypernatremia", "Hypocalcemia"],
    answer: 0,
  },
  {
    prompt: "Which of the following is an ACE inhibitor?",
    explanation: "Enalapril is an ACE inhibitor that blocks the conversion of angiotensin I to angiotensin II.",
    options: ["Enalapril", "Losartan", "Amlodipine", "Propranolol"],
    answer: 0,
  },
  {
    prompt: "The target of macrolide antibiotics is:",
    explanation: "Macrolides (erythromycin, azithromycin) bind the 50S ribosomal subunit and inhibit bacterial protein synthesis.",
    options: ["50S ribosomal subunit", "30S ribosomal subunit", "DNA gyrase", "Cell wall transpeptidase"],
    answer: 0,
  },
  {
    prompt: "Which of the following drugs can cause drug-induced lupus?",
    explanation: "Hydralazine and procainamide are the most common drugs associated with drug-induced lupus erythematosus.",
    options: ["Hydralazine", "Metformin", "Amoxicillin", "Omeprazole"],
    answer: 0,
  },
  {
    prompt: "The loading dose of a drug depends primarily on:",
    explanation: "Loading dose = (Cp x Vd) / F. It depends mainly on the volume of distribution (Vd), not clearance.",
    options: ["Volume of distribution (Vd)", "Clearance (Cl)", "Half-life (t1/2)", "Bioavailability (F)"],
    answer: 0,
  },
  {
    prompt: "Sildenafil acts by inhibiting which enzyme?",
    explanation: "Sildenafil is a selective inhibitor of phosphodiesterase type 5 (PDE5), increasing cGMP levels and promoting smooth muscle relaxation.",
    options: ["Phosphodiesterase-5 (PDE5)", "Phosphodiesterase-3 (PDE3)", "Angiotensin-converting enzyme", "HMG-CoA reductase"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a loop diuretic?",
    explanation: "Furosemide inhibits the Na-K-2Cl cotransporter in the thick ascending limb of the loop of Henle.",
    options: ["Furosemide", "Hydrochlorothiazide", "Spironolactone", "Amiloride"],
    answer: 0,
  },
  {
    prompt: "The drug used to reverse opioid overdose is:",
    explanation: "Naloxone is a competitive opioid receptor antagonist used to reverse respiratory depression from opioid overdose.",
    options: ["Naloxone", "Flumazenil", "Atropine", "Physostigmine"],
    answer: 0,
  },
  {
    prompt: "CYP3A4 is responsible for the metabolism of approximately:",
    explanation: "CYP3A4 is the most abundant CYP enzyme in the liver and metabolizes approximately 50% of all clinically used drugs.",
    options: ["50% of drugs", "10% of drugs", "90% of drugs", "25% of drugs"],
    answer: 0,
  },
  {
    prompt: "Which of the following is NOT a beta-blocker side effect?",
    explanation: "Beta-blockers cause bradycardia, bronchospasm, fatigue, and cold extremities. They do NOT cause hyperglycemia; in fact, they may mask hypoglycemia symptoms.",
    options: ["Hyperglycemia", "Bradycardia", "Bronchospasm", "Fatigue"],
    answer: 0,
  },
  {
    prompt: "Lithium is primarily used for:",
    explanation: "Lithium is the gold standard for long-term prophylaxis of bipolar disorder (manic-depressive illness).",
    options: ["Bipolar disorder", "Major depression", "Schizophrenia", "Generalized anxiety"],
    answer: 0,
  },
  {
    prompt: "The antidote for acetaminophen overdose is:",
    explanation: "N-acetylcysteine (NAC) replenishes glutathione stores and prevents hepatotoxicity from the toxic metabolite NAPQI.",
    options: ["N-acetylcysteine (NAC)", "Flumazenil", "Vitamin K", "Deferoxamine"],
    answer: 0,
  },
  {
    prompt: "Which of the following drugs is a H2-receptor antagonist?",
    explanation: "Ranitidine blocks histamine H2 receptors on gastric parietal cells, reducing acid secretion.",
    options: ["Ranitidine", "Omeprazole", "Metoclopramide", "Ondansetron"],
    answer: 0,
  },
  {
    prompt: "The prototype of statins (HMG-CoA reductase inhibitors) is:",
    explanation: "Lovastatin was the first FDA-approved statin. All statins inhibit HMG-CoA reductase, the rate-limiting enzyme in cholesterol synthesis.",
    options: ["Lovastatin", "Atorvastatin", "Simvastatin", "Rosuvastatin"],
    answer: 0,
  },
  {
    prompt: "Intrinsic activity of a partial agonist is:",
    explanation: "Partial agonists have affinity for the receptor but lower intrinsic activity (0 < efficacy < 1) compared to full agonists.",
    options: ["Between 0 and 1", "Equal to 1", "Equal to 0", "Greater than 1"],
    answer: 0,
  },
  {
    prompt: "Which organ is most affected by drug-induced fibrosis?",
    explanation: "The liver is the most common target of drug-induced fibrosis (e.g., methotrexate, amiodarone, isoniazid).",
    options: ["Liver", "Kidney", "Lung", "Heart"],
    answer: 0,
  },
  {
    prompt: "Anticholinergic effects include all EXCEPT:",
    explanation: "Anticholinergic effects: dry mouth, blurred vision, urinary retention, constipation, tachycardia. They cause mydriasis (dilation), NOT miosis (constriction).",
    options: ["Miosis (pupil constriction)", "Dry mouth (Xerostomia)", "Urinary retention", "Tachycardia"],
    answer: 0,
  },
];
