import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "The functional unit of the kidney is:",
    explanation: "The nephron is the functional unit of the kidney, responsible for filtration, reabsorption, and secretion.",
    options: ["Nephron", "Glomerulus", "Collecting duct", "Renal corpuscle"],
    answer: 0,
  },
  {
    prompt: "The glomerular filtration rate (GFR) in a healthy adult is approximately:",
    explanation: "Normal GFR is approximately 125 mL/min or 180 L/day. It is the best overall index of kidney function.",
    options: ["125 mL/min", "25 mL/min", "500 mL/min", "10 mL/min"],
    answer: 0,
  },
  {
    prompt: "The hormone responsible for water reabsorption in the collecting ducts is:",
    explanation: "ADH (antidiuretic hormone/vasopressin) increases water permeability of collecting ducts via aquaporin-2 channels.",
    options: ["ADH (Antidiuretic hormone)", "Aldosterone", "ANP", "Renin"],
    answer: 0,
  },
  {
    prompt: "The juxtaglomerular apparatus (JGA) is located between:",
    explanation: "The JGA is located between the afferent arteriole and the distal convoluted tubule of the same nephron.",
    options: ["Afferent arteriole and distal convoluted tubule", "Efferent arteriole and proximal tubule", "Glomerulus and Bowman's capsule", "Collecting duct and loop of Henle"],
    answer: 0,
  },
  {
    prompt: "Acute kidney injury (AKI) is most commonly caused by:",
    explanation: "Prerenal AKI (due to decreased renal perfusion, e.g., dehydration, heart failure, hemorrhage) is the most common cause.",
    options: ["Prerenal causes (dehydration, hypotension)", "Postrenal obstruction only", "Acute glomerulonephritis", "Renal artery stenosis"],
    answer: 0,
  },
  {
    prompt: "The most common cause of nephrotic syndrome in adults is:",
    explanation: "Membranous nephropathy is the most common cause of nephrotic syndrome in adults in Western countries.",
    options: ["Membranous nephropathy", "Minimal change disease", "Focal segmental glomerulosclerosis", "Diabetic nephropathy"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of metabolic acidosis?",
    explanation: "Metabolic acidosis shows decreased pH, decreased HCO3-, and compensatory decreased pCO2 (Kussmaul breathing).",
    options: ["Decreased pH with decreased HCO3-", "Increased pH with increased HCO3-", "Decreased pH with increased pCO2", "Normal pH with decreased HCO3-"],
    answer: 0,
  },
  {
    prompt: "The countercurrent multiplier system is located in:",
    explanation: "The countercurrent multiplier is located in the loop of Henle, creating the medullary osmotic gradient for water concentration.",
    options: ["Loop of Henle", "Proximal convoluted tubule", "Distal convoluted tubule", "Collecting duct"],
    answer: 0,
  },
  {
    prompt: "Which electrolyte abnormality is most commonly associated with chronic kidney disease?",
    explanation: "Hyperkalemia is a common and potentially life-threatening complication of CKD due to decreased potassium excretion.",
    options: ["Hyperkalemia", "Hypokalemia", "Hypernatremia", "Hypocalcemia (early)"],
    answer: 0,
  },
  {
    prompt: "The renin-angiotensin-aldosterone system (RAAS) is activated by:",
    explanation: "RAAS is activated by decreased renal perfusion pressure, sympathetic stimulation, and decreased NaCl at the macula densa.",
    options: ["Decreased renal perfusion pressure", "Increased blood volume", "Increased GFR", "Hypernatremia"],
    answer: 0,
  },
  {
    prompt: "Polycystic kidney disease (ADPKD) is inherited in which pattern?",
    explanation: "Autosomal Dominant Polycystic Kidney Disease (ADPKD) is inherited in an autosomal dominant pattern (PKD1 and PKD2 genes).",
    options: ["Autosomal dominant", "Autosomal recessive", "X-linked recessive", "Mitochondrial"],
    answer: 0,
  },
  {
    prompt: "The kidney's role in acid-base balance includes:",
    explanation: "The kidneys excrete H+ ions and reabsorb/generate HCO3- to maintain acid-base homeostasis (slower but more powerful than lungs).",
    options: ["Excreting H+ and reabsorbing/generating HCO3-", "Excreting HCO3- only", "Producing CO2", "Reabsorbing H+ from urine"],
    answer: 0,
  },
  {
    prompt: "BUN:Creatinine ratio > 20:1 suggests:",
    explanation: "A high BUN:Cr ratio (>20:1) suggests prerenal azotemia (dehydration, heart failure, GI bleeding) rather than intrinsic renal disease.",
    options: ["Prerenal azotemia", "Intrinsic renal disease", "Postrenal obstruction", "Normal kidney function"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of chronic kidney disease (CKD)?",
    explanation: "CKD features include: anemia (decreased EPO), renal osteodystrophy (calcium/phosphate imbalance), and metabolic acidosis.",
    options: ["Anemia from decreased erythropoietin", "Polyuria from diabetes insipidus", "Hypercalcemia", "Hypotension"],
    answer: 0,
  },
  {
    prompt: "The proximal convoluted tubule reabsorbs approximately what percentage of filtered sodium?",
    explanation: "The PCT reabsorbs approximately 65-70% of filtered sodium and water (obligatory reabsorption).",
    options: ["65-70%", "10-15%", "5%", "95%"],
    answer: 0,
  },
  {
    prompt: "Which drug class is nephroprotective in diabetic nephropathy?",
    explanation: "ACE inhibitors and ARBs reduce intraglomerular pressure and proteinuria, slowing progression of diabetic nephropathy.",
    options: ["ACE inhibitors / ARBs", "Calcium channel blockers", "Loop diuretics", "Potassium-sparing diuretics"],
    answer: 0,
  },
  {
    prompt: "Hematuria with dysmorphic RBCs and RBC casts suggests:",
    explanation: "Dysmorphic RBCs and RBC casts indicate glomerular origin of hematuria (glomerulonephritis).",
    options: ["Glomerulonephritis", "Urinary tract infection", "Kidney stones", "Bladder cancer"],
    answer: 0,
  },
  {
    prompt: "The osmolarity of urine can range from:",
    explanation: "The kidneys can concentrate urine up to ~1200 mOsm/kg or dilute it to ~50 mOsm/kg depending on hydration status.",
    options: ["50 to 1200 mOsm/kg", "300 to 300 mOsm/kg (fixed)", "1000 to 2000 mOsm/kg", "10 to 50 mOsm/kg"],
    answer: 0,
  },
  {
    prompt: "The most common cause of kidney stones (renal calculi) is:",
    explanation: "Calcium oxalate stones are the most common type of kidney stone (~80% of cases).",
    options: ["Calcium oxalate", "Uric acid", "Struvite (infection)", "Cystine"],
    answer: 0,
  },
  {
    prompt: "Urinary tract infections in women are more common than in men because:",
    explanation: "Women have a shorter urethra and its proximity to the vaginal and anal openings facilitates bacterial ascent.",
    options: ["Shorter urethra in women", "Larger bladder capacity in men", "Different pH of urine", "Stronger immune system in men"],
    answer: 0,
  },
  {
    prompt: "The normal serum potassium level is:",
    explanation: "Normal serum potassium is 3.5-5.0 mEq/L. Hyperkalemia (>5.5) can cause fatal cardiac arrhythmias.",
    options: ["3.5-5.0 mEq/L", "1.5-2.5 mEq/L", "6.0-7.0 mEq/L", "5.5-6.5 mEq/L"],
    answer: 0,
  },
  {
    prompt: "Acute glomerulonephritis typically presents with:",
    explanation: "Acute GN presents with nephritic syndrome: hematuria (cola-colored urine), hypertension, edema, and oliguria.",
    options: ["Hematuria, hypertension, edema, oliguria", "Massive proteinuria only", "Asymptomatic bacteriuria", "Flank pain"],
    answer: 0,
  },
  {
    prompt: "Which of the following is an indication for dialysis?",
    explanation: "Indications for dialysis: severe hyperkalemia, refractory metabolic acidosis, fluid overload, uremic encephalopathy, pericarditis.",
    options: ["Refractory hyperkalemia and metabolic acidosis", "Mild dehydration", "Normal kidney function", "Mild anemia"],
    answer: 0,
  },
  {
    prompt: "The clearance of which substance best estimates GFR?",
    explanation: "Inulin clearance is the gold standard for GFR measurement. Creatinine clearance is used clinically (though slightly overestimates GFR).",
    options: ["Inulin (or Creatinine clinically)", "Glucose", "Urea", "PAH"],
    answer: 0,
  },
  {
    prompt: "Nephrogenic diabetes insipidus is caused by:",
    explanation: "Nephrogenic DI results from the kidney's inability to respond to ADH (resistance to ADH action in collecting ducts).",
    options: ["Kidney resistance to ADH", "Decreased ADH production", "Excess ADH production", "Pituitary tumor"],
    answer: 0,
  },
  {
    prompt: "The normal pH of urine is:",
    explanation: "Normal urine pH ranges from 4.5 to 8.0, with an average of ~6.0 (slightly acidic).",
    options: ["4.5-8.0 (average ~6.0)", "7.35-7.45", "1.0-2.0", "8.0-10.0"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a feature of Fanconi syndrome?",
    explanation: "Fanconi syndrome is generalized dysfunction of the PCT with wasting of glucose, amino acids, phosphate, and bicarbonate.",
    options: ["Generalized proximal tubular dysfunction", "Distal tubular acidosis only", "Glomerular damage only", "Collecting duct dysfunction"],
    answer: 0,
  },
  {
    prompt: "The most common cause of end-stage renal disease (ESRD) in the US is:",
    explanation: "Diabetes mellitus is the leading cause of ESRD in the US and worldwide, followed by hypertension.",
    options: ["Diabetes mellitus", "Glomerulonephritis", "Polycystic kidney disease", "Hypertension"],
    answer: 0,
  },
  {
    prompt: "Aldosterone acts primarily on which part of the nephron?",
    explanation: "Aldosterone acts on the principal cells of the distal convoluted tubule and collecting duct, increasing Na+ reabsorption and K+ secretion.",
    options: ["Distal convoluted tubule and collecting duct", "Proximal convoluted tubule", "Loop of Henle", "Glomerulus"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the best initial test for evaluating kidney function?",
    explanation: "Serum creatinine and estimated GFR (eGFR) are the best initial tests for evaluating kidney function.",
    options: ["Serum creatinine with eGFR", "Urinalysis only", "Blood urea nitrogen (BUN) alone", "Kidney ultrasound"],
    answer: 0,
  },
  {
    prompt: "Postrenal azotemia is caused by:",
    explanation: "Postrenal azotemia results from urinary tract obstruction (e.g., BPH, kidney stones, tumors) causing back-pressure on the kidneys.",
    options: ["Urinary tract obstruction", "Decreased renal blood flow", "Glomerulonephritis", "Renal artery stenosis"],
    answer: 0,
  },
];
