import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "Which of the following is the correct number of lobes in the right lung?",
    explanation: "The right lung has 3 lobes (superior, middle, inferior) separated by horizontal and oblique fissures.",
    options: ["3 lobes", "2 lobes", "4 lobes", "5 lobes"],
    answer: 0,
  },
  {
    prompt: "Gas exchange in the lungs occurs at:",
    explanation: "Gas exchange occurs at the alveoli, where the respiratory membrane (alveolar and capillary walls) allows O2 and CO2 diffusion.",
    options: ["Alveoli", "Bronchioles", "Bronchi", "Trachea"],
    answer: 0,
  },
  {
    prompt: "The enzyme secreted by type II pneumocytes is:",
    explanation: "Type II pneumocytes secrete pulmonary surfactant, which reduces surface tension and prevents alveolar collapse.",
    options: ["Surfactant", "Mucus", "Histamine", "Pepsin"],
    answer: 0,
  },
  {
    prompt: "Which structure prevents food from entering the trachea during swallowing?",
    explanation: "The epiglottis folds over the laryngeal inlet during swallowing, directing food into the esophagus.",
    options: ["Epiglottis", "Uvula", "Soft palate", "Tongue"],
    answer: 0,
  },
  {
    prompt: "The most common site of bronchogenic carcinoma is:",
    explanation: "The hilum (central) of the lung is the most common site for bronchogenic carcinoma (squamous cell and small cell).",
    options: ["Hilum (central lung)", "Peripheral lung apex", "Lower lobe base", "Middle lobe"],
    answer: 0,
  },
  {
    prompt: "COPD includes which two conditions?",
    explanation: "COPD (Chronic Obstructive Pulmonary Disease) encompasses chronic bronchitis and emphysema.",
    options: ["Chronic bronchitis and emphysema", "Asthma and bronchiectasis", "Pneumonia and pleurisy", "Pulmonary fibrosis and sarcoidosis"],
    answer: 0,
  },
  {
    prompt: "The pleural fluid that reduces friction during breathing is produced by:",
    explanation: "The parietal pleura produces serous fluid that lubricates the pleural cavity, reducing friction during respiration.",
    options: ["Parietal pleura", "Visceral pleura", "Diaphragm", "Alveolar macrophages"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a characteristic of asthma?",
    explanation: "Asthma is characterized by reversible airflow obstruction, bronchial hyperresponsiveness, and airway inflammation.",
    options: ["Reversible airflow obstruction", "Irreversible fibrosis", "Alveolar destruction", "Pulmonary hypertension"],
    answer: 0,
  },
  {
    prompt: "Pneumothorax is defined as:",
    explanation: "Pneumothorax is the presence of air in the pleural space, causing lung collapse.",
    options: ["Air in the pleural space", "Fluid in the pleural space", "Infection in the lung", "Blockage of the airway"],
    answer: 0,
  },
  {
    prompt: "The main muscle of inspiration is:",
    explanation: "The diaphragm is the primary muscle of inspiration, contracting to increase thoracic volume.",
    options: ["Diaphragm", "External intercostals", "Abdominal muscles", "Sternocleidomastoid"],
    answer: 0,
  },
  {
    prompt: "Which organism is the most common cause of community-acquired pneumonia?",
    explanation: "Streptococcus pneumoniae is the most common cause of community-acquired pneumonia in adults.",
    options: ["Streptococcus pneumoniae", "Mycoplasma pneumoniae", "Legionella pneumophila", "Haemophilus influenzae"],
    answer: 0,
  },
  {
    prompt: "Tuberculosis primarily affects which part of the lung?",
    explanation: "TB has a predilection for the upper lobes (apical and posterior segments) due to higher oxygen tension.",
    options: ["Upper lobes (apical segments)", "Lower lobes (basal segments)", "Middle lobe", "Lingula"],
    answer: 0,
  },
  {
    prompt: "The respiratory membrane consists of:",
    explanation: "The respiratory membrane is composed of the alveolar epithelium, fused basement membrane, and capillary endothelium.",
    options: ["Alveolar epithelium, basement membrane, and capillary endothelium", "Bronchial smooth muscle and cartilage", "Tracheal mucosa and cilia", "Pleural membranes"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a sign of respiratory acidosis?",
    explanation: "Respiratory acidosis results from CO2 retention (hypoventilation) with low pH and elevated pCO2.",
    options: ["Elevated pCO2 with low pH", "Low pCO2 with high pH", "Normal pH with low pCO2", "High pH with normal pCO2"],
    answer: 0,
  },
  {
    prompt: "Cystic fibrosis primarily affects which organ?",
    explanation: "Cystic fibrosis is a genetic disease caused by CFTR mutation, primarily affecting the lungs (thick mucus) and pancreas.",
    options: ["Lungs (and pancreas)", "Heart", "Brain", "Liver only"],
    answer: 0,
  },
  {
    prompt: "The hum in the lungs heard on auscultation is called:",
    explanation: "Vesicular breath sounds are normal breath sounds heard over most lung fields during quiet breathing.",
    options: ["Vesicular breath sounds", "Bronchial breath sounds", "Crackles (rales)", "Wheezing"],
    answer: 0,
  },
  {
    prompt: "Which gas has the highest partial pressure in alveolar air?",
    explanation: "Nitrogen (N2) has the highest partial pressure in alveolar air (~569 mmHg), followed by oxygen (~104 mmHg).",
    options: ["Nitrogen (N2)", "Oxygen (O2)", "Carbon dioxide (CO2)", "Water vapor"],
    answer: 0,
  },
  {
    prompt: "Pulmonary embolism most commonly originates from:",
    explanation: "Most pulmonary emboli originate from deep vein thrombosis (DVT) in the lower extremities.",
    options: ["Deep vein thrombosis (DVT) in legs", "Right atrial thrombus", "Pulmonary artery atherosclerosis", "Venous catheter"],
    answer: 0,
  },
  {
    prompt: "The compliance of the lung refers to:",
    explanation: "Lung compliance is the ability of the lung to stretch and expand (change in volume per unit change in pressure).",
    options: ["Lung's ability to stretch and expand", "Resistance to airflow", "Blood flow through the lung", "Gas exchange efficiency"],
    answer: 0,
  },
  {
    prompt: "Which type of lung cancer is strongly associated with smoking?",
    explanation: "Small cell lung cancer (SCLC) is most strongly associated with smoking (>95% of cases).",
    options: ["Small cell lung cancer", "Adenocarcinoma", "Bronchoalveolar carcinoma", "Carcinoid tumor"],
    answer: 0,
  },
  {
    prompt: "A chest X-ray showing a 'white-out' of one hemithorax suggests:",
    explanation: "Complete opacification of a hemithorax may indicate total lung collapse, massive pleural effusion, or pneumonectomy.",
    options: ["Complete lung collapse or massive effusion", "Early pneumonia", "Pneumothorax", "Normal finding"],
    answer: 0,
  },
  {
    prompt: "The Hering-Breuer reflex prevents:",
    explanation: "The Hering-Breuer inflation reflex prevents over-inflation of the lungs by inhibiting inspiration when the lung is stretched.",
    options: ["Over-inflation of the lungs", "Lung collapse", "Excessive mucus production", "Pulmonary edema"],
    answer: 0,
  },
  {
    prompt: "Which of the following best describes bronchiectasis?",
    explanation: "Bronchiectasis is permanent dilation and destruction of bronchi and bronchioles due to chronic infection and inflammation.",
    options: ["Permanent dilation of airways", "Narrowing of airways", "Alveolar destruction", "Pleural thickening"],
    answer: 0,
  },
  {
    prompt: "The oxygen-hemoglobin dissociation curve shifts to the RIGHT with:",
    explanation: "Factors that shift the curve right (decreased affinity): increased temperature, increased CO2, decreased pH, increased 2,3-DPG.",
    options: ["Increased CO2, decreased pH, increased temperature", "Decreased CO2, increased pH, decreased temperature", "Carbon monoxide poisoning", "Methemoglobinemia"],
    answer: 0,
  },
  {
    prompt: "Silicosis is caused by inhalation of:",
    explanation: "Silicosis is caused by inhalation of crystalline silica dust, commonly in mining, sandblasting, and quarrying.",
    options: ["Crystalline silica dust", "Asbestos fibers", "Coal dust", "Cotton dust"],
    answer: 0,
  },
  {
    prompt: "The pH of arterial blood is normally:",
    explanation: "Normal arterial blood pH is 7.35-7.45. Values below 7.35 indicate acidosis, above 7.45 indicate alkalosis.",
    options: ["7.35-7.45", "6.8-7.0", "7.55-7.70", "7.00-7.20"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the earliest sign of lung cancer on chest X-ray?",
    explanation: "A solitary pulmonary nodule or mass is often the earliest radiographic sign of lung cancer.",
    options: ["Solitary pulmonary nodule or mass", "Pleural effusion", "Mediastinal widening", "Rib destruction"],
    answer: 0,
  },
  {
    prompt: "The concept of V/Q (ventilation-perfusion) mismatch explains:",
    explanation: "V/Q mismatch occurs when ventilation and blood flow are not matched, impairing gas exchange (e.g., pulmonary embolism, pneumonia).",
    options: ["Impaired gas exchange from ventilation-blood flow mismatch", "Airway narrowing", "Pleural disease", "Diaphragmatic weakness"],
    answer: 0,
  },
  {
    prompt: "Which of the following drugs is a short-acting beta-2 agonist (SABA)?",
    explanation: "Salbutamol (Albuterol) is a short-acting beta-2 agonist used for acute bronchospasm relief.",
    options: ["Salbutamol (Albuterol)", "Fluticasone", "Montelukast", "Tiotropium"],
    answer: 0,
  },
  {
    prompt: "ARDS is characterized by:",
    explanation: "ARDS (Acute Respiratory Distress Syndrome) is characterized by non-cardiogenic pulmonary edema, severe hypoxemia, and bilateral infiltrates.",
    options: ["Non-cardiogenic pulmonary edema and severe hypoxemia", "Chronic airway obstruction", "Fibrotic lung disease", "Pleural effusion"],
    answer: 0,
  },
  {
    prompt: "The dead space in the lung refers to:",
    explanation: "Dead space is the volume of ventilated air that does not participate in gas exchange (anatomical + physiological dead space).",
    options: ["Ventilated air that does not participate in gas exchange", "Blood that does not reach the alveoli", "Alveoli without capillaries", "Blocked airways"],
    answer: 0,
  },
];
