import type { SeedQuestion } from "../seed-mcq-all";

export const questions: SeedQuestion[] = [
  {
    prompt: "Which of the following is the most common cause of preventable death worldwide?",
    explanation: "Tobacco use is the leading preventable cause of death worldwide, responsible for ~8 million deaths annually.",
    options: ["Tobacco use", "Alcohol use", "Poor diet", "Physical inactivity"],
    answer: 0,
  },
  {
    prompt: "Epidemiology is defined as:",
    explanation: "Epidemiology is the study of the distribution and determinants of health-related states and events in populations.",
    options: ["Study of disease distribution and determinants in populations", "Study of individual disease processes", "Study of treatment effectiveness", "Study of hospital infections"],
    answer: 0,
  },
  {
    prompt: "The incidence rate differs from prevalence in that:",
    explanation: "Incidence measures new cases over a period, while prevalence measures all existing cases (new + old) at a point or period.",
    options: ["Incidence measures new cases; prevalence measures all cases", "Incidence measures mortality; prevalence measures morbidity", "They are the same thing", "Incidence is always higher than prevalence"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a primary prevention measure?",
    explanation: "Primary prevention aims to prevent disease before it occurs (e.g., vaccination, health education, sanitation).",
    options: ["Vaccination", "Screening tests", "Treatment of disease", "Rehabilitation"],
    answer: 0,
  },
  {
    prompt: "The relative risk (RR) is calculated as:",
    explanation: "Relative Risk = Incidence in exposed / Incidence in unexposed. RR > 1 indicates a positive association.",
    options: ["Incidence in exposed / Incidence in unexposed", "Odds in exposed / Odds in unexposed", "Prevalence in exposed / Prevalence in unexposed", "Mortality in exposed / Mortality in unexposed"],
    answer: 0,
  },
  {
    prompt: "A case-control study starts with:",
    explanation: "Case-control studies start with cases (disease present) and controls (disease absent), then look back at exposure history.",
    options: ["Cases and controls (with/without disease)", "Exposed and unexposed individuals", "A random sample of the population", "A cohort of healthy individuals"],
    answer: 0,
  },
  {
    prompt: "The most effective public health intervention in history is:",
    explanation: "Provision of clean water and sanitation has saved more lives than any other public health intervention.",
    options: ["Clean water and sanitation", "Antibiotics", "Vaccination", "Surgery"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a risk factor for coronary artery disease?",
    explanation: "Major risk factors for CAD: smoking, hypertension, diabetes, hyperlipidemia, obesity, family history, age.",
    options: ["Smoking, hypertension, diabetes, hyperlipidemia", "Low blood pressure", "Young age", "High physical activity"],
    answer: 0,
  },
  {
    prompt: "BMI (Body Mass Index) is calculated as:",
    explanation: "BMI = Weight (kg) / Height (m squared). Categories: <18.5 underweight, 18.5-24.9 normal, 25-29.9 overweight, >=30 obese.",
    options: ["Weight (kg) / Height (m squared)", "Weight (lb) / Height (in)", "Height (cm) / Weight (kg)", "Weight (kg) x Height (m)"],
    answer: 0,
  },
  {
    prompt: "The leading cause of death globally is:",
    explanation: "Ischemic heart disease is the leading cause of death globally, followed by stroke.",
    options: ["Ischemic heart disease", "Infectious diarrhea", "Road traffic accidents", "Lung cancer"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a measure of disease frequency in cross-sectional studies?",
    explanation: "Prevalence is the measure used in cross-sectional studies, representing all existing cases at a specific point in time.",
    options: ["Prevalence", "Incidence", "Cumulative incidence", "Incidence rate"],
    answer: 0,
  },
  {
    prompt: "The attributable risk (AR) measures:",
    explanation: "Attributable risk = Incidence in exposed - Incidence in unexposed. It measures the excess risk due to the exposure.",
    options: ["Excess risk due to exposure in the exposed group", "Total risk in the population", "Risk ratio between groups", "Reduction in risk from intervention"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the best measure of association in a cohort study?",
    explanation: "Relative risk (RR) and attributable risk are the primary measures of association in prospective cohort studies.",
    options: ["Relative risk (RR)", "Odds ratio (OR)", "Attributable risk percent", "Number needed to treat"],
    answer: 0,
  },
  {
    prompt: "Herd immunity threshold for measles requires approximately what vaccination coverage?",
    explanation: "Measles is highly contagious (R0 ~12-18) and requires ~93-95% vaccination coverage for herd immunity.",
    options: ["93-95%", "70-80%", "50-60%", "99-100%"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a social determinant of health?",
    explanation: "Social determinants include income, education, employment, housing, food security, and access to healthcare.",
    options: ["Income and education level", "Blood type", "Genetic predisposition only", "Eye color"],
    answer: 0,
  },
  {
    prompt: "Positive predictive value (PPV) depends on:",
    explanation: "PPV depends on disease prevalence. Higher prevalence increases PPV. Sensitivity and specificity also affect PPV.",
    options: ["Disease prevalence (and sensitivity/specificity)", "Only sensitivity", "Only specificity", "Sample size only"],
    answer: 0,
  },
  {
    prompt: "The basic reproduction number (R0) for a disease indicates:",
    explanation: "R0 is the average number of secondary infections produced by one infected individual in a fully susceptible population.",
    options: ["Average secondary infections from one case in susceptible population", "Total number of cases in an outbreak", "Mortality rate of the disease", "Recovery rate"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a confounding variable?",
    explanation: "A confounding variable is associated with both the exposure and the outcome, distorting the true relationship between them.",
    options: ["A variable associated with both exposure and outcome", "The outcome variable", "The exposure variable", "A random variable"],
    answer: 0,
  },
  {
    prompt: "Screening programs are most useful when:",
    explanation: "Screening is most useful when: disease is common, has a long pre-symptomatic period, and effective treatment is available.",
    options: ["Disease has long pre-symptomatic period and effective treatment exists", "Disease is rare and untreatable", "Disease is acute and self-limiting", "Disease affects young people only"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a measure of effect modification?",
    explanation: "Effect modification occurs when the effect of an exposure on the outcome differs across levels of another variable (e.g., age, sex).",
    options: ["The effect of exposure differs across subgroups", "The effect is the same in all subgroups", "A third variable distorts the association", "The exposure has no effect"],
    answer: 0,
  },
  {
    prompt: "Malnutrition in developing countries is primarily caused by:",
    explanation: "Poverty is the root cause of malnutrition, leading to inadequate food intake, poor diet quality, and increased disease burden.",
    options: ["Poverty and food insecurity", "Overeating", "Food allergies", "Excessive vitamin intake"],
    answer: 0,
  },
  {
    prompt: "The disability-adjusted life year (DALY) measures:",
    explanation: "DALY = Years of Life Lost (YLL) + Years Lived with Disability (YLD). It measures the total burden of disease.",
    options: ["Total burden of disease (YLL + YLD)", "Life expectancy only", "Mortality rate only", "Quality of life only"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a health system building block (WHO)?",
    explanation: "WHO's 6 building blocks: service delivery, health workforce, information, medical products/vaccines/technologies, financing, leadership/governance.",
    options: ["Service delivery, health workforce, health information", "Disease only treatment", "Hospital construction only", "Medical research only"],
    answer: 0,
  },
  {
    prompt: "The odds ratio (OR) is used in which study design when the disease is rare?",
    explanation: "The odds ratio approximates the relative risk when the disease is rare (<10%), and is the primary measure in case-control studies.",
    options: ["Case-control studies (rare disease)", "Randomized controlled trials", "Cohort studies", "Cross-sectional studies"],
    answer: 0,
  },
  {
    prompt: "Vector-borne diseases include all EXCEPT:",
    explanation: "Vector-borne: malaria (mosquito), dengue (mosquito), leishmaniasis (sandfly). Tuberculosis is airborne, not vector-borne.",
    options: ["Tuberculosis", "Malaria", "Dengue fever", "Leishmaniasis"],
    answer: 0,
  },
  {
    prompt: "The infant mortality rate is defined as:",
    explanation: "IMR = number of deaths of infants under 1 year per 1,000 live births. It is a key indicator of population health.",
    options: ["Deaths under 1 year per 1,000 live births", "Deaths under 5 years per 100 births", "Births per 1,000 population", "Maternal deaths per 100,000"],
    answer: 0,
  },
  {
    prompt: "Which of the following is a waterborne disease?",
    explanation: "Cholera, typhoid fever, hepatitis A, and cryptosporidiosis are transmitted through contaminated water.",
    options: ["Cholera", "Measles", "Tuberculosis", "HIV/AIDS"],
    answer: 0,
  },
  {
    prompt: "The number needed to treat (NNT) is calculated as:",
    explanation: "NNT = 1 / Absolute Risk Reduction (ARR). It represents the number of patients needed to treat to prevent one adverse outcome.",
    options: ["1 / Absolute Risk Reduction (ARR)", "1 / Relative Risk Reduction", "ARR x 100", "1 / Odds Ratio"],
    answer: 0,
  },
  {
    prompt: "Which of the following is the most important global cause of childhood mortality?",
    explanation: "Pneumonia is the single largest infectious cause of death in children worldwide.",
    options: ["Pneumonia", "Malaria", "Diarrheal diseases", "HIV/AIDS"],
    answer: 0,
  },
  {
    prompt: "The healthy worker effect is a type of:",
    explanation: "The healthy worker effect is a form of selection bias where employed populations appear healthier than the general population.",
    options: ["Selection bias", "Information bias", "Confounding", "Random error"],
    answer: 0,
  },
  {
    prompt: "Informed consent in public health research requires:",
    explanation: "Informed consent requires: disclosure of information, comprehension, voluntariness, competence, and agreement.",
    options: ["Disclosure, comprehension, voluntariness, competence, and agreement", "Only a signed form", "Verbal agreement only", "Physician approval only"],
    answer: 0,
  },
];
