import type { SeedQuestion } from "../seed-mcq-all";

/**
 * OSPE CVS Question Bank — 60 clinical MCQs
 * Style: "Identify the structure", "Name the pathology", "What is the diagnosis?"
 * imageUrl points to the OSPE image API (user uploads real images later)
 */

function img(file: string): string {
  return `/api/content/ospe/image?folder=CVS&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ─────────────────────────────────────────────────────────
  //  ANATOMY — Identify the structure (20 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "Identify the nerve indicated by the arrow in the mediastinum.",
    imageUrl: img("cvs-anatomy-001-nerve-identification.jpg"),
    options: ["Phrenic nerve", "Vagus nerve", "Recurrent laryngeal nerve", "Sympathetic trunk"],
    answer: 0,
    explanation: "The phrenic nerve runs along the pericardium between the heart and lungs, innervating the diaphragm.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this part of the cardiac conducting system located in the right atrium.",
    imageUrl: img("cvs-anatomy-002-conducting-system-sa-node.jpg"),
    options: ["SA node", "AV node", "Bundle of His", "Purkinje fibers"],
    answer: 0,
    explanation: "The sinoatrial (SA) node is the primary pacemaker, located in the right atrium near the superior vena cava.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this major vessel entering the right atrium from above.",
    imageUrl: img("cvs-anatomy-003-vessel-superior-vena-cava.jpg"),
    options: ["Superior vena cava", "Inferior vena cava", "Pulmonary artery", "Aorta"],
    answer: 0,
    explanation: "The superior vena cava drains blood from the upper body into the right atrium.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this major vessel entering the right atrium from below.",
    imageUrl: img("cvs-anatomy-004-vessel-inferior-vena-cava.jpg"),
    options: ["Inferior vena cava", "Superior vena cava", "Coronary sinus", "Hepatic vein"],
    answer: 0,
    explanation: "The inferior vena cava returns deoxygenated blood from the lower body to the right atrium.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the largest artery in the body arising from the left ventricle.",
    imageUrl: img("cvs-anatomy-005-vessel-aorta.jpg"),
    options: ["Aorta", "Pulmonary trunk", "Brachiocephalic artery", "Left common carotid"],
    answer: 0,
    explanation: "The aorta is the largest artery, arising from the left ventricle and distributing oxygenated blood to the body.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this valve located between the right atrium and right ventricle.",
    imageUrl: img("cvs-anatomy-011-valve-tricuspid.jpg"),
    options: ["Tricuspid valve", "Mitral valve", "Pulmonary valve", "Aortic valve"],
    answer: 0,
    explanation: "The tricuspid valve has three cusps and guards the right atrioventricular orifice.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this valve located between the left atrium and left ventricle.",
    imageUrl: img("cvs-anatomy-012-valve-mitral.jpg"),
    options: ["Mitral (bicuspid) valve", "Tricuspid valve", "Aortic valve", "Pulmonary valve"],
    answer: 0,
    explanation: "The mitral valve is the only bicuspid valve, guarding the left atrioventricular orifice.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this semilunar valve at the base of the pulmonary trunk.",
    imageUrl: img("cvs-anatomy-009-valve-pulmonary.jpg"),
    options: ["Pulmonary valve", "Aortic valve", "Tricuspid valve", "Mitral valve"],
    answer: 0,
    explanation: "The pulmonary valve has three semilunar cusps at the exit of the right ventricle.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this semilunar valve at the base of the ascending aorta.",
    imageUrl: img("cvs-anatomy-010-valve-aortic.jpg"),
    options: ["Aortic valve", "Pulmonary valve", "Mitral valve", "Tricuspid valve"],
    answer: 0,
    explanation: "The aortic valve has three cusps (right, left, posterior) at the left ventricular outflow tract.",
    difficulty: "medium",
  },
  {
    prompt: "Identify these cord-like structures connecting papillary muscles to valve cusps.",
    imageUrl: img("cvs-anatomy-016-chordae-tendineae.jpg"),
    options: ["Chordae tendineae", "Trabeculae carneae", "Pectinate muscles", "Moderator band"],
    answer: 0,
    explanation: "Chordae tendineae prevent AV valve eversion during ventricular systole.",
    difficulty: "medium",
  },
  {
    prompt: "Identify these muscular ridges on the internal surface of the ventricles.",
    imageUrl: img("cvs-anatomy-013-trabeculae-carneae.jpg"),
    options: ["Trabeculae carneae", "Chordae tendineae", "Pectinate muscles", "Crista terminalis"],
    answer: 0,
    explanation: "Trabeculae carneae are irregular muscular columns on the ventricular walls.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this finger-like projection inside the ventricle that anchors chordae tendineae.",
    imageUrl: img("cvs-anatomy-014-papillary-muscle.jpg"),
    options: ["Papillary muscle", "Trabeculae carneae", "Moderator band", "Columnae carneae"],
    answer: 0,
    explanation: "Papillary muscles contract during systole to prevent prolapse of AV valve cusps via chordae tendineae.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this oval depression in the interatrial septum.",
    imageUrl: img("cvs-anatomy-015-fossa-ovalis.jpg"),
    options: ["Fossa ovalis", "Foramen ovale", "Interventricular foramen", "PFO"],
    answer: 0,
    explanation: "The fossa ovalis is the remnant of the foramen ovale in the adult interatrial septum.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this structure in the right ventricle that crosses the ventricular cavity.",
    imageUrl: img("cvs-anatomy-047-moderator-band.jpg"),
    options: ["Moderator band (septomarginal trabecula)", "Chordae tendineae", "Papillary muscle", "Trabeculae carneae"],
    answer: 0,
    explanation: "The moderator band carries part of the right bundle branch to the anterior papillary muscle.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this coronary artery running in the anterior interventricular groove.",
    imageUrl: img("cvs-anatomy-022-coronary-left-anterior-descending.jpg"),
    options: ["Left anterior descending (LAD) artery", "Circumflex artery", "Right coronary artery", "Posterior descending artery"],
    answer: 0,
    explanation: "The LAD supplies the anterior wall of the left ventricle and the anterior two-thirds of the interventricular septum.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this coronary artery arising from the right aortic sinus.",
    imageUrl: img("cvs-anatomy-023-coronary-right.jpg"),
    options: ["Right coronary artery (RCA)", "Left coronary artery", "Circumflex artery", "LAD artery"],
    answer: 0,
    explanation: "The RCA supplies the right ventricle, SA node, and in right-dominant hearts, the inferior wall.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this vessel entering the left atrium from the lungs.",
    imageUrl: img("cvs-anatomy-026-pulmonary-vein.jpg"),
    options: ["Pulmonary vein", "Pulmonary artery", "Superior vena cava", "Aorta"],
    answer: 0,
    explanation: "Four pulmonary veins (two from each lung) carry oxygenated blood to the left atrium.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this nerve descending in the thorax along the trachea.",
    imageUrl: img("cvs-anatomy-021-recurrent-laryngeal.jpg"),
    options: ["Recurrent laryngeal nerve", "Phrenic nerve", "Vagus nerve", "Sympathetic chain"],
    answer: 0,
    explanation: "The recurrent laryngeal nerve loops under the aortic arch (left) or subclavian artery (right) to innervate laryngeal muscles.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this vein draining into the right atrium via the coronary sulcus.",
    imageUrl: img("cvs-anatomy-048-coronary-sinus-opening.jpg"),
    options: ["Coronary sinus", "Great cardiac vein", "Azygos vein", "Hemiazygos vein"],
    answer: 0,
    explanation: "The coronary sinus receives most cardiac venous blood and empties into the right atrium.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this ridge on the internal wall of the right atrium.",
    imageUrl: img("cvs-anatomy-049-crista-terminalis.jpg"),
    options: ["Crista terminalis", "Pectinate muscles", "Fossa ovalis", "Tuberculum of Lower"],
    answer: 0,
    explanation: "The crista terminalis is a vertical ridge separating the smooth posterior and rough anterior right atrial walls.",
    difficulty: "hard",
  },

  // ─────────────────────────────────────────────────────────
  //  HISTOLOGY — Identify tissue / layer (15 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "Identify this innermost layer of a large elastic artery.",
    imageUrl: img("cvs-histo-001-tunica-intima.jpg"),
    options: ["Tunica intima", "Tunica media", "Tunica adventitia", "Internal elastic lamina"],
    answer: 0,
    explanation: "The tunica intima consists of endothelium and a thin subendothelial layer.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this thick middle layer of the aorta.",
    imageUrl: img("cvs-histo-002-tunica-media.jpg"),
    options: ["Tunica media", "Tunica intima", "Tunica adventitia", "External elastic lamina"],
    answer: 0,
    explanation: "The tunica media contains smooth muscle and elastic lamellae, giving large arteries their elasticity.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this tissue type characterized by branching striated cells with intercalated discs.",
    imageUrl: img("cvs-histo-004-cardiac-muscle-cross-section.jpg"),
    options: ["Cardiac muscle", "Skeletal muscle", "Smooth muscle", "Dense regular connective tissue"],
    answer: 0,
    explanation: "Cardiac muscle is striated, branched, and connected by intercalated discs containing gap junctions.",
    difficulty: "easy",
  },
  {
    prompt: "Identify these specialized junctions between cardiac muscle cells.",
    imageUrl: img("cvs-histo-006-intercalated-discs.jpg"),
    options: ["Intercalated discs", "Desmosomes", "Gap junctions", "Tight junctions"],
    answer: 0,
    explanation: "Intercalated discs contain fascia adherens, desmosomes, and gap junctions for mechanical and electrical coupling.",
    difficulty: "easy",
  },
  {
    prompt: "Identify these pale-staining specialized cardiac muscle fibers in the ventricular wall.",
    imageUrl: img("cvs-histo-007-purkinje-fibers.jpg"),
    options: ["Purkinje fibers", "Cardiac myocytes", "Smooth muscle cells", "Nerve fibers"],
    answer: 0,
    explanation: "Purkinje fibers are larger, paler, and conduct action potentials faster than普通 cardiac myocytes.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of artery with prominent elastic lamellae in the tunica media.",
    imageUrl: img("cvs-histo-008-elastic-artery.jpg"),
    options: ["Elastic (conducting) artery", "Muscular artery", "Arteriole", "Venule"],
    answer: 0,
    explanation: "Elastic arteries (e.g., aorta) have 40-70 concentric elastic lamellae in the tunica media.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this artery with a prominent internal elastic lamina and smooth muscle media.",
    imageUrl: img("cvs-histo-009-muscular-artery.jpg"),
    options: ["Muscular (distributing) artery", "Elastic artery", "Arteriole", "Capillary"],
    answer: 0,
    explanation: "Muscular arteries have a well-defined internal elastic lamina and thick smooth muscle media.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this small vessel with one or two layers of smooth muscle.",
    imageUrl: img("cvs-histo-010-arteriole.jpg"),
    options: ["Arteriole", "Capillary", "Venule", "Muscular artery"],
    answer: 0,
    explanation: "Arterioles regulate peripheral resistance and blood pressure through smooth muscle contraction.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this vessel with a thin wall consisting mainly of endothelium.",
    imageUrl: img("cvs-histo-011-capillary.jpg"),
    options: ["Capillary", "Arteriole", "Venule", "Lymphatic vessel"],
    answer: 0,
    explanation: "Capillaries are the smallest vessels, consisting of a single endothelial layer for exchange.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this layer lining the internal surface of the heart chambers.",
    imageUrl: img("cvs-histo-014-endocardium.jpg"),
    options: ["Endocardium", "Myocardium", "Epicardium", "Pericardium"],
    answer: 0,
    explanation: "The endocardium is a thin layer of endothelium and subendocardial connective tissue lining the heart chambers.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this thick muscular middle layer of the heart wall.",
    imageUrl: img("cvs-histo-015-myocardium.jpg"),
    options: ["Myocardium", "Endocardium", "Epicardium", "Pericardium"],
    answer: 0,
    explanation: "The myocardium is the thickest layer, composed of cardiac muscle responsible for contraction.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this outermost layer of the heart wall (visceral pericardium).",
    imageUrl: img("cvs-histo-016-epicardium.jpg"),
    options: ["Epicardium (visceral pericardium)", "Myocardium", "Endocardium", "Parietal pericardium"],
    answer: 0,
    explanation: "The epicardium consists of mesothelium and connective tissue, forming the visceral layer of the serous pericardium.",
    difficulty: "easy",
  },
  {
    prompt: "Identify these specialized cells in the sinoatrial node.",
    imageUrl: img("cvs-histo-017-sa-node.jpg"),
    options: ["SA nodal cells (pacemaker cells)", "Purkinje fibers", "Cardiac myocytes", "Smooth muscle cells"],
    answer: 0,
    explanation: "SA nodal cells are smaller than普通 myocytes and spontaneously depolarize to set the heart rate.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this pathological change: golden-brown pigment in cardiac macrophages after MI.",
    imageUrl: img("cvs-histo-025-hemosiderin-heart.jpg"),
    options: ["Hemosiderin deposition", "Lipofuscin accumulation", "Amyloid deposition", "Calcification"],
    answer: 0,
    explanation: "Hemosiderin (iron-containing pigment) appears in macrophages as hemoglobin is broken down after hemorrhage or MI.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this pathognomonic lesion of rheumatic heart disease.",
    imageUrl: img("cvs-histo-027-aschoff-body.jpg"),
    options: ["Aschoff body", "Ghon focus", "Granuloma", "Libman-Sacks vegetation"],
    answer: 0,
    explanation: "Aschoff bodies are granulomatous lesions with Anitschkow cells, pathognomonic of acute rheumatic fever.",
    difficulty: "hard",
  },

  // ─────────────────────────────────────────────────────────
  //  PATHOLOGY — Name the diagnosis / stage (20 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "What stage of myocardial infarction is shown? (1-3 hours post-MI)",
    imageUrl: img("cvs-patho-001-mi-wavy-fibers-1-3-hours.jpg"),
    options: [
      "Wavy fibers (1-3 hours)",
      "Coagulative necrosis (1-3 days)",
      "Neutrophilic infiltration (3-7 days)",
      "Granulation tissue (10-14 days)",
    ],
    answer: 0,
    explanation: "In the first 1-3 hours, MI shows wavy fibers, contraction bands, and early coagulative necrosis.",
    difficulty: "hard",
  },
  {
    prompt: "What stage of myocardial infarction is shown? (1-3 days)",
    imageUrl: img("cvs-patho-002-mi-coagulative-necrosis-1-3-days.jpg"),
    options: [
      "Coagulative necrosis with early neutrophilic infiltrate (1-3 days)",
      "Wavy fibers (1-3 hours)",
      "Macrophage infiltration (7-10 days)",
      "Collagenous scar (2+ weeks)",
    ],
    answer: 0,
    explanation: "At 1-3 days, MI shows coagulative necrosis with pyknosis, karyolysis, and neutrophilic infiltration.",
    difficulty: "hard",
  },
  {
    prompt: "What type of endocarditis shows sterile vegetations on both sides of the valve cusps?",
    imageUrl: img("cvs-patho-013-libman-sacks-endocarditis.jpg"),
    options: [
      "Libman-Sacks endocarditis (SLE)",
      "Infective endocarditis",
      "Rheumatic endocarditis",
      "Carcinoid heart disease",
    ],
    answer: 0,
    explanation: "Libman-Sacks endocarditis is associated with SLE and shows small, sterile vegetations on both surfaces of valve cusps.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of cardiomyopathy characterized by four-chamber dilation.",
    imageUrl: img("cvs-patho-014-dilated-cardiomyopathy.jpg"),
    options: [
      "Dilated cardiomyopathy",
      "Hypertrophic cardiomyopathy",
      "Restrictive cardiomyopathy",
      "Arrhythmogenic right ventricular cardiomyopathy",
    ],
    answer: 0,
    explanation: "Dilated cardiomyopathy shows global chamber dilation with reduced systolic function, often idiopathic or viral.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this cardiomyopathy showing asymmetric septal hypertrophy.",
    imageUrl: img("cvs-patho-015-hypertrophic-cardiomyopathy.jpg"),
    options: [
      "Hypertrophic cardiomyopathy (HCM)",
      "Dilated cardiomyopathy",
      "Restrictive cardiomyopathy",
      "Athlete's heart",
    ],
    answer: 0,
    explanation: "HCM shows asymmetric septal hypertrophy, myocyte disarray, and fibrosis; a common cause of sudden death in young athletes.",
    difficulty: "medium",
  },
  {
    prompt: "What is the most likely diagnosis? Aortic wall shows intimal tear with false lumen.",
    imageUrl: img("cvs-patho-010-aortic-dissection.jpg"),
    options: [
      "Aortic dissection",
      "Aortic aneurysm",
      "Atherosclerosis",
      "Aortitis",
    ],
    answer: 0,
    explanation: "Aortic dissection occurs when blood enters the media through an intimal tear, creating a false lumen.",
    difficulty: "medium",
  },
  {
    prompt: "What is the diagnosis? Heart valve shows large, irregular, friable vegetations.",
    imageUrl: img("cvs-patho-012-vegetation-endocarditis.jpg"),
    options: [
      "Infective (bacterial) endocarditis",
      "Rheumatic endocarditis",
      "Libman-Sacks endocarditis",
      "Carcinoid heart disease",
    ],
    answer: 0,
    explanation: "Infective endocarditis shows large, irregular vegetations with microorganisms and inflammatory cells.",
    difficulty: "medium",
  },
  {
    prompt: "What stage of atherosclerosis is shown? Intimal lipid streak.",
    imageUrl: img("cvs-patho-059-atherosclerosis-fatty-streak.jpg"),
    options: [
      "Fatty streak (early lesion)",
      "Fibrofatty plaque",
      "Complicated plaque",
      "Calcified plaque",
    ],
    answer: 0,
    explanation: "Fatty streaks are the earliest visible lesions of atherosclerosis, appearing as yellow streaks in the intima.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this atherosclerotic lesion with a lipid core and fibrous cap.",
    imageUrl: img("cvs-patho-008-atherosclerosis-fibrofatty-plaque.jpg"),
    options: [
      "Fibrofatty (atheromatous) plaque",
      "Fatty streak",
      "Complicated plaque",
      "Calcified lesion",
    ],
    answer: 0,
    explanation: "The atheromatous plaque has a necrotic lipid core covered by a fibrous cap of smooth muscle and collagen.",
    difficulty: "medium",
  },
  {
    prompt: "What complication of atherosclerosis is shown? Plaque rupture with superimposed thrombus.",
    imageUrl: img("cvs-patho-009-atherosclerosis-complicated-plaque.jpg"),
    options: [
      "Complicated plaque (rupture + thrombosis)",
      "Fatty streak",
      "Calcified plaque",
      "Fibrofatty plaque",
    ],
    answer: 0,
    explanation: "Plaque rupture exposes thrombogenic material, leading to acute thrombosis and potential MI or stroke.",
    difficulty: "hard",
  },
  {
    prompt: "What is the diagnosis? Pericardial space filled with blood.",
    imageUrl: img("cvs-patho-018-cardiac-tamponade.jpg"),
    options: [
      "Cardiac tamponade (hemopericardium)",
      "Constrictive pericarditis",
      "Pericardial effusion",
      "Myocardial rupture",
    ],
    answer: 0,
    explanation: "Cardiac tamponade is compression of the heart due to accumulation of fluid (often blood) in the pericardial sac.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this pericardial condition with thickened, fibrotic pericardium restricting filling.",
    imageUrl: img("cvs-patho-019-constrictive-pericarditis.jpg"),
    options: [
      "Constrictive pericarditis",
      "Cardiac tamponade",
      "Acute pericarditis",
      "Pericardial effusion",
    ],
    answer: 0,
    explanation: "Constrictive pericarditis shows a thickened, fibrotic (sometimes calcified) pericardium restricting diastolic filling.",
    difficulty: "medium",
  },
  {
    prompt: "What is the diagnosis? This tumor is the most common primary cardiac neoplasm.",
    imageUrl: img("cvs-patho-034-cardiac-myxoma.jpg"),
    options: [
      "Cardiac myxoma",
      "Cardiac rhabdomyoma",
      "Angiosarcoma",
      "Lipoma",
    ],
    answer: 0,
    explanation: "Cardiac myxoma is the most common primary cardiac tumor, typically in the left atrium attached to the interatrial septum.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this malignant tumor arising from the cardiac endothelium.",
    imageUrl: img("cvs-patho-035-angiosarcoma-heart.jpg"),
    options: [
      "Cardiac angiosarcoma",
      "Cardiac myxoma",
      "Rhabdomyoma",
      "Fibroma",
    ],
    answer: 0,
    explanation: "Angiosarcoma is the most common malignant primary cardiac tumor, usually in the right atrium.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this infiltrative cardiomyopathy with extracellular amyloid deposition.",
    imageUrl: img("cvs-patho-037-cardiac-amyloidosis.jpg"),
    options: [
      "Cardiac amyloidosis",
      "Cardiac sarcoidosis",
      "Hemochromatosis",
      "Endomyocardial fibrosis",
    ],
    answer: 0,
    explanation: "Cardiac amyloidosis shows extracellular deposition of misfolded proteins, causing restrictive physiology.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this granulomatous disease affecting the myocardium.",
    imageUrl: img("cvs-patho-038-cardiac-sarcoidosis.jpg"),
    options: [
      "Cardiac sarcoidosis",
      "Cardiac amyloidosis",
      "Rheumatic myocarditis",
      "Chagas disease",
    ],
    answer: 0,
    explanation: "Cardiac sarcoidosis shows non-caseating granulomas in the myocardium, potentially causing conduction defects.",
    difficulty: "hard",
  },
  {
    prompt: "What is the diagnosis? This metabolic disorder causes iron deposition in the myocardium.",
    imageUrl: img("cvs-patho-039-hemochromatosis-heart.jpg"),
    options: [
      "Hemochromatosis (iron overload)",
      "Wilson's disease",
      "Amyloidosis",
      "Sarcoidosis",
    ],
    answer: 0,
    explanation: "Hemochromatosis causes iron deposition in the heart, leading to dilated or restrictive cardiomyopathy.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of vasculitis affecting large vessels (e.g., aorta and its branches).",
    imageUrl: img("cvs-patho-041-arteritis-giant-cell.jpg"),
    options: [
      "Giant cell (temporal) arteritis",
      "Polyarteritis nodosa",
      "Kawasaki disease",
      "Granulomatosis with polyangiitis",
    ],
    answer: 0,
    explanation: "Giant cell arteritis affects large vessels, showing granulomatous inflammation with multinucleated giant cells.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this medium-vessel vasculitis showing transmural inflammation with fibrinoid necrosis.",
    imageUrl: img("cvs-patho-042-polyarteritis-nodosa.jpg"),
    options: [
      "Polyarteritis nodosa (PAN)",
      "Giant cell arteritis",
      "Kawasaki disease",
      "Microscopic polyangiitis",
    ],
    answer: 0,
    explanation: "PAN shows segmental transmural necrotizing inflammation of medium-sized arteries, often with aneurysm formation.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this vasculitis primarily affecting coronary arteries in children.",
    imageUrl: img("cvs-patho-043-Kawasaki-disease.jpg"),
    options: [
      "Kawasaki disease",
      "Polyarteritis nodosa",
      "Giant cell arteritis",
      "Henoch-Schönlein purpura",
    ],
    answer: 0,
    explanation: "Kawasaki disease is an acute vasculitis of childhood affecting coronary arteries, risking aneurysm formation.",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────────────────
  //  CLINICAL / ECG / IMAGING (5 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "Identify this ECG pattern: ST-segment elevation in leads II, III, aVF.",
    imageUrl: img("cvs-other-001-ecg-stemi.jpg"),
    options: [
      "Inferior STEMI (RCA occlusion)",
      "Anterior STEMI (LAD occlusion)",
      "Lateral STEMI (circumflex occlusion)",
      "Posterior MI",
    ],
    answer: 0,
    explanation: "ST elevation in II, III, aVF indicates inferior wall MI, usually due to RCA occlusion.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this arrhythmia: irregularly irregular rhythm with no P waves.",
    imageUrl: img("cvs-other-003-ecg-atrial-fibrillation.jpg"),
    options: [
      "Atrial fibrillation",
      "Atrial flutter",
      "Multifocal atrial tachycardia",
      "Sinus arrhythmia",
    ],
    answer: 0,
    explanation: "Atrial fibrillation shows an irregularly irregular rhythm with absent P waves and fibrillatory baseline.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this wide-complex tachycardia at rate >150 bpm.",
    imageUrl: img("cvs-other-004-ecg-ventricular-tachycardia.jpg"),
    options: [
      "Ventricular tachycardia (VT)",
      "SVT with aberrancy",
      "Atrial flutter with 2:1 block",
      "Sinus tachycardia",
    ],
    answer: 0,
    explanation: "VT shows wide QRS complexes (>120ms) at rate >100 bpm, originating from a ventricular focus.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this chest X-ray finding: enlarged cardiac silhouette with pulmonary congestion.",
    imageUrl: img("cvs-other-014-xray-cardiomegaly.jpg"),
    options: [
      "Cardiomegaly with pulmonary edema",
      "Pleural effusion",
      "Pneumothorax",
      "Normal chest X-ray",
    ],
    answer: 0,
    explanation: "Cardiomegaly (CTR >0.5) with pulmonary venous congestion suggests heart failure.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this echocardiographic finding: asymmetric thickening of the interventricular septum.",
    imageUrl: img("cvs-other-010-echo-hcm.jpg"),
    options: [
      "Hypertrophic cardiomyopathy (HCM)",
      "Dilated cardiomyopathy",
      "Athlete's heart",
      "Aortic stenosis with LVH",
    ],
    answer: 0,
    explanation: "Echocardiography showing asymmetric septal hypertrophy (septum:posterior wall ratio >1.3) is diagnostic of HCM.",
    difficulty: "medium",
  },
];
