import type { SeedQuestion } from "../seed-utils";

function img(file: string): string {
  return `/api/content/ospe/image?folder=IBL&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ── Immunology (10) ──
  {
    prompt: "Identify this cell type involved in the innate immune response that releases histamine and heparin.",
    imageUrl: img("ibl-001-mast-cell.jpg"),
    options: ["Mast cell", "Basophil", "Eosinophil", "Dendritic cell", "Natural killer cell"],
    answer: 0,
    explanation: "Mast cells reside in tissues and degranulate releasing histamine and heparin, key mediators of innate immunity and type I hypersensitivity.",
    difficulty: "easy",
  },
  {
    prompt: "A patient presents with urticaria and bronchospasm minutes after receiving IV antibiotics. Which hypersensitivity reaction type is this?",
    imageUrl: img("ibl-002-anaphylaxis.jpg"),
    options: ["Type I (Immediate)", "Type II (Cytotoxic)", "Type III (Immune complex)", "Type IV (Delayed)", "Type V (Stimulatory)"],
    answer: 0,
    explanation: "Immediate onset (minutes) with IgE-mediated mast cell degranulation is characteristic of Type I hypersensitivity (anaphylaxis).",
    difficulty: "easy",
  },
  {
    prompt: "Identify this antigen-presenting cell characterized by extensive dendritic processes and MHC II expression.",
    imageUrl: img("ibl-003-dendritic-cell.jpg"),
    options: ["Dendritic cell", "Macrophage", "B lymphocyte", "Follicular dendritic cell", "Langerhans cell"],
    answer: 0,
    explanation: "Dendritic cells are professional antigen-presenting cells with long cytoplasmic processes, bridging innate and adaptive immunity.",
    difficulty: "medium",
  },
  {
    prompt: "Which immunoglobulin is the first to rise during a primary immune response and is the most abundant in serum?",
    imageUrl: img("ibl-004-immunoglobulin.jpg"),
    options: ["IgG", "IgM", "IgA", "IgE", "IgD"],
    answer: 1,
    explanation: "IgM is the first antibody produced in a primary response and exists as a pentamer, giving it high avidity despite lower individual affinity.",
    difficulty: "easy",
  },
  {
    prompt: "A patient with SLE has a positive anti-dsDNA antibody and glomerulonephritis. Which hypersensitivity mechanism mediates this organ damage?",
    imageUrl: img("ibl-005-lupus-nephritis.jpg"),
    options: ["Type II cytotoxic", "Type I anaphylactic", "Type III immune complex", "Type IV delayed", "Type II antibody-dependent"],
    answer: 2,
    explanation: "SLE glomerulonephritis is caused by deposition of antigen-antibody (immune) complexes in the glomerular basement membrane, a Type III reaction.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this deficiency: a male infant presents with recurrent bacterial infections and absent thymic shadow on chest X-ray.",
    imageUrl: img("ibl-006-digeorge.jpg"),
    options: ["DiGeorge syndrome", "X-linked agammaglobulinemia", "Severe combined immunodeficiency", "Chronic granulomatous disease", "Wiskott-Aldrich syndrome"],
    answer: 0,
    explanation: "DiGeorge syndrome involves 22q11.2 deletion causing thymic hypoplasia, leading to T-cell deficiency and absent thymic shadow on imaging.",
    difficulty: "medium",
  },
  {
    prompt: "This graft-versus-host disease reaction primarily involves which immune cell attacking host tissues?",
    imageUrl: img("ibl-007-gvhd.jpg"),
    options: ["Donor T lymphocytes", "Donor B lymphocytes", "Recipient macrophages", "Donor NK cells", "Recipient neutrophils"],
    answer: 0,
    explanation: "GVHD occurs when donor T lymphocytes recognize host MHC antigens as foreign and mount an immune attack against host tissues.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this autoimmune condition: antibodies against the acetylcholine receptor at the neuromuscular junction causing muscle weakness.",
    imageUrl: img("ibl-008-myasthenia.jpg"),
    options: ["Myasthenia gravis", "Graves disease", "Type 1 diabetes mellitus", "Rheumatoid arthritis", "Hashimoto thyroiditis"],
    answer: 0,
    explanation: "Myasthenia gravis is a Type II autoimmune disease where anti-AChR antibodies block neuromuscular transmission causing fatigable weakness.",
    difficulty: "easy",
  },
  {
    prompt: "Which complement pathway is activated directly by antigen-antibody complexes without the need for C1q?",
    imageUrl: img("ibl-009-complement.jpg"),
    options: ["Lectin pathway", "Alternative pathway", "Classical pathway", "Membrane attack complex", "Properdin pathway"],
    answer: 1,
    explanation: "The alternative complement pathway is activated spontaneously by C3 hydrolysis on microbial surfaces and does not require antibodies or C1q.",
    difficulty: "hard",
  },
  {
    prompt: "A child presents with a history of severe eczema, thrombocytopenia, and recurrent infections. Which gene mutation is most likely?",
    imageUrl: img("ibl-010-wiskott-aldrich.jpg"),
    options: ["WAS gene (Xp11.22)", "BTK gene (Xq21.33)", "IL2RG gene (Xq13.1)", "CYBB gene (Xp21.1-p11.4)", "ADA gene (20q13.12)"],
    answer: 0,
    explanation: "Wiskott-Aldrich syndrome (WAS gene mutation) presents with the triad of eczema, thrombocytopenia (small platelets), and immunodeficiency.",
    difficulty: "hard",
  },

  // ── Hematology (10) ──
  {
    prompt: "Identify this blood cell: a large granular lymphocyte responsible for antibody-dependent cellular cytotoxicity.",
    imageUrl: img("ibl-011-nk-cell.jpg"),
    options: ["Natural killer cell", "Cytotoxic T lymphocyte", "Monocyte", "Large granular lymphocyte (T cell)", "Neutrophil"],
    answer: 0,
    explanation: "NK cells are large granular lymphocytes that perform ADCC and kill virus-infected or tumor cells without prior sensitization.",
    difficulty: "easy",
  },
  {
    prompt: "In a peripheral blood smear, which coagulation factor is the most abundant and has the shortest half-life?",
    imageUrl: img("ibl-012-coag-factor.jpg"),
    options: ["Factor V", "Factor VIII", "Fibrinogen (Factor I)", "Prothrombin (Factor II)", "Factor XII"],
    answer: 2,
    explanation: "Fibrinogen (Factor I) is the most abundant coagulation factor in plasma, essential for clot formation via conversion to fibrin.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this anemia: a blood smear shows microcytic hypochromic cells with target cells and basophilic stippling.",
    imageUrl: img("ibl-013-thalassemia.jpg"),
    options: ["Thalassemia major", "Iron deficiency anemia", "Sideroblastic anemia", "Anemia of chronic disease", "Lead poisoning"],
    answer: 0,
    explanation: "Thalassemia major shows microcytic hypochromic cells, target cells, and basophilic stippling due to ineffective erythropoiesis and excess alpha chains.",
    difficulty: "medium",
  },
  {
    prompt: "A patient on warfarin has an elevated PT/INR but normal aPTT. Which coagulation pathway does warfarin primarily affect?",
    imageUrl: img("ibl-014-warfarin.jpg"),
    options: ["Extrinsic pathway", "Intrinsic pathway", "Common pathway", "Fibrinolytic pathway", "Platelet aggregation pathway"],
    answer: 0,
    explanation: "Warfarin inhibits vitamin K-dependent factors (II, VII, IX, X) but primarily affects Factor VII (extrinsic pathway), causing prolonged PT.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this condition: a blood smear shows sickle-shaped red blood cells, and the patient has chronic hemolytic anemia with vaso-occlusive crises.",
    imageUrl: img("ibl-015-sickle-cell.jpg"),
    options: ["Sickle cell disease", "Thalassemia intermedia", "Hereditary spherocytosis", "G6PD deficiency", "Hemoglobin C disease"],
    answer: 0,
    explanation: "Sickle cell disease (HbS) causes sickling of RBCs under hypoxia, leading to hemolytic anemia and painful vaso-occlusive crises.",
    difficulty: "easy",
  },
  {
    prompt: "A blood smear shows hypersegmented neutrophils (>5 lobes) and macro-ovalocytes. Which deficiency is most likely?",
    imageUrl: img("ibl-016-megaloblastic.jpg"),
    options: ["Vitamin B12 deficiency", "Iron deficiency", "Folate deficiency", "Both B12 and folate deficiency", "Copper deficiency"],
    answer: 3,
    explanation: "Megaloblastic anemia with hypersegmented neutrophils and macro-ovalocytes is caused by impaired DNA synthesis from either B12 or folate deficiency.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this leukemia: a blood smear shows >20% blast cells with Auer rods and myeloperoxidase positivity.",
    imageUrl: img("ibl-017-aml.jpg"),
    options: ["Acute myeloid leukemia (AML)", "Acute lymphoblastic leukemia (ALL)", "Chronic myeloid leukemia (CML)", "Hairy cell leukemia", "Myelodysplastic syndrome"],
    answer: 0,
    explanation: "AML is characterized by myeloblasts with Auer rods (crystallized granules) and myeloperoxidase positivity, distinguishing it from ALL.",
    difficulty: "easy",
  },
  {
    prompt: "This blood bank test is performed to detect unexpected antibodies in a patient's serum before transfusion. Name this test.",
    imageUrl: img("ibl-018-indirect-coombs.jpg"),
    options: ["Indirect antiglobulin test (IAT)", "Direct antiglobulin test (DAT)", "Crossmatch", "Antibody screen", "Elution test"],
    answer: 3,
    explanation: "The antibody screen (indirect Coombs) uses reagent red cells to detect unexpected antibodies in patient serum before transfusion.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this coagulation disorder: a patient with prolonged aPTT but normal PT, corrected by mixing study, and not corrected by adding Bethesda units.",
    imageUrl: img("ibl-019-hemophilia.jpg"),
    options: ["Hemophilia A (Factor VIII deficiency)", "Hemophilia B (Factor IX deficiency)", "Von Willebrand disease", "Factor XI deficiency", "Lupus anticoagulant"],
    answer: 0,
    explanation: "Prolonged aPTT with normal PT that corrects on mixing study indicates a factor deficiency. Factor VIII deficiency is Hemophilia A.",
    difficulty: "hard",
  },
  {
    prompt: "A patient with ITP has petechiae, purpura, and isolated thrombocytopenia. Which antibody is typically responsible?",
    imageUrl: img("ibl-020-itr.jpg"),
    options: ["Anti-platelet glycoprotein IIb/IIIa IgG", "Anti-red blood cell IgG", "Anti-neutrophil IgG", "Anti-phospholipid IgG", "Anti-basement membrane IgG"],
    answer: 0,
    explanation: "Immune thrombocytopenic purpura involves IgG autoantibodies against platelet surface glycoproteins (especially IIb/IIIa), causing platelet destruction.",
    difficulty: "medium",
  },

  // ── Lymphatic System (10) ──
  {
    prompt: "Identify this lymph node region: the outer zone containing B cells organized into follicles with germinal centers.",
    imageUrl: img("ibl-021-cortex.jpg"),
    options: ["Cortex", "Paracortex", "Medulla", "Subcapsular sinus", "Medullary sinus"],
    answer: 0,
    explanation: "The cortex of the lymph node contains B-cell follicles (primary and secondary) organized into germinal centers for B cell proliferation.",
    difficulty: "easy",
  },
  {
    prompt: "This lymphoid organ is the primary site of T-cell maturation and contains epithelial reticular cells forming a blood-thymus barrier.",
    imageUrl: img("ibl-022-thymus.jpg"),
    options: ["Thymus", "Spleen", "Bone marrow", "Tonsil", "Peyer's patch"],
    answer: 0,
    explanation: "The thymus is a primary lymphoid organ where T cells undergo maturation, positive selection (cortex), and negative selection (medulla).",
    difficulty: "easy",
  },
  {
    prompt: "Identify this splenic region: the white pulp surrounding the central arteriole containing T cells in the periarteriolar lymphoid sheath.",
    imageUrl: img("ibl-023-pals.jpg"),
    options: ["Periarteriolar lymphoid sheath (PALS)", "Splenic cord of Billroth", "Red pulp", "Marginal zone", "Follicle-associated epithelium"],
    answer: 0,
    explanation: "The PALS is the T-cell zone of the spleen surrounding the central arteriole in the white pulp, analogous to the paracortex of lymph nodes.",
    difficulty: "medium",
  },
  {
    prompt: "Which adhesion molecule on lymphocytes mediates high endothelial venule (HEV) binding for lymph node homing?",
    imageUrl: img("ibl-024-selectin.jpg"),
    options: ["L-selectin (CD62L)", "E-selectin", "P-selectin", "ICAM-1", "VCAM-1"],
    answer: 0,
    explanation: "L-selectin (CD62L) on lymphocytes binds PNAd on high endothelial venules, mediating the initial rolling step of lymphocyte extravasation into lymph nodes.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this cell type found in lymph node paracortex: a professional antigen-presenting cell with abundant MHC II, responsible for activating naive T cells.",
    imageUrl: img("ibl-025-dc-paracortex.jpg"),
    options: ["Interdigitating dendritic cell", "Follicular dendritic cell", "Macrophage", "B cell", "NK cell"],
    answer: 0,
    explanation: "Interdigitating dendritic cells in the paracortex present antigen on MHC II to naive T cells, initiating adaptive immune responses.",
    difficulty: "medium",
  },
  {
    prompt: "A lymph node biopsy shows effacement of architecture with Reed-Sternberg cells (owl-eye appearance). What is the diagnosis?",
    imageUrl: img("ibl-026-hodgkin.jpg"),
    options: ["Hodgkin lymphoma", "Diffuse large B-cell lymphoma", "Follicular lymphoma", "Chronic lymphocytic leukemia", "Burkitt lymphoma"],
    answer: 0,
    explanation: "Reed-Sternberg cells (binucleate, owl-eye) with CD15+ and CD30+ are pathognomonic of classical Hodgkin lymphoma.",
    difficulty: "easy",
  },
  {
    prompt: "Which lymphocyte subset primarily resides in the intestinal lamina propria and is identified by the integrin α4β7 and chemokine receptor CCR9?",
    imageUrl: img("ibl-027-gut-homing.jpg"),
    options: ["Gut-homing T cells", "Memory B cells", "Natural killer T cells", "Regulatory T cells", "γδ T cells"],
    answer: 0,
    explanation: "Gut-homing T cells express α4β7 integrin (binds MAdCAM-1) and CCR9 (binds CCL25), directing them to the intestinal mucosa.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this structure: a collection of lymphoid tissue at the entrance of the pharynx, forming part of MALT (mucosa-associated lymphoid tissue).",
    imageUrl: img("ibl-028-palatine-tonsil.jpg"),
    options: ["Palatine tonsil", "Thymus", "Spleen", "Lymph node", "Appendix"],
    answer: 0,
    explanation: "Palatine tonsils are part of Waldeyer's ring of MALT at the pharyngeal entrance, with a deep tonsillar crypt lined by stratified squamous epithelium.",
    difficulty: "easy",
  },
  {
    prompt: "Which chemokine receptor is expressed on effector memory T cells and directs them to sites of peripheral tissue inflammation?",
    imageUrl: img("ibl-029-chemokine.jpg"),
    options: ["CXCR3", "CCR7", "CXCR4", "CXCR5", "CCR6"],
    answer: 0,
    explanation: "CXCR3 is expressed on Th1 effector memory T cells and binds CXCL9/10/11 at sites of inflammation, directing tissue-homing of effector cells.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this condition: massive splenomegaly with infiltration by lipid-laden macrophages (Gaucher cells) in a patient with hepatosplenomegaly and bone pain.",
    imageUrl: img("ibl-030-gaucher.jpg"),
    options: ["Gaucher disease", "Niemann-Pick disease", "Tangier disease", "Wolman disease", "Hunter syndrome"],
    answer: 0,
    explanation: "Gaucher disease (glucocerebrosidase deficiency) causes accumulation of glucocerebroside in macrophages (Gaucher cells), leading to massive hepatosplenomegaly.",
    difficulty: "medium",
  },
];
