import type { SeedQuestion } from "../seed-utils";

function img(file: string): string {
  return `/api/content/ospe/image?folder=MT&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ── Word Roots, Prefixes, and Suffixes (10) ──
  {
    prompt: "What does the prefix 'dys-' mean in medical terminology?",
    imageUrl: img("mt-104-001-dys-prefix.jpg"),
    options: ["Normal", "Painful or difficult", "Excessive", "Absence of", "Before"],
    answer: 1,
    explanation: "The prefix 'dys-' means painful, difficult, or abnormal (e.g., dyspnea, dysphagia).",
    difficulty: "easy",
  },
  {
    prompt: "Break down the medical term 'gastroenteritis'. Which word parts are present?",
    imageUrl: img("mt-104-002-gastroenteritis.jpg"),
    options: ["gastro + enter + itis", "gastro + enter + ostomy", "gast + enter + itis", "gastro + entero + plasty", "gastro + enter + pathy"],
    answer: 0,
    explanation: "'Gastro-' (stomach) + 'enter-' (intestines) + '-itis' (inflammation) = inflammation of the stomach and intestines.",
    difficulty: "easy",
  },
  {
    prompt: "Which suffix means 'surgical creation of an opening'?",
    imageUrl: img("mt-104-003-suffix-opening.jpg"),
    options: ["-ectomy", "-ostomy", "-otomy", "-plasty", "-rrhaphy"],
    answer: 1,
    explanation: "'-ostomy' means the surgical creation of an opening (stoma), e.g., colostomy. '-otomy' means surgical incision.",
    difficulty: "medium",
  },
  {
    prompt: "What is the meaning of the root word 'hepat/o'?",
    imageUrl: img("mt-104-004-hepato-root.jpg"),
    options: ["Kidney", "Liver", "Heart", "Spleen", "Pancreas"],
    answer: 1,
    explanation: "'Hepat/o' refers to the liver, as seen in hepatitis (inflammation of the liver) and hepatomegaly (enlarged liver).",
    difficulty: "easy",
  },
  {
    prompt: "The prefix 'tachy-' is combined with '-cardia' to form a medical term. What does 'tachycardia' mean?",
    imageUrl: img("mt-104-005-tachycardia.jpg"),
    options: ["Slow heart rate", "Fast heart rate", "Irregular heart rhythm", "Heart failure", "Chest pain"],
    answer: 1,
    explanation: "'Tachy-' (fast) + '-cardia' (heart) = abnormally fast heart rate, typically >100 bpm.",
    difficulty: "easy",
  },
  {
    prompt: "Which prefix means 'under, below, or deficient'?",
    imageUrl: img("mt-104-006-hypo-prefix.jpg"),
    options: ["Hyper-", "Hypo-", "Sub-", "In-", "Peri-"],
    answer: 1,
    explanation: "'Hypo-' means under, below, or deficient (e.g., hypoglycemia = low blood sugar). 'Sub-' is also used but 'hypo-' is the primary medical prefix for this meaning.",
    difficulty: "medium",
  },
  {
    prompt: "What does the suffix '-plasty' indicate?",
    imageUrl: img("mt-104-007-plasty-suffix.jpg"),
    options: ["Surgical repair or reconstruction", "Removal of", "Surgical incision into", "Prolapse of", "Inflammation of"],
    answer: 0,
    explanation: "'-plasty' means surgical repair or reconstruction, as in rhinoplasty (surgical repair of the nose).",
    difficulty: "medium",
  },
  {
    prompt: "The term 'polyuria' combines a prefix and a suffix. What does it mean?",
    imageUrl: img("mt-104-008-polyuria.jpg"),
    options: ["Painful urination", "Excessive urination", "Blood in urine", "Inability to urinate", "Cloudy urine"],
    answer: 1,
    explanation: "'Poly-' (many/excessive) + '-uria' (urine) = excessive production of urine.",
    difficulty: "medium",
  },
  {
    prompt: "What is the root word meaning in the term 'cholecystectomy'?",
    imageUrl: img("mt-104-009-cholecystectomy.jpg"),
    options: ["Removal of the gallbladder", "Removal of the colon", "Removal of the appendix", "Removal of the bile duct", "Removal of the stomach"],
    answer: 0,
    explanation: "'Cholecyst/o' (gallbladder) + '-ectomy' (removal) = surgical removal of the gallbladder.",
    difficulty: "medium",
  },
  {
    prompt: "Which prefix means 'new'?",
    imageUrl: img("mt-104-010-neo-prefix.jpg"),
    options: ["Neo-", "Paleo-", "Proto-", "Archaeo-", "Ceno-"],
    answer: 0,
    explanation: "'Neo-' means new, as in neoplasm (new, abnormal growth) and neonatal (relating to newborn).",
    difficulty: "easy",
  },

  // ── Body System Terminology: Anatomical Terms, Directional Terms, Planes (10) ──
  {
    prompt: "What is the anatomical term for the front of the body?",
    imageUrl: img("mt-104-011-anterior.jpg"),
    options: ["Posterior", "Anterior", "Dorsal", "Proximal", "Lateral"],
    answer: 1,
    explanation: "'Anterior' (also called 'ventral') refers to the front of the body. 'Posterior' (or 'dorsal') refers to the back.",
    difficulty: "easy",
  },
  {
    prompt: "Which anatomical plane divides the body into superior and inferior parts?",
    imageUrl: img("mt-104-012-planes.jpg"),
    options: ["Sagittal plane", "Coronal (frontal) plane", "Transverse (horizontal) plane", "Midsagittal plane", "Oblique plane"],
    answer: 2,
    explanation: "The transverse (horizontal) plane divides the body into superior (upper) and inferior (lower) portions.",
    difficulty: "medium",
  },
  {
    prompt: "In anatomical terminology, what does 'distal' mean?",
    imageUrl: img("mt-104-013-distal.jpg"),
    options: ["Closer to the point of attachment", "Farther from the point of attachment", "Toward the midline", "Away from the midline", "On the side of"],
    answer: 1,
    explanation: "'Distal' means farther from the point of attachment or origin. 'Proximal' means closer to the point of attachment.",
    difficulty: "easy",
  },
  {
    prompt: "What does the term 'supine' refer to?",
    imageUrl: img("mt-104-014-supine.jpg"),
    options: ["Face down", "Face up", "On the left side", "Standing upright", "On the right side"],
    answer: 1,
    explanation: "'Supine' means lying face up (back down). 'Prone' means lying face down (front down).",
    difficulty: "easy",
  },
  {
    prompt: "Which term describes a structure located toward the head end of the body?",
    imageUrl: img("mt-104-015-superior.jpg"),
    options: ["Inferior", "Superior", "Medial", "Lateral", "Deep"],
    answer: 1,
    explanation: "'Superior' means toward the head or upper part of a structure. 'Inferior' means toward the feet or lower part.",
    difficulty: "easy",
  },
  {
    prompt: "The sagittal plane divides the body into which two parts?",
    imageUrl: img("mt-104-016-sagittal.jpg"),
    options: ["Superior and inferior", "Anterior and posterior", "Right and left", "Medial and lateral", "Proximal and distal"],
    answer: 2,
    explanation: "The sagittal plane divides the body into right and left portions. The midsagittal (median) plane divides into equal halves.",
    difficulty: "medium",
  },
  {
    prompt: "What is the medical term for the inner aspect of the body (closer to the midline)?",
    imageUrl: img("mt-104-017-medial.jpg"),
    options: ["Lateral", "Medial", "Superficial", "Deep", "Distal"],
    answer: 1,
    explanation: "'Medial' means toward the midline of the body. 'Lateral' means away from the midline, toward the side.",
    difficulty: "easy",
  },
  {
    prompt: "What does the anatomical term 'contralateral' mean?",
    imageUrl: img("mt-104-018-contralateral.jpg"),
    options: ["On the same side", "On the opposite side", "In the middle", "Toward the head", "Away from the surface"],
    answer: 1,
    explanation: "'Contralateral' means on the opposite side. 'Ipsilateral' means on the same side.",
    difficulty: "medium",
  },
  {
    prompt: "Which term describes the outer layer of the body surface?",
    imageUrl: img("mt-104-019-superficial.jpg"),
    options: ["Deep", "Superficial", "Visceral", "Parietal", "Medial"],
    answer: 1,
    explanation: "'Superficial' means on or near the surface of the body. 'Deep' means farther from the surface, toward the interior.",
    difficulty: "easy",
  },
  {
    prompt: "What is the medical term for lying face down?",
    imageUrl: img("mt-104-020-prone.jpg"),
    options: ["Supine", "Prone", "Lateral recumbent", "Sims' position", "Trendelenburg"],
    answer: 1,
    explanation: "'Prone' position means lying face down. This contrasts with 'supine' (face up).",
    difficulty: "easy",
  },

  // ── Clinical Terminology: Diagnoses, Procedures, Abbreviations, Eponyms (10) ──
  {
    prompt: "What does the abbreviation 'BID' mean in a medical prescription?",
    imageUrl: img("mt-104-021-bid.jpg"),
    options: ["Once daily", "Twice daily", "Three times daily", "Four times daily", "At bedtime"],
    answer: 1,
    explanation: "'BID' (bis in die) means twice daily. 'QD' means once daily, 'TID' means three times daily.",
    difficulty: "easy",
  },
  {
    prompt: "What is the medical term for the surgical removal of the appendix?",
    imageUrl: img("mt-104-022-appendectomy.jpg"),
    options: ["Appendicitis", "Appendectomy", "Appendicostomy", "Appendoplasty", "Appendorrhaphy"],
    answer: 1,
    explanation: "'Appendectomy' is the surgical removal of the appendix. 'Appendicitis' is inflammation of the appendix.",
    difficulty: "easy",
  },
  {
    prompt: "Which eponym refers to the 'deep tendon reflex' test performed with a reflex hammer?",
    imageUrl: img("mt-104-023-deep-tendon.jpg"),
    options: ["Barthel index", "Babinski sign", "Romberg test", "Brudzinski sign", "Kernig sign"],
    answer: 1,
    explanation: "The Babinski sign is an extensor plantar response indicating upper motor neuron lesions. It tests the deep tendon reflex pathway.",
    difficulty: "hard",
  },
  {
    prompt: "What does 'NPO' stand for in medical orders?",
    imageUrl: img("mt-104-024-npo.jpg"),
    options: ["No problems observed", "Nothing by mouth", "Normal pulse oximetry", "Notify physician on duty", "No previous operations"],
    answer: 1,
    explanation: "'NPO' (nil per os) means nothing by mouth. It is used when a patient must fast before surgery or procedures.",
    difficulty: "easy",
  },
  {
    prompt: "What is the meaning of the clinical term 'myocardial infarction'?",
    imageUrl: img("mt-104-025-mi.jpg"),
    options: ["Heart valve disorder", "Heart muscle death due to blocked blood supply", "Heart infection", "Irregular heartbeat", "Heart failure"],
    answer: 1,
    explanation: "'Myocardial' (heart muscle) + 'infarction' (tissue death from loss of blood supply) = commonly known as a heart attack.",
    difficulty: "medium",
  },
  {
    prompt: "What does the abbreviation 'PRN' mean in medical documentation?",
    imageUrl: img("mt-104-026-prn.jpg"),
    options: ["Before meals", "As needed", "After meals", "At night", "By mouth"],
    answer: 1,
    explanation: "'PRN' (pro re nata) means 'as needed' or 'when the situation arises.' It is used for medications given on request.",
    difficulty: "easy",
  },
  {
    prompt: "Which procedure involves the visual examination of the interior of the colon?",
    imageUrl: img("mt-104-027-colonoscopy.jpg"),
    options: ["Laparoscopy", "Colonoscopy", "Bronchoscopy", "Cystoscopy", "Arthroscopy"],
    answer: 1,
    explanation: "'Colonoscopy' is the visual examination of the colon using a flexible endoscope. The suffix '-scopy' means visual examination.",
    difficulty: "easy",
  },
  {
    prompt: "What does the medical abbreviation 'STAT' indicate?",
    imageUrl: img("mt-104-028-stat.jpg"),
    options: ["Patient is stable", "Immediately, right now", "Statistics", "Status unchanged", "Scheduled time"],
    answer: 1,
    explanation: "'STAT' (from Latin 'statim') means immediately. It is used to order urgent tests or medications.",
    difficulty: "easy",
  },
  {
    prompt: "What is the medical term for the surgical creation of a passage between the stomach and the abdominal wall for feeding?",
    imageUrl: img("mt-104-029-gastrostomy.jpg"),
    options: ["Gastroscopy", "Gastroplasty", "Gastrostomy", "Gastrectomy", "Gastroenterostomy"],
    answer: 2,
    explanation: "'Gastrostomy' is the surgical creation of an opening into the stomach, typically for enteral feeding (e.g., PEG tube).",
    difficulty: "medium",
  },
  {
    prompt: "Which of the following is an eponym for the grading scale used to assess the severity of muscle spasticity?",
    imageUrl: img("mt-104-030-ashworth.jpg"),
    options: ["Glasgow Coma Scale", "Ashworth Scale", "APGAR Score", "Barthel Index", "Karnofsky Scale"],
    answer: 1,
    explanation: "The Ashworth Scale (Modified Ashworth Scale) is used to grade the severity of spasticity in muscles on a 0–4 scale.",
    difficulty: "hard",
  },
];
