import type { SeedQuestion } from "../seed-utils";

function img(file: string): string {
  return `/api/content/ospe/image?folder=PMB&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ── Pathology (10) ──────────────────────────────────────────────────────
  {
    prompt: "Identify the type of inflammation shown in this tissue section, characterised by neutrophil infiltration and tissue oedema.",
    imageUrl: img("pmb-001-acute-inflammation.jpg"),
    options: [
      "Chronic inflammation",
      "Acute inflammation",
      "Granulomatous inflammation",
      "Allergic inflammation",
      "Suppurative inflammation",
    ],
    answer: 1,
    explanation: "Neutrophil predominance and oedema are hallmarks of acute inflammation.",
    difficulty: "easy",
  },
  {
    prompt: "What pathological process is depicted in this image showing uncontrolled cell proliferation with nuclear pleomorphism and increased mitotic figures?",
    imageUrl: img("pmb-002-neoplasia.jpg"),
    options: [
      "Hyperplasia",
      "Metaplasia",
      "Neoplasia",
      "Dysplasia",
      "Anaplasia",
    ],
    answer: 2,
    explanation: "Uncontrolled proliferation with nuclear atypia defines neoplasia.",
    difficulty: "medium",
  },
  {
    prompt: "Identify the type of cell injury demonstrated by the presence of hyaline droplets within renal tubular epithelial cells.",
    imageUrl: img("pmb-003-reversible-cell-injury.jpg"),
    options: [
      "Necrosis",
      "Apoptosis",
      "Reversible cell injury",
      "Gangrenous necrosis",
      "Fatty change",
    ],
    answer: 2,
    explanation: "Hyaline droplet change is a morphological feature of reversible cell injury.",
    difficulty: "easy",
  },
  {
    prompt: "What mode of cell death is shown in this section, featuring cell shrinkage, chromatin condensation and formation of apoptotic bodies?",
    imageUrl: img("pmb-004-apoptosis.jpg"),
    options: [
      "Necrosis",
      "Autolysis",
      "Apoptosis",
      "Coagulative necrosis",
      "Liquefactive necrosis",
    ],
    answer: 2,
    explanation: "Shrunken cells with condensed chromatin and apoptotic bodies indicate apoptosis.",
    difficulty: "easy",
  },
  {
    prompt: "Name the process illustrated here, in which fibroblasts deposit collagen to restore tissue architecture following injury.",
    imageUrl: img("pmb-005-tissue-repair.jpg"),
    options: [
      "Regeneration",
      "Wound healing by granulation tissue",
      "Fibrosis",
      "Angiogenesis",
      "Re-epithelialisation",
    ],
    answer: 1,
    explanation: "Granulation tissue with fibroblast proliferation and new vessel formation characterises wound healing.",
    difficulty: "medium",
  },
  {
    prompt: "Identify the type of necrosis shown in this infarcted tissue where the structural outline of dead cells is preserved.",
    imageUrl: img("pmb-006-coagulative-necrosis.jpg"),
    options: [
      "Liquefactive necrosis",
      "Coagulative necrosis",
      "Caseous necrosis",
      "Fat necrosis",
      "Fibrinoid necrosis",
    ],
    answer: 1,
    explanation: "Coagulative necrosis retains the basic architecture of dead tissue; it is the most common form of necrosis.",
    difficulty: "easy",
  },
  {
    prompt: "What haemodynamic disorder is indicated by the presence of post-mortem blood clotting as seen in this vessel?",
    imageUrl: img("pmb-007-post-mortem-clot.jpg"),
    options: [
      "Ante-mortem thrombus",
      "Post-mortem clot",
      "Embolus",
      "Infarction",
      "Thromboembolism",
    ],
    answer: 1,
    explanation: "Post-mortem clots are gelatinous and lack attachment to vessel walls, unlike ante-mortem thrombi.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the organism or structure indicated by the arrow in this histopathology slide of caseous necrosis within a granuloma.",
    imageUrl: img("pmb-008-granuloma-caseous.jpg"),
    options: [
      "Foreign body",
      "Mycobacterium tuberculosis",
      "Fungal spore",
      "Calcified debris",
      "Suture material",
    ],
    answer: 1,
    explanation: "Caseating granulomas are highly suggestive of tuberculosis caused by Mycobacterium tuberculosis.",
    difficulty: "medium",
  },
  {
    prompt: "What form of oedema is depicted in this section of lung tissue showing fluid-filled alveolar spaces?",
    imageUrl: img("pmb-009-pulmonary-oedema.jpg"),
    options: [
      "Cerebral oedema",
      "Angioneurotic oedema",
      "Pulmonary oedema",
      "Lymphoedema",
      "Hydrothorax",
    ],
    answer: 2,
    explanation: "Intra-alveolar fluid accumulation is characteristic of pulmonary oedema.",
    difficulty: "easy",
  },
  {
    prompt: "Name the pathological feature shown: a well-circumscribed, encapsulated mass composed of mature adipocytes.",
    imageUrl: img("pmb-010-lipoma.jpg"),
    options: [
      "Lipoma",
      "Liposarcoma",
      "Lipoma",
      "Angiomyolipoma",
      "Hibernoma",
    ],
    answer: 0,
    explanation: "A benign tumour of mature fat cells is a lipoma.",
    difficulty: "easy",
  },

  // ── Microbiology (10) ───────────────────────────────────────────────────
  {
    prompt: "Identify the staining method used in this slide that differentiates acid-fast bacilli (red) from background tissue (blue).",
    imageUrl: img("pmb-011-ziehl-neelsen.jpg"),
    options: [
      "Gram stain",
      "Ziehl-Neelsen stain",
      "Wright stain",
      "Giemsa stain",
      "India ink stain",
    ],
    answer: 1,
    explanation: "The Ziehl-Neelsen (acid-fast) stain is used to identify Mycobacterium species.",
    difficulty: "easy",
  },
  {
    prompt: "What culture medium is shown in this plate, which selects for Gram-negative bacteria by inhibiting Gram-positive organisms?",
    imageUrl: img("pmb-012-macconkey-agar.jpg"),
    options: [
      "Blood agar",
      "MacConkey agar",
      "Sabouraud dextrose agar",
      "Lowenstein-Jensen medium",
      "Chocolate agar",
    ],
    answer: 1,
    explanation: "MacConkey agar is a selective and differential medium for Gram-negative enteric bacilli.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the bacterial morphology shown in this Gram-stained smear: purple, spherical organisms arranged in grape-like clusters.",
    imageUrl: img("pmb-013-staphylococcus.jpg"),
    options: [
      "Streptococcus (chains)",
      "Staphylococcus (clusters)",
      "Diplococci",
      "Bacilli",
      "Spirilla",
    ],
    answer: 1,
    explanation: "Gram-positive cocci in grape-like clusters are characteristic of Staphylococcus species.",
    difficulty: "easy",
  },
  {
    prompt: "What type of viral structure is depicted in this electron micrograph, showing a capsid without an envelope?",
    imageUrl: img("pmb-014-naked-virus.jpg"),
    options: [
      "Enveloped virus",
      "Naked (non-enveloped) virus",
      "Bacteriophage",
      "Viroid",
      "Prion",
    ],
    answer: 1,
    explanation: "A virus particle consisting only of nucleocapsid without a lipid envelope is a naked virus.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the organism shown in this blood film preparation stained with Giemsa, featuring ring-form trophozoites within red blood cells.",
    imageUrl: img("pmb-015-malaria-ring-form.jpg"),
    options: [
      "Plasmodium falciparum",
      "Trypanosoma cruzi",
      "Leishmania donovani",
      "Entamoeba histolytica",
      "Giardia lamblia",
    ],
    answer: 0,
    explanation: "Intraerythrocytic ring-form trophozoites are diagnostic of Plasmodium infection (malaria).",
    difficulty: "medium",
  },
  {
    prompt: "What capsule stain technique is used here to demonstrate the polysaccharide capsule surrounding Cryptococcus neoformans in cerebrospinal fluid?",
    imageUrl: img("pmb-016-india-ink.jpg"),
    options: [
      "Gram stain",
      "India ink preparation",
      "Acridine orange stain",
      "Albert stain",
      "Papanicolaou stain",
    ],
    answer: 1,
    explanation: "India ink negatively stains the capsule of Cryptococcus neoformans, leaving a clear halo.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the organism seen in this stool microscopy slide as oval, thick-walled cysts with four nuclei.",
    imageUrl: img("pmb-017-entamoeba-cyst.jpg"),
    options: [
      "Giardia lamblia cyst",
      "Entamoeba histolytica cyst",
      "Cryptosporidium oocyst",
      "Cyclospora cayetanensis",
      "Balantidium coli cyst",
    ],
    answer: 1,
    explanation: "Mature cysts of Entamoeba histolytica with four nuclei are diagnostic in stool examination.",
    difficulty: "medium",
  },
  {
    prompt: "What differential stain is illustrated here, used to classify bacteria into Gram-positive (purple) and Gram-negative (pink) groups?",
    imageUrl: img("pmb-018-gram-stain.jpg"),
    options: [
      "Acid-fast stain",
      "Gram stain",
      "Endospore stain",
      "Capsule stain",
      "Flagella stain",
    ],
    answer: 1,
    explanation: "The Gram stain is the most fundamental and widely used differential stain in bacteriology.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the laboratory test shown: a clear zone of inhibition around antibiotic discs on an agar plate used to determine antimicrobial susceptibility.",
    imageUrl: img("pmb-019-antibiogram.jpg"),
    options: [
      "Minimum inhibitory concentration (MIC)",
      "Kirby-Bauer disc diffusion test",
      "Agglutination test",
      "ELISA",
      "Western blot",
    ],
    answer: 1,
    explanation: "The Kirby-Bauer method measures zones of inhibition to determine antibiotic sensitivity.",
    difficulty: "medium",
  },
  {
    prompt: "What structure is visible in this electron micrograph of a bacterial cell: a rigid, protective outer layer external to the cell wall?",
    imageUrl: img("pmb-020-bacterial-capsule.jpg"),
    options: [
      "Flagellum",
      "Pili (fimbriae)",
      "Capsule",
      "Plasma membrane",
      "Nucleoid",
    ],
    answer: 2,
    explanation: "The polysaccharide capsule is an important virulence factor that protects bacteria from phagocytosis.",
    difficulty: "easy",
  },

  // ── Biochemistry (10) ───────────────────────────────────────────────────
  {
    prompt: "What enzyme is deficient in this metabolic disorder characterised by accumulation of phenylalanine, detected by newborn screening?",
    imageUrl: img("pmb-021-pku.jpg"),
    options: [
      "Tyrosine hydroxylase",
      "Phenylalanine hydroxylase",
      "Tryptophan hydroxylase",
      "Homogentisate oxidase",
      "Fumarylacetoacetate hydrolase",
    ],
    answer: 1,
    explanation: "Phenylketonuria (PKU) is caused by deficiency of phenylalanine hydroxylase.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the metabolic pathway primarily responsible for this serum analyte used to assess liver synthetic function and nutritional status.",
    imageUrl: img("pmb-022-albumin-liver.jpg"),
    options: [
      "Proteasome degradation pathway",
      "Hepatic albumin synthesis",
      "Urea cycle",
      "Gluconeogenesis",
      "Beta-oxidation of fatty acids",
    ],
    answer: 1,
    explanation: "Serum albumin is synthesised exclusively by the liver and reflects its synthetic capacity.",
    difficulty: "easy",
  },
  {
    prompt: "What molecular diagnostic technique is depicted here, used to amplify specific DNA sequences for diagnostic and research purposes?",
    imageUrl: img("pmb-023-pcr.jpg"),
    options: [
      "Southern blotting",
      "Polymerase chain reaction (PCR)",
      "Northern blotting",
      "ELISA",
      "Chromatography",
    ],
    answer: 1,
    explanation: "PCR amplifies targeted DNA sequences and is fundamental to molecular diagnostics.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the enzyme elevated in this serum sample, which is a specific marker for acute myocardial infarction when measured alongside troponin.",
    imageUrl: img("pmb-024-cpk-mb.jpg"),
    options: [
      "Alanine aminotransferase (ALT)",
      "Creatine kinase-MB (CK-MB)",
      "Alkaline phosphatase (ALP)",
      "Gamma-glutamyl transferase (GGT)",
      "Lactate dehydrogenase (LDH)",
    ],
    answer: 1,
    explanation: "CK-MB is a cardiac-specific isoenzyme elevated in acute myocardial infarction.",
    difficulty: "medium",
  },
  {
    prompt: "What metabolic pathway is impaired in this disorder, leading to the accumulation of uric acid and recurrent joint inflammation?",
    imageUrl: img("pmb-025-gout.jpg"),
    options: [
      "Purine catabolism (degradation)",
      "Pyrimidine synthesis",
      "Glycolysis",
      "Fatty acid synthesis",
      "Urea cycle",
    ],
    answer: 0,
    explanation: "Gout results from overproduction or under-excretion of uric acid from purine degradation.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the carbohydrate metabolism test shown: a glucose tolerance curve indicating impaired glucose handling without meeting diabetic thresholds.",
    imageUrl: img("pmb-026-ogtt.jpg"),
    options: [
      "Normal glucose tolerance",
      "Impaired glucose tolerance",
      "Diabetes mellitus",
      "Reactive hypoglycaemia",
      "Insulinoma",
    ],
    answer: 1,
    explanation: "Impaired glucose tolerance is diagnosed when 2-hour OGTT values fall between diabetic and normal ranges.",
    difficulty: "medium",
  },
  {
    prompt: "What blood gas parameter is primarily responsible for the acid-base disturbance illustrated in this patient with chronic obstructive pulmonary disease?",
    imageUrl: img("pmb-027-respiratory-acidosis.jpg"),
    options: [
      "Metabolic acidosis",
      "Respiratory acidosis",
      "Metabolic alkalosis",
      "Respiratory alkalosis",
      "Mixed acid-base disorder",
    ],
    answer: 1,
    explanation: "CO2 retention in COPD leads to respiratory acidosis with elevated pCO2 and decreased pH.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the lipid abnormality characterised by elevated low-density lipoprotein (LDL) cholesterol, a major risk factor for atherosclerosis.",
    imageUrl: img("pmb-028-ldl-cholesterol.jpg"),
    options: [
      "Hypertriglyceridaemia",
      "Hypercholesterolaemia (elevated LDL)",
      "Low HDL cholesterol",
      "Chylomicronaemia",
      "Lipoprotein(a) elevation",
    ],
    answer: 1,
    explanation: "Elevated LDL cholesterol is the primary lipid abnormality driving atherosclerotic cardiovascular disease.",
    difficulty: "easy",
  },
  {
    prompt: "What diagnostic technique is shown in this gel electrophoresis image, used to separate haemoglobin variants for the diagnosis of sickle cell disease?",
    imageUrl: img("pmb-029-haemoglobin-electrophoresis.jpg"),
    options: [
      "Serum protein electrophoresis",
      "Haemoglobin electrophoresis",
      "Lipoprotein electrophoresis",
      "Urine protein electrophoresis",
      "Isoenzyme electrophoresis",
    ],
    answer: 1,
    explanation: "Haemoglobin electrophoresis separates HbA from HbS and other variants, diagnosing haemoglobinopathies.",
    difficulty: "medium",
  },
  {
    prompt: "Identify the liver function test result pattern shown: elevated conjugated (direct) bilirubin with normal unconjugated bilirubin, indicating obstructive jaundice.",
    imageUrl: img("pmb-030-conjugated-bilirubin.jpg"),
    options: [
      "Pre-hepatic jaundice",
      "Hepatic (hepatocellular) jaundice",
      "Post-hepatic (obstructive) jaundice",
      "Neonatal physiological jaundice",
      "Gilbert syndrome",
    ],
    answer: 2,
    explanation: "Predominantly elevated conjugated bilirubin with ALP and GGT elevation indicates obstructive jaundice.",
    difficulty: "medium",
  },
];
