import type { SeedQuestion } from "../seed-utils";

function img(file: string): string {
  return `/api/content/ospe/image?folder=PPG&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ─── Pharmacology (10) ─────────────────────────────────────────────
  {
    prompt: "A 55-year-old patient with hypertension is started on enalapril. Which mechanism best explains the antihypertensive action of this drug?",
    imageUrl: img("ppg-001-ace-inhibitor.jpg"),
    options: [
      "Competitive inhibition of angiotensin-converting enzyme",
      "Blockade of AT1 receptors for angiotensin II",
      "Inhibition of renin secretion from the juxtaglomerular cells",
      "Direct vasodilation of arteriolar smooth muscle",
      "Blockade of calcium channels in vascular smooth muscle",
    ],
    answer: 0,
    explanation: "Enalapril is an ACE inhibitor that blocks the conversion of angiotensin I to angiotensin II, reducing vasoconstriction and aldosterone secretion.",
    difficulty: "easy",
  },
  {
    prompt: "A patient on warfarin therapy presents with an INR of 8.0 and gingival bleeding. Which vitamin analogue is used as a specific antidote?",
    imageUrl: img("ppg-002-warfarin-antidote.jpg"),
    options: [
      "Vitamin B12",
      "Phylloquinone (Vitamin K1)",
      "Folic acid",
      "Ascorbic acid (Vitamin C)",
      "Calciferol (Vitamin D)",
    ],
    answer: 1,
    explanation: "Warfarin antagonises vitamin K-dependent clotting factors (II, VII, IX, X). Phytonadione (Vitamin K1) directly replenishes functional vitamin K, reversing anticoagulation.",
    difficulty: "easy",
  },
  {
    prompt: "A child presents with febrile seizures. Which first-line anticonvulsant is administered intravenously in acute management?",
    imageUrl: img("ppg-003-febrile-seizure.jpg"),
    options: [
      "Phenytoin",
      "Valproic acid",
      "Diazepam",
      "Carbamazepine",
      "Ethosuximide",
    ],
    answer: 2,
    explanation: "IV diazepam is the first-line benzodiazepine for acute seizure termination. It enhances GABA-A receptor-mediated chloride conductance.",
    difficulty: "easy",
  },
  {
    prompt: "A 60-year-old man with heart failure is prescribed furosemide. What is the primary site of action of this drug in the nephron?",
    imageUrl: img("ppg-004-furosemide-nephron.jpg"),
    options: [
      "Proximal convoluted tubule",
      "Thick ascending limb of the loop of Henle",
      "Distal convoluted tubule",
      "Collecting duct",
      "Glomerulus",
    ],
    answer: 1,
    explanation: "Furosemide inhibits the Na-K-2Cl cotransporter in the thick ascending limb, producing a potent loop diuresis.",
    difficulty: "easy",
  },
  {
    prompt: "A patient with acute myeloid leukaemia is started on cytarabine. This drug is an analogue of which naturally occurring pyrimidine nucleoside?",
    imageUrl: img("ppg-005-cytarabine-structure.jpg"),
    options: [
      "Guanosine",
      "Adenosine",
      "Deoxycytidine",
      "Uridine",
      "Thymidine",
    ],
    answer: 2,
    explanation: "Cytarabine (Ara-C) is a deoxycytidine analogue that inhibits DNA polymerase and incorporates into DNA, causing chain termination.",
    difficulty: "medium",
  },
  {
    prompt: "Which of the following drugs works by irreversibly inhibiting cyclooxygenase-1 and cyclooxygenase-2?",
    imageUrl: img("ppg-006-cox-inhibitor.jpg"),
    options: [
      "Paracetamol (Acetaminophen)",
      "Ibuprofen",
      "Aspirin",
      "Celecoxib",
      "Naproxen",
    ],
    answer: 2,
    explanation: "Aspirin is the only NSAID that irreversibly acetylates a serine residue in the active site of COX-1 and COX-2, permanently disabling the enzyme.",
    difficulty: "medium",
  },
  {
    prompt: "A 45-year-old woman is diagnosed with hyperthyroidism. Propylthiouracil is prescribed. In addition to inhibiting thyroid hormone synthesis, what other mechanism contributes to its antithyroid effect?",
    imageUrl: img("ppg-007-ptu-mechanism.jpg"),
    options: [
      "Inhibition of TSH release from the anterior pituitary",
      "Blocking T3 receptors in peripheral tissues",
      "Inhibiting peripheral conversion of T4 to T3",
      "Stimulating hepatic degradation of thyroid hormones",
      "Enhancing renal excretion of iodide",
    ],
    answer: 2,
    explanation: "PTU inhibits peripheral 5'-deiodinase, blocking conversion of T4 (inactive prohormone) to T3 (active hormone) — a property not shared by methimazole.",
    difficulty: "medium",
  },
  {
    prompt: "A hypertensive patient who is also diabetic is started on amlodipine. Which class of antihypertensive does this drug belong to?",
    imageUrl: img("ppg-008-amlodipine.jpg"),
    options: [
      "ACE inhibitor",
      "Beta-blocker",
      "Dihydropyridine calcium channel blocker",
      "Alpha-1 blocker",
      "Thiazide diuretic",
    ],
    answer: 2,
    explanation: "Amlodipine is a dihydropyridine CCB that selectively blocks L-type calcium channels in vascular smooth muscle, causing vasodilation.",
    difficulty: "easy",
  },
  {
    prompt: "A 30-year-old patient on isoniazid prophylaxis for tuberculosis develops peripheral neuropathy. Which vitamin deficiency is responsible, and which supplement should be co-prescribed?",
    imageUrl: img("ppg-009-isoniazid-neuropathy.jpg"),
    options: [
      "Vitamin B12 deficiency; cyanocobalamin",
      "Vitamin B6 (pyridoxine) deficiency; pyridoxine",
      "Folic acid deficiency; folate",
      "Vitamin B1 (thiamine) deficiency; thiamine",
      "Vitamin C deficiency; ascorbic acid",
    ],
    answer: 1,
    explanation: "Isoniazid inhibits pyridoxal phosphokinase, depleting pyridoxine (B6), a cofactor in neurotransmitter synthesis. Co-prescription of vitamin B6 prevents neuropathy.",
    difficulty: "medium",
  },
  {
    prompt: "A patient on fluoxetine (an SSRI) takes meperidine (pethidine) for severe pain. The patient develops hyperthermia, rigidity, and altered mental status. What is the most likely diagnosis?",
    imageUrl: img("ppg-010-ssri-opioid-interaction.jpg"),
    options: [
      "Neuroleptic malignant syndrome",
      "Serotonin syndrome",
      "Anticholinergic toxicity",
      "Neuroleptic malignant syndrome",
      "Opioid overdose",
    ],
    answer: 1,
    explanation: "Concomitant serotonergic agents (SSRI + meperidine, which also inhibits serotonin reuptake) can precipitate serotonin syndrome — characterised by hyperthermia, clonus, and altered mental status.",
    difficulty: "hard",
  },

  // ─── Molecular Biology (10) ────────────────────────────────────────
  {
    prompt: "During DNA replication, which enzyme is responsible for joining Okazaki fragments on the lagging strand?",
    imageUrl: img("ppg-011-okazaki-ligation.jpg"),
    options: [
      "DNA polymerase I",
      "DNA polymerase III",
      "DNA ligase",
      "Helicase",
      "Primase",
    ],
    answer: 2,
    explanation: "DNA ligase catalyses phosphodiester bond formation between adjacent Okazaki fragments after RNA primers are replaced by DNA.",
    difficulty: "easy",
  },
  {
    prompt: "In eukaryotic transcription, which general transcription factor is responsible for recognising the TATA box and positioning RNA polymerase II at the promoter?",
    imageUrl: img("ppg-012-tata-binding.jpg"),
    options: [
      "TFIIA",
      "TFIIB",
      "TFIID",
      "TFIIE",
      "TFIIH",
    ],
    answer: 2,
    explanation: "TFIID contains the TATA-binding protein (TBP), which recognises and binds the TATA box, nucleating pre-initiation complex assembly.",
    difficulty: "medium",
  },
  {
    prompt: "A mutation in the CFTR gene causes cystic fibrosis. The most common mutation, ΔF508, results in which of the following?",
    imageUrl: img("ppg-013-cftr-mutation.jpg"),
    options: [
      "Premature stop codon producing truncated protein",
      "Deletion of a phenylalanine residue causing protein misfolding",
      "Missense mutation altering chloride channel selectivity",
      "Splice site mutation causing exon skipping",
      "Trinucleotide repeat expansion",
    ],
    answer: 1,
    explanation: "ΔF508 is an in-frame deletion of phenylalanine at position 508, causing misfolding, ER retention, and proteasomal degradation of CFTR.",
    difficulty: "medium",
  },
  {
    prompt: "Which of the following correctly describes the direction of translation on an mRNA molecule?",
    imageUrl: img("ppg-014-translation-direction.jpg"),
    options: [
      "5' → 3' relative to mRNA, synthesising protein from N-terminus to C-terminus",
      "3' → 5' relative to mRNA, synthesising protein from N-terminus to C-terminus",
      "5' → 3' relative to mRNA, synthesising protein from C-terminus to N-terminus",
      "Bidirectional along the mRNA",
      "3' → 5' relative to mRNA, synthesising protein from C-terminus to N-terminus",
    ],
    answer: 0,
    explanation: "Ribosomes read mRNA in the 5'→3' direction and synthesise the polypeptide chain from the N-terminus to the C-terminus.",
    difficulty: "easy",
  },
  {
    prompt: "A researcher observes that a gene is silenced by a small interfering RNA (siRNA). What is the primary mechanism by which siRNA exerts gene silencing?",
    imageUrl: img("ppg-015-siRNA-mechanism.jpg"),
    options: [
      "DNA methylation at CpG islands",
      "Chromatin remodelling and histone deacetylation",
      "Endonucleolytic cleavage of complementary mRNA by RISC",
      "Inhibition of transcription initiation at the promoter",
      "Degradation of the corresponding tRNA",
    ],
    answer: 2,
    explanation: "siRNA is loaded into RISC (RNA-induced silencing complex), where the guide strand directs Argonaute-mediated endonucleolytic cleavage of perfectly complementary mRNA.",
    difficulty: "medium",
  },
  {
    prompt: "In the MAPK/ERK signalling cascade, what is the sequential order of kinase activation from receptor to transcription factor?",
    imageUrl: img("ppg-016-mapk-cascade.jpg"),
    options: [
      "Ras → Raf → MEK → ERK",
      "Raf → Ras → ERK → MEK",
      "MEK → Raf → Ras → ERK",
      "ERK → MEK → Raf → Ras",
      "Ras → MEK → Raf → ERK",
    ],
    answer: 0,
    explanation: "The canonical MAPK pathway proceeds: Ras-GTP activates Raf (MAPKKK), which phosphorylates MEK (MAPKK), which activates ERK (MAPK).",
    difficulty: "medium",
  },
  {
    prompt: "Which enzyme is responsible for adding the poly-A tail to eukaryotic mRNA during post-transcriptional processing?",
    imageUrl: img("ppg-017-polyadenylation.jpg"),
    options: [
      "RNA polymerase II",
      "Poly(A) polymerase",
      "RNA primase",
      "Adenylate kinase",
      "Poly(A) ribonuclease",
    ],
    answer: 1,
    explanation: "Poly(A) polymerase (PAP) adds ~200 adenine residues to the 3' end of mRNA in a template-independent manner after cleavage by CPSF.",
    difficulty: "easy",
  },
  {
    prompt: "A patient is found to have a deficiency in ornithine transcarbamylase (OTC). This enzyme is located in which cellular compartment and is part of which metabolic pathway?",
    imageUrl: img("ppg-018-otc-deficiency.jpg"),
    options: [
      "Mitochondrial matrix; urea cycle",
      "Cytosol; urea cycle",
      "Mitochondrial matrix; TCA cycle",
      "Cytosol; fatty acid β-oxidation",
      "Endoplasmic reticulum; protein synthesis",
    ],
    answer: 0,
    explanation: "OTC catalyses the condensation of ornithine and carbamoyl phosphate to form citrulline in the mitochondrial matrix as the first committed step of the urea cycle.",
    difficulty: "medium",
  },
  {
    prompt: "Which of the following best describes the role of tumour suppressor genes such as RB1?",
    imageUrl: img("ppg-019-rb1-function.jpg"),
    options: [
      "Promoting cell cycle progression by activating cyclin-dependent kinases",
      "Inhibiting cell cycle progression by sequestering E2F transcription factors",
      "Stimulating apoptosis through the mitochondrial pathway only",
      "Enhancing telomerase activity to maintain chromosome ends",
      "Acting as oncogenes when overexpressed",
    ],
    answer: 1,
    explanation: "RB1 protein (pRb) binds and sequesters E2F transcription factors in hypophosphorylated state, preventing S-phase entry. Loss of RB1 releases E2F, driving uncontrolled proliferation.",
    difficulty: "medium",
  },
  {
    prompt: "During homologous recombination repair of double-strand breaks, which protein initiates 5'→3' resection of the DNA ends?",
    imageUrl: img("ppg-020-hr-resection.jpg"),
    options: [
      "DNA polymerase III",
      "Ku70/Ku80 heterodimer",
      "MRN complex (Mre11-Rad50-Nbs1)",
      "DNA ligase IV",
      "Topoisomerase II",
    ],
    answer: 2,
    explanation: "The MRN complex, together with CtIP, initiates 5'→3' end resection at DSBs, generating 3' single-stranded overhangs required for RAD51 loading and strand invasion.",
    difficulty: "hard",
  },

  // ─── Physiology (10) ───────────────────────────────────────────────
  {
    prompt: "At rest, what is the approximate equilibrium potential for potassium (EK) in a typical mammalian neuron?",
    imageUrl: img("ppg-021-ek-resting.jpg"),
    options: [
      "+40 mV",
      "0 mV",
      "−70 mV",
      "−90 mV",
      "−120 mV",
    ],
    answer: 3,
    explanation: "Using the Nernst equation with typical intracellular [K⁺]=140 mM and extracellular [K⁺]=5 mM at 37°C, EK ≈ −90 mV, which is close to the resting membrane potential.",
    difficulty: "easy",
  },
  {
    prompt: "A 50-year-old man undergoes a thyroidectomy. Post-operatively, he develops paraesthesia and positive Chvostek and Trousseau signs. Which electrolyte abnormality is most likely responsible?",
    imageUrl: img("ppg-022-hypocalcaemia-signs.jpg"),
    options: [
      "Hyperkalaemia",
      "Hyponatraemia",
      "Hypocalcaemia",
      "Hypomagnesaemia",
      "Hyperphosphataemia",
    ],
    answer: 2,
    explanation: "Accidental removal or devascularisation of parathyroid glands causes hypocalcaemia, increasing neuromuscular excitability — manifesting as Chvostek's sign (facial twitch) and Trousseau's sign (carpopedal spasm on cuff inflation).",
    difficulty: "medium",
  },
  {
    prompt: "In the cardiac action potential, which ion current is responsible for Phase 2 (the plateau phase)?",
    imageUrl: img("ppg-023-cardiac-plateau.jpg"),
    options: [
      "Rapid Na⁺ influx",
      "Delayed rectifier K⁺ efflux",
      "L-type Ca²⁺ influx balanced by K⁺ efflux",
      "Inward rectifier K⁺ current (IK1)",
      "Na⁺/K⁺-ATPase current",
    ],
    answer: 2,
    explanation: "Phase 2 plateau results from L-type Ca²⁺ channels remaining open while delayed rectifier K⁺ channels begin opening, creating a balance that sustains depolarisation.",
    difficulty: "medium",
  },
  {
    prompt: "Which lung volumes and capacities can be measured using simple spirometry but NOT using a body plethysmograph alone?",
    imageUrl: img("ppg-024-spirometry-volumes.jpg"),
    options: [
      "Tidal volume and inspiratory reserve volume",
      "Total lung capacity and residual volume",
      "Functional residual capacity and transpulmonary pressure",
      "Inspiratory capacity and expiratory reserve volume",
    ],
    answer: 1,
    explanation: "TLC and RV cannot be directly measured by simple spirometry because RV cannot be exhaled. Body plethysmography measures FRC (from which TLC and RV are calculated) but simple spirometry alone cannot.",
    difficulty: "hard",
  },
  {
    prompt: "A patient presents with metabolic acidosis and an anion gap of 28 mEq/L. Which of the following conditions is most likely?",
    imageUrl: img("ppg-025-anion-gap-acidosis.jpg"),
    options: [
      "Diarrhoea",
      "Renal tubular acidosis",
      "Diabetic ketoacidosis",
      "Hyperaldosteronism",
      "Hyperventilation",
    ],
    answer: 2,
    explanation: "Diabetic ketoacidosis produces ketoacids (anions) that accumulate, widening the anion gap. Diarrhoea causes non-anion gap metabolic acidosis (bicarbonate loss).",
    difficulty: "medium",
  },
  {
    prompt: "During skeletal muscle contraction, which protein undergoes a conformational change to expose myosin-binding sites on actin?",
    imageUrl: img("ppg-026-troponin-tropomyosin.jpg"),
    options: [
      "Myosin heavy chain",
      "Titin",
      "Troponin C",
      "Tropomyosin",
      "Troponin I",
    ],
    answer: 3,
    explanation: "When Ca²⁺ binds troponin C, the troponin complex shifts tropomyosin deeper into the groove of the actin helix, exposing myosin-binding sites and enabling cross-bridge cycling.",
    difficulty: "easy",
  },
  {
    prompt: "Which of the following best explains the.countercurrent multiplier mechanism in the loop of Henle?",
    imageUrl: img("ppg-027-countercurrent.jpg"),
    options: [
      "Active transport of Na⁺ into the medullary interstitium from the collecting duct",
      "Active NaCl transport in the thick ascending limb creating a corticomedullary osmotic gradient",
      "Passive water reabsorption in the descending limb only",
      "ADH-mediated aquaporin insertion in the descending limb",
      "Urea recycling in the proximal tubule",
    ],
    answer: 1,
    explanation: "The thick ascending limb actively pumps NaCl into the interstitium without water (impermeable to water), creating the medullary osmotic gradient that drives countercurrent multiplication.",
    difficulty: "medium",
  },
  {
    prompt: "A 40-year-old man has a resting heart rate of 50 bpm. Which autonomic mechanism best explains this bradycardia?",
    imageUrl: img("ppg-028-vagal-tone.jpg"),
    options: [
      "Increased sympathetic output to the sinoatrial node",
      "Decreased parasympathetic (vagal) tone to the SA node",
      "Increased parasympathetic (vagal) tone to the SA node",
      "Intrinsic SA node dysfunction",
      "Circulating catecholamine withdrawal",
    ],
    answer: 2,
    explanation: "High vagal tone (as seen in well-trained athletes) releases acetylcholine acting on M2 muscarinic receptors, increasing K⁺ conductance and hyperpolarising SA node cells, slowing heart rate.",
    difficulty: "easy",
  },
  {
    prompt: "Which hormone is primarily responsible for calcium homeostasis by increasing renal calcium reabsorption and stimulating 1α-hydroxylase in the kidney?",
    imageUrl: img("ppg-029-pth-calcium.jpg"),
    options: [
      "Calcitonin",
      "Parathyroid hormone (PTH)",
      "Vitamin D3 (cholecalciferol)",
      "Thyroxine (T4)",
      "Aldosterone",
    ],
    answer: 1,
    explanation: "PTH increases serum Ca²⁺ by: (1) stimulating osteoclasts, (2) enhancing renal Ca²⁺ reabsorption, and (3) activating 1α-hydroxylase to convert 25(OH)D to active 1,25(OH)₂D₃.",
    difficulty: "medium",
  },
  {
    prompt: "During the baroreceptor reflex, an acute drop in blood pressure results in which immediate autonomic response?",
    imageUrl: img("ppg-030-baroreceptor-reflex.jpg"),
    options: [
      "Decreased heart rate and vasodilation",
      "Increased heart rate, increased cardiac contractility, and vasoconstriction",
      "Decreased heart rate and increased contractility",
      "Increased heart rate only with no change in vascular tone",
      "No change until chemoreceptors are activated",
    ],
    answer: 1,
    explanation: "Reduced arterial pressure decreases baroreceptor firing, reducing vagal tone and increasing sympathetic outflow — producing tachycardia, increased contractility, and peripheral vasoconstriction to restore BP.",
    difficulty: "easy",
  },
];
