import type { SeedQuestion } from "../seed-mcq-all";

/**
 * OSPE RESP Question Bank — 40 clinical MCQs
 * Style: "Identify the structure", "Name the pathology", "What is the diagnosis?"
 */

function img(file: string): string {
  return `/api/content/ospe/image?folder=RESP&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ─────────────────────────────────────────────────────────
  //  PATHOLOGY — Diagnosis / staging (25 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "Identify the stage of tuberculosis: early, firm, gray-white tubercles.",
    imageUrl: img("resp-patho-001-tb-early-firm-tubercles.jpg"),
    options: [
      "Early TB — firm, gray-white tubercles",
      "Caseating granulomas with central necrosis",
      "Healed calcified Ghon focus",
      "Miliary TB — disseminated micronodules",
    ],
    answer: 0,
    explanation: "Early TB shows firm, gray-white tubercles before significant caseation develops.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of tuberculous lesion: granuloma with central caseous necrosis.",
    imageUrl: img("resp-patho-002-tb-caseating-tubercles.jpg"),
    options: [
      "Caseating granuloma (classic TB)",
      "Non-caseating granuloma (sarcoidosis)",
      "Suppurative granuloma",
      "Fibrinous granuloma",
    ],
    answer: 0,
    explanation: "Classic TB granulomas show central caseous necrosis surrounded by epithelioid histiocytes and Langhans giant cells.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this primary TB lesion: solitary subpleural granuloma in the lower/mid lung zone.",
    imageUrl: img("resp-patho-003-tb-ghon-focus.jpg"),
    options: [
      "Ghon focus (primary TB)",
      "Reactivation TB cavity",
      "Lung abscess",
      "Hamartoma",
    ],
    answer: 0,
    explanation: "A Ghon focus is a subpleural granuloma in the lower or mid zone, the hallmark of primary TB.",
    difficulty: "medium",
  },
  {
    prompt: "What is this combination? Ghon focus + involved hilar lymph nodes.",
    imageUrl: img("resp-patho-004-tb-ghon-complex.jpg"),
    options: [
      "Ghon complex (primary TB)",
      "Reactivation TB",
      "Miliary TB",
      "Tuberculoma",
    ],
    answer: 0,
    explanation: "The Ghon complex includes the Ghon focus plus involved hilar lymph nodes, representing primary TB.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this disseminated form of TB: tiny, uniform granulomas throughout both lungs.",
    imageUrl: img("resp-patho-005-tb-miliary.jpg"),
    options: [
      "Miliary tuberculosis",
      "Sarcoidosis",
      "Pneumoconiosis",
      "Metastatic disease",
    ],
    answer: 0,
    explanation: "Miliary TB shows countless tiny (1-2mm) granulomas resembling millet seeds, due to hematogenous spread.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of emphysema: destruction centered on respiratory bronchioles.",
    imageUrl: img("resp-patho-008-emphysema-centrilobular.jpg"),
    options: [
      "Centrilobular emphysema (smoking-related)",
      "Panacinar emphysema (alpha-1 antitrypsin deficiency)",
      "Paraseptal (distal acinar) emphysema",
      "Irregular emphysema",
    ],
    answer: 0,
    explanation: "Centrilobular emphysema is the most common type, strongly associated with cigarette smoking.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of emphysema: uniform destruction of the entire acinus.",
    imageUrl: img("resp-patho-009-emphysema-panacinar.jpg"),
    options: [
      "Panacinar emphysema (alpha-1 antitrypsin deficiency)",
      "Centrilobular emphysema",
      "Paraseptal emphysema",
      "Irregular emphysema",
    ],
    answer: 0,
    explanation: "Panacinar emphysema shows uniform destruction of the entire acinus, characteristically associated with alpha-1 antitrypsin deficiency.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this airway pathology: permanent dilation of bronchi with destroyed walls.",
    imageUrl: img("resp-patho-012-bronchiectasis.jpg"),
    options: [
      "Bronchiectasis",
      "Chronic bronchitis",
      "Bronchial asthma",
      "Bronchiolitis obliterans",
    ],
    answer: 0,
    explanation: "Bronchiectasis is permanent, abnormal dilation of bronchi due to destruction of elastic and muscular wall components.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this pattern of pneumonia: consolidation of an entire lobe.",
    imageUrl: img("resp-patho-017-pneumonia-lobar.jpg"),
    options: [
      "Lobar pneumonia (Streptococcus pneumoniae)",
      "Bronchopneumonia",
      "Interstitial pneumonia",
      "Aspiration pneumonia",
    ],
    answer: 0,
    explanation: "Lobar pneumonia shows uniform consolidation of an entire lobe, classically caused by S. pneumoniae.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this pattern of pneumonia: patchy consolidation centered on bronchi.",
    imageUrl: img("resp-patho-018-pneumonia-broncho.jpg"),
    options: [
      "Bronchopneumonia (lobular)",
      "Lobar pneumonia",
      "Interstitial pneumonia",
      "Pneumocystis pneumonia",
    ],
    answer: 0,
    explanation: "Bronchopneumonia shows patchy consolidation centered on bronchi/bronchioles, often polymicrobial.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of lung cancer: arises centrally from major bronchi, strongly linked to smoking.",
    imageUrl: img("resp-patho-019-lung-cancer-squamous.jpg"),
    options: [
      "Squamous cell carcinoma",
      "Adenocarcinoma",
      "Small cell carcinoma",
      "Large cell carcinoma",
    ],
    answer: 0,
    explanation: "Squamous cell carcinoma is the most common centrally located lung cancer, strongly associated with smoking.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of lung cancer: most common overall, arises peripherally.",
    imageUrl: img("resp-patho-020-lung-cancer-adenocarcinoma.jpg"),
    options: [
      "Adenocarcinoma",
      "Squamous cell carcinoma",
      "Small cell carcinoma",
      "Large cell carcinoma",
    ],
    answer: 0,
    explanation: "Adenocarcinoma is the most common lung cancer overall, typically peripheral, and the most common in non-smokers.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this highly aggressive lung cancer: small cells with scant cytoplasm, rapid growth.",
    imageUrl: img("resp-patho-021-lung-cancer-small-cell.jpg"),
    options: [
      "Small cell lung carcinoma (oat cell)",
      "Squamous cell carcinoma",
      "Adenocarcinoma",
      "Carcinoid tumor",
    ],
    answer: 0,
    explanation: "Small cell carcinoma is highly aggressive, strongly linked to smoking, and often metastatic at diagnosis.",
    difficulty: "medium",
  },
  {
    prompt: "What is the diagnosis? Bilateral diffuse alveolar damage with hyaline membrane formation.",
    imageUrl: img("resp-patho-023-ARDS.jpg"),
    options: [
      "ARDS (diffuse alveolar damage)",
      "Pulmonary edema",
      "Pulmonary hemorrhage",
      "Pulmonary fibrosis",
    ],
    answer: 0,
    explanation: "ARDS shows diffuse alveolar damage with hyaline membranes, type II pneumocyte hyperplasia, and edema.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this interstitial lung disease: honeycomb lung with fibroblastic foci.",
    imageUrl: img("resp-patho-024-pulmonary-fibrosis.jpg"),
    options: [
      "Usual interstitial pneumonia (UIP) / IPF",
      "NsIP (nonspecific interstitial pneumonia)",
      "Hypersensitivity pneumonitis",
      "Sarcoidosis",
    ],
    answer: 0,
    explanation: "UIP shows heterogeneous fibrosis, honeycombing, and fibroblastic foci, the hallmark of idiopathic pulmonary fibrosis.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this occupational lung disease: upper lobe nodular fibrosis with eggshell calcification of hilar nodes.",
    imageUrl: img("resp-patho-028-pneumoconiosis-silicosis.jpg"),
    options: [
      "Silicosis",
      "Asbestosis",
      "Coal workers' pneumoconiosis (CWP)",
      "Berylliosis",
    ],
    answer: 0,
    explanation: "Silicosis shows upper lobe nodular fibrosis with whorled collagen (silicotic nodules) and eggshell calcification.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this occupational lung disease: lower lobe interstitial fibrosis with ferruginous bodies.",
    imageUrl: img("resp-patho-029-pneumoconiosis-asbestosis.jpg"),
    options: [
      "Asbestosis",
      "Silicosis",
      "Coal workers' pneumoconiosis",
      "Talcosis",
    ],
    answer: 0,
    explanation: "Asbestosis shows lower lobe interstitial fibrosis with ferruginous bodies (asbestos bodies) and pleural plaques.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this granulomatous lung disease: bilateral hilar lymphadenopathy with non-caseating granulomas.",
    imageUrl: img("resp-patho-031-sarcoidosis-lung.jpg"),
    options: [
      "Sarcoidosis",
      "Tuberculosis",
      "Berylliosis",
      "Hypersensitivity pneumonitis",
    ],
    answer: 0,
    explanation: "Sarcoidosis shows non-caseating granulomas with bilateral hilar lymphadenopathy, often with elevated ACE levels.",
    difficulty: "medium",
  },
  {
    prompt: "What is the diagnosis? Necrotizing lung infection with cavity formation and foul-smelling sputum.",
    imageUrl: img("resp-patho-016-lung-abscess.jpg"),
    options: [
      "Lung abscess",
      "Empyema",
      "Cavitating tuberculosis",
      "Necrotizing pneumonia",
    ],
    answer: 0,
    explanation: "Lung abscess shows a cavitary lesion with necrotic center, often from aspiration of oropharyngeal contents.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this type of lung cancer: undifferentiated, no glandular or squamous features.",
    imageUrl: img("resp-patho-022-lung-cancer-large-cell.jpg"),
    options: [
      "Large cell (undifferentiated) carcinoma",
      "Squamous cell carcinoma",
      "Adenocarcinoma",
      "Small cell carcinoma",
    ],
    answer: 0,
    explanation: "Large cell carcinoma is a diagnosis of exclusion — undifferentiated NSCLC lacking squamous, glandular, or neuroendocrine features.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this pleural pathology: pus in the pleural space.",
    imageUrl: img("resp-patho-032-empyema.jpg"),
    options: [
      "Empyema",
      "Pleural effusion",
      "Pneumothorax",
      "Hemothorax",
    ],
    answer: 0,
    explanation: "Empyema is a collection of pus in the pleural space, often complicating pneumonia or lung abscess.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this chronic airway disease: mucus gland hypertrophy in the bronchial wall.",
    imageUrl: img("resp-patho-014-chronic-bronchitis.jpg"),
    options: [
      "Chronic bronchitis",
      "Bronchial asthma",
      "Bronchiectasis",
      "COPD (emphysema)",
    ],
    answer: 0,
    explanation: "Chronic bronchitis shows hypertrophy of mucus-secreting glands (Reid index >0.5) and chronic inflammation.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this obstructive airway disease: smooth muscle hypertrophy with thickened basement membrane.",
    imageUrl: img("resp-patho-015-bronchial-asthma.jpg"),
    options: [
      "Bronchial asthma",
      "Chronic bronchitis",
      "Bronchiectasis",
      "COPD",
    ],
    answer: 0,
    explanation: "Asthma shows airway remodeling: smooth muscle hypertrophy, thickened basement membrane, mucus plugging, and eosinophilic inflammation.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this vascular lung pathology: plexiform lesions in small pulmonary arteries.",
    imageUrl: img("resp-patho-027-pulmonary-hypertension.jpg"),
    options: [
      "Pulmonary arterial hypertension",
      "Pulmonary embolism",
      "Pulmonary venous hypertension",
      "Cor pulmonale",
    ],
    answer: 0,
    explanation: "Primary pulmonary hypertension shows plexiform lesions, medial hypertrophy, and intimal fibrosis of small pulmonary arteries.",
    difficulty: "hard",
  },
  {
    prompt: "Identify this occupational lung disease: coal macules and simple CWP.",
    imageUrl: img("resp-patho-030-pneumoconiosis-coal-workers.jpg"),
    options: [
      "Coal workers' pneumoconiosis (CWP)",
      "Silicosis",
      "Asbestosis",
      "Siderosis",
    ],
    answer: 0,
    explanation: "CWP shows coal macules (coal dust + macrophages) around respiratory bronchioles, potentially progressing to progressive massive fibrosis.",
    difficulty: "medium",
  },

  // ─────────────────────────────────────────────────────────
  //  MICROBIOLOGY — Stain / culture identification (8 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "What is the name of this acid-fast stain used to identify Mycobacterium tuberculosis?",
    imageUrl: img("resp-micro-001-stain-ziehl-neelsen.jpg"),
    options: [
      "Ziehl-Neelsen (acid-fast) stain",
      "Gram stain",
      "Giemsa stain",
      "India ink stain",
    ],
    answer: 0,
    explanation: "The Ziehl-Neelsen stain identifies acid-fast bacilli (e.g., Mycobacterium) which retain carbol fuchsin after acid-alcohol decolorization.",
    difficulty: "easy",
  },
  {
    prompt: "What type of stain is this? Fluorescent dye used to detect acid-fast bacilli.",
    imageUrl: img("resp-micro-002-stain-fluorochrome.jpg"),
    options: [
      "Fluorochrome stain (auramine-rhodamine)",
      "Gram stain",
      "Ziehl-Neelsen stain",
      "PAS stain",
    ],
    answer: 0,
    explanation: "Fluorochrome stains (auramine-rhodamine) are more sensitive than ZN for detecting AFB in sputum samples.",
    difficulty: "medium",
  },
  {
    prompt: "What type of stain shows purple-stained bacteria?",
    imageUrl: img("resp-micro-003-stain-gram-positive.jpg"),
    options: [
      "Gram stain — Gram-positive bacteria",
      "Gram stain — Gram-negative bacteria",
      "Acid-fast stain",
      "Wright stain",
    ],
    answer: 0,
    explanation: "Gram-positive bacteria retain crystal violet dye and appear purple/blue under Gram stain.",
    difficulty: "easy",
  },
  {
    prompt: "What type of stain shows pink/red-stained bacteria?",
    imageUrl: img("resp-micro-004-stain-gram-negative.jpg"),
    options: [
      "Gram stain — Gram-negative bacteria",
      "Gram stain — Gram-positive bacteria",
      "Acid-fast stain",
      "Negative stain",
    ],
    answer: 0,
    explanation: "Gram-negative bacteria lose crystal violet and take up the counterstain (safranin), appearing pink/red.",
    difficulty: "easy",
  },
  {
    prompt: "What type of culture medium is this? Green, egg-based medium for Mycobacterium.",
    imageUrl: img("resp-micro-005-culture-lowenstein-jensen.jpg"),
    options: [
      "Lowenstein-Jensen medium",
      "Blood agar",
      "MacConkey agar",
      "Chocolate agar",
    ],
    answer: 0,
    explanation: "LJ medium is an egg-based medium used for cultivation of Mycobacterium tuberculosis, showing buff-colored colonies.",
    difficulty: "medium",
  },
  {
    prompt: "What type of culture medium is this? Egg-based medium for Mycobacterium, similar to LJ.",
    imageUrl: img("resp-micro-006-culture-dorset-egg.jpg"),
    options: [
      "Dorset egg medium",
      "Lowenstein-Jensen medium",
      "Sabouraud agar",
      "Chocolate agar",
    ],
    answer: 0,
    explanation: "Dorset egg medium is another egg-based medium for Mycobacterium cultivation, used historically.",
    difficulty: "hard",
  },
  {
    prompt: "What type of culture medium is this? Enriched medium that requires CO2 for growth.",
    imageUrl: img("resp-micro-007-culture-chocolate-agar.jpg"),
    options: [
      "Chocolate (heated blood) agar",
      "Blood agar",
      "MacConkey agar",
      "SS agar",
    ],
    answer: 0,
    explanation: "Chocolate agar is heated blood agar that releases growth factors, used for fastidious organisms like Haemophilus and Neisseria.",
    difficulty: "medium",
  },
  {
    prompt: "What type of culture medium is this? Commonly used for isolation of streptococci.",
    imageUrl: img("resp-micro-008-culture-blood-agar.jpg"),
    options: [
      "Blood agar (5% sheep blood)",
      "Chocolate agar",
      "MacConkey agar",
      "Mannitol salt agar",
    ],
    answer: 0,
    explanation: "Blood agar supports growth of most pathogens and allows observation of hemolysis patterns (alpha, beta, gamma).",
    difficulty: "easy",
  },

  // ─────────────────────────────────────────────────────────
  //  PHYSIOLOGY / ANATOMY (7 questions)
  // ─────────────────────────────────────────────────────────
  {
    prompt: "Identify the lobes and fissures of the right lung.",
    imageUrl: img("resp-anato-001-lung-lobes-right.jpg"),
    options: [
      "Right lung — 3 lobes (superior, middle, inferior) with 2 fissures",
      "Left lung — 2 lobes with 1 fissure",
      "Right lung — 2 lobes with 1 fissure",
      "Both lungs — 3 lobes each",
    ],
    answer: 0,
    explanation: "The right lung has 3 lobes separated by horizontal and oblique fissures. The left lung has 2 lobes with only an oblique fissure.",
    difficulty: "easy",
  },
  {
    prompt: "Identify the lobes and fissures of the left lung.",
    imageUrl: img("resp-anato-002-lung-lobes-left.jpg"),
    options: [
      "Left lung — 2 lobes (superior, inferior) with 1 oblique fissure",
      "Right lung — 3 lobes with 2 fissures",
      "Left lung — 3 lobes with 2 fissures",
      "Left lung — 2 lobes with 2 fissures",
    ],
    answer: 0,
    explanation: "The left lung has 2 lobes separated by a single oblique fissure, with the cardiac notch on the medial surface.",
    difficulty: "easy",
  },
  {
    prompt: "Identify this airway structure: the first division of the trachea.",
    imageUrl: img("resp-anato-003-bronchial-tree.jpg"),
    options: [
      "Carina / main (primary) bronchus",
      "Lobar (secondary) bronchus",
      "Segmental (tertiary) bronchus",
      "Bronchiole",
    ],
    answer: 0,
    explanation: "The carina is the ridge at the base of the trachea where it bifurcates into the right and left main bronchi.",
    difficulty: "medium",
  },
  {
    prompt: "Identify parameter number 4 on this spirometry tracing: the maximum volume after full inspiration.",
    imageUrl: img("resp-physio-001-spirometry-fev1.jpg"),
    options: [
      "FVC (Forced Vital Capacity)",
      "FEV1 (Forced Expiratory Volume in 1 second)",
      "Tidal Volume",
      "Residual Volume",
    ],
    answer: 0,
    explanation: "FVC is the maximum volume of air exhaled forcefully from full inspiration to full expiration.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this spirometry parameter: the volume exhaled in the first second of forced expiration.",
    imageUrl: img("resp-physio-002-spirometry-fvc.jpg"),
    options: [
      "FEV1 (Forced Expiratory Volume in 1 second)",
      "FVC (Forced Vital Capacity)",
      "PEF (Peak Expiratory Flow)",
      "ERV (Expiratory Reserve Volume)",
    ],
    answer: 0,
    explanation: "FEV1 is the volume exhaled in the first second; FEV1/FVC ratio <0.70 indicates obstructive disease.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this lung volume: the volume remaining after maximum forced expiration.",
    imageUrl: img("resp-physio-003-spirometry-residual-volume.jpg"),
    options: [
      "Residual Volume (RV)",
      "Tidal Volume (TV)",
      "Inspiratory Reserve Volume (IRV)",
      "Expiratory Reserve Volume (ERV)",
    ],
    answer: 0,
    explanation: "Residual Volume is the air remaining in the lungs after maximum expiration; it cannot be measured by spirometry.",
    difficulty: "medium",
  },
  {
    prompt: "Identify this respiratory tissue: thin-walled air sacs for gas exchange.",
    imageUrl: img("resp-histo-001-alveoli-histology.jpg"),
    options: [
      "Alveoli (Type I and Type II pneumocytes)",
      "Bronchial epithelium",
      "Bronchiolar smooth muscle",
      "Pleural mesothelium",
    ],
    answer: 0,
    explanation: "Alveoli are lined by thin Type I pneumocytes for gas exchange and cuboidal Type II pneumocytes that produce surfactant.",
    difficulty: "easy",
  },
];
