import type { SeedQuestion } from "../seed-utils";

function img(file: string): string {
  return `/api/content/ospe/image?folder=UNI&file=${encodeURIComponent(file)}`;
}

export const questions: SeedQuestion[] = [
  // ─── Epidemiology: Study Types, Bias, Screening Tests, Disease Surveillance (10) ───

  {
    prompt: "A researcher identifies patients with lung cancer and asks them about their past smoking habits. What study design is this?",
    imageUrl: img("uni-001-case-control-study.jpg"),
    options: [
      "Cohort study",
      "Case-control study",
      "Cross-sectional survey",
      "Randomized controlled trial",
      "Ecological study",
    ],
    answer: 1,
    explanation: "Starting with cases and looking back at exposures is characteristic of a case-control study.",
    difficulty: "easy",
  },
  {
    prompt: "Which of the following biases occurs when the group selected for a study is not representative of the target population?",
    imageUrl: img("uni-002-selection-bias.jpg"),
    options: [
      "Recall bias",
      "Detection bias",
      "Selection bias",
      "Attrition bias",
      "Lead-time bias",
    ],
    answer: 2,
    explanation: "Selection bias arises from systematic differences between the study sample and the target population.",
    difficulty: "easy",
  },
  {
    prompt: "A screening test has high sensitivity but low specificity. What is the most likely consequence?",
    imageUrl: img("uni-003-screening-sensitivity.jpg"),
    options: [
      "Many false negatives",
      "Many false positives",
      "Few true positives",
      "Low positive predictive value in a low-prevalence population",
      "Low negative predictive value",
    ],
    answer: 1,
    explanation: "Low specificity means many healthy individuals are incorrectly identified as positive (false positives).",
    difficulty: "medium",
  },
  {
    prompt: "What is the primary purpose of disease surveillance systems?",
    imageUrl: img("uni-004-surveillance.jpg"),
    options: [
      "To determine the cause of disease",
      "To provide treatment to patients",
      "To detect trends and outbreaks early for public health action",
      "To evaluate the efficacy of new drugs",
      "To assign diagnoses to hospitalised patients",
    ],
    answer: 2,
    explanation: "Disease surveillance is the continuous collection and analysis of health data to detect outbreaks and guide responses.",
    difficulty: "easy",
  },
  {
    prompt: "In a cohort study, the attributable risk (risk difference) among the exposed is calculated as:",
    imageUrl: img("uni-005-attributable-risk.jpg"),
    options: [
      "RR × (RR − 1)",
      "Incidence in exposed − Incidence in unexposed",
      "Odds in exposed / Odds in unexposed",
      "Prevalence in exposed / Prevalence in unexposed",
      "Incidence in unexposed / Incidence in exposed",
    ],
    answer: 1,
    explanation: "Attributable risk (risk difference) = I_e − I_u, the excess risk in the exposed group attributable to the exposure.",
    difficulty: "medium",
  },
  {
    prompt: "A mammography screening programme detects breast cancer 18 months earlier than it would normally present. Screened women have longer survival from diagnosis but no difference in overall mortality. This is an example of:",
    imageUrl: img("uni-006-lead-time-bias.jpg"),
    options: [
      "Length bias",
      "Lead-time bias",
      "Selection bias",
      "Recall bias",
      "Confounding",
    ],
    answer: 1,
    explanation: "Lead-time bias occurs when screening simply advances the time of diagnosis without improving survival or mortality.",
    difficulty: "medium",
  },
  {
    prompt: "Which of the following best describes the positive predictive value (PPV) of a screening test?",
    imageUrl: img("uni-007-ppv.jpg"),
    options: [
      "Probability that a truly diseased person tests positive",
      "Probability that a test-positive person actually has the disease",
      "Proportion of negatives correctly identified",
      "Ratio of true positives to true negatives",
      "Pre-test probability of disease",
    ],
    answer: 1,
    explanation: "PPV = True positives / (True positives + False positives), i.e. the probability that a positive result is truly positive.",
    difficulty: "medium",
  },
  {
    prompt: "A study compares mortality rates across different countries using aggregate national data. No individual-level data are collected. What study design is this?",
    imageUrl: img("uni-008-ecological-study.jpg"),
    options: [
      "Cross-sectional study",
      "Case-control study",
      "Cohort study",
      "Ecological study",
      "Meta-analysis",
    ],
    answer: 3,
    explanation: "Ecological studies use summary population-level data rather than individual data, which can lead to ecological fallacy.",
    difficulty: "easy",
  },
  {
    prompt: "The sensitivity of a rapid antigen test for influenza is 70%. This means that:",
    imageUrl: img("uni-009-sensitivity-definition.jpg"),
    options: [
      "70% of test-positive individuals have influenza",
      "70% of healthy individuals test negative",
      "70% of individuals with influenza test positive",
      "70% of all tests are accurate",
      "30% of cases are missed by other tests",
    ],
    answer: 2,
    explanation: "Sensitivity is the proportion of truly diseased individuals who test positive, i.e. TP / (TP + FN) = 70%.",
    difficulty: "easy",
  },
  {
    prompt: "Which form of bias would result from patients with milder or subclinical disease being more likely to seek screening, thus underestimating severity in the screened population?",
    imageUrl: img("uni-010-length-bias.jpg"),
    options: [
      "Lead-time bias",
      "Healthy volunteer bias",
      "Length bias",
      "Detection bias",
      "Confounding by indication",
    ],
    answer: 2,
    explanation: "Length bias refers to the preferential detection of slower-progressing (longer-duration) disease by screening, which may overestimate screening effectiveness.",
    difficulty: "hard",
  },

  // ─── Biostatistics: Statistical Measures, Study Design, Data Interpretation (10) ───

  {
    prompt: "A dataset of household incomes is highly right-skewed. Which measure of central tendency is most appropriate?",
    imageUrl: img("uni-011-mean-vs-median.jpg"),
    options: [
      "Mean",
      "Median",
      "Mode",
      "Standard deviation",
      "Range",
    ],
    answer: 1,
    explanation: "The median is preferred for skewed data because it is not influenced by extreme values, unlike the mean.",
    difficulty: "easy",
  },
  {
    prompt: "In a case-control study, the odds ratio is calculated as (a × d) / (b × c). If the odds ratio equals 1.0, what does this indicate?",
    imageUrl: img("uni-012-odds-ratio.jpg"),
    options: [
      "Strong positive association",
      "Strong negative association",
      "No association between exposure and disease",
      "The exposure is protective",
      "The study has confounding",
    ],
    answer: 2,
    explanation: "An odds ratio of 1.0 means the odds of exposure are the same in cases and controls, indicating no association.",
    difficulty: "easy",
  },
  {
    prompt: "A researcher reports a p-value of 0.03. Which of the following is a correct interpretation?",
    imageUrl: img("uni-013-p-value.jpg"),
    options: [
      "There is a 3% probability the null hypothesis is true",
      "If the null hypothesis is true, there is a 3% probability of observing results as extreme as those obtained",
      "The results are clinically significant",
      "The alternative hypothesis is definitely true",
      "There is a 97% chance the treatment works",
    ],
    answer: 1,
    explanation: "The p-value is the probability of observing data as extreme as or more extreme than what was observed, assuming the null hypothesis is true.",
    difficulty: "medium",
  },
  {
    prompt: "In a clinical trial, 200 patients are randomised to Drug A and 200 to placebo. After 6 months, 30 in Drug A group and 50 in placebo group have the outcome. What is the relative risk reduction?",
    imageUrl: img("uni-014-rrr.jpg"),
    options: [
      "40%",
      "25%",
      "20%",
      "10%",
      "60%",
    ],
    answer: 0,
    explanation: "RR (Drug A) = 30/200 = 0.15; RR (placebo) = 50/200 = 0.25. RRR = (0.25 − 0.15) / 0.25 = 0.10 / 0.25 = 0.40 = 40%.",
    difficulty: "medium",
  },
  {
    prompt: "Which statistical test is most appropriate to compare the mean blood pressure between two independent groups of patients?",
    imageUrl: img("uni-015-t-test.jpg"),
    options: [
      "Paired t-test",
      "Independent samples t-test",
      "Chi-squared test",
      "ANOVA",
      "Wilcoxon signed-rank test",
    ],
    answer: 1,
    explanation: "An independent samples t-test is used to compare means between two independent groups with continuous outcomes.",
    difficulty: "easy",
  },
  {
    prompt: "The number needed to treat (NNT) is calculated as the reciprocal of the absolute risk reduction. If the ARR is 5%, what is the NNT?",
    imageUrl: img("uni-016-nnt.jpg"),
    options: [
      "5",
      "20",
      "25",
      "50",
      "100",
    ],
    answer: 1,
    explanation: "NNT = 1 / ARR = 1 / 0.05 = 20. You need to treat 20 patients to prevent one additional adverse outcome.",
    difficulty: "easy",
  },
  {
    prompt: "In a study, a 95% confidence interval for the mean difference in recovery time is [2.1, 5.8] days. Which conclusion is correct?",
    imageUrl: img("uni-017-confidence-interval.jpg"),
    options: [
      "There is no significant difference between groups",
      "The true mean difference likely lies between 2.1 and 5.8 days",
      "5% of patients recovered between 2.1 and 5.8 days",
      "The p-value is less than 0.01",
      "The sample size is too small",
    ],
    answer: 1,
    explanation: "A 95% CI means we are 95% confident that the true population parameter lies within the interval [2.1, 5.8].",
    difficulty: "medium",
  },
  {
    prompt: "What is the prevalence of a disease in a community if 450 cases are identified in a total population of 15,000?",
    imageUrl: img("uni-018-prevalence.jpg"),
    options: [
      "30 per 1,000",
      "3%",
      "45 per 1,000",
      "0.3%",
      "Both A and B are correct",
    ],
    answer: 4,
    explanation: "Prevalence = 450 / 15,000 = 0.03 = 3% = 30 per 1,000. Both A and B express the same value.",
    difficulty: "easy",
  },
  {
    prompt: "In a study examining the association between physical activity (continuous variable) and blood pressure (continuous variable), which correlation coefficient is most appropriate?",
    imageUrl: img("uni-019-correlation.jpg"),
    options: [
      "Spearman rank correlation",
      "Pearson correlation coefficient",
      "Kappa statistic",
      "Intraclass correlation",
      "Cramér's V",
    ],
    answer: 1,
    explanation: "Pearson's r measures the linear association between two continuous variables when assumptions of normality are met.",
    difficulty: "medium",
  },
  {
    prompt: "A study has 1,200 participants, 600 exposed and 600 unexposed. Among exposed, 90 develop the disease. Among unexposed, 30 develop the disease. What is the risk ratio (relative risk)?",
    imageUrl: img("uni-020-risk-ratio.jpg"),
    options: [
      "1.5",
      "2.0",
      "3.0",
      "0.33",
      "4.0",
    ],
    answer: 2,
    explanation: "Risk in exposed = 90/600 = 0.15; Risk in unexposed = 30/600 = 0.05. RR = 0.15 / 0.05 = 3.0.",
    difficulty: "easy",
  },

  // ─── Public Health: Health Systems, Social Determinants, Environmental Health, Nutrition, Infection Control (10) ───

  {
    prompt: "Which of the following is a key component of the WHO health systems framework (Building Blocks)?",
    imageUrl: img("uni-021-who-health-systems.jpg"),
    options: [
      "Health financing",
      "Pharmaceutical marketing",
      "Private insurance only",
      "Fee-for-service payments",
      "Hospital bed density",
    ],
    answer: 0,
    explanation: "Health financing is one of the six WHO building blocks, alongside service delivery, health workforce, information, essential medicines, and leadership/governance.",
    difficulty: "easy",
  },
  {
    prompt: "A child living in a low-income neighbourhood has poor nutrition, limited access to healthcare, and attends an under-resourced school. This is an example of:",
    imageUrl: img("uni-022-social-determinants.jpg"),
    options: [
      "Genetic predisposition",
      "Healthcare access issue only",
      "Social determinants of health",
      "Iatrogenic disease",
      "A natural disaster",
    ],
    answer: 2,
    explanation: "Social determinants of health include economic conditions, education, neighbourhood, and access to services that shape health outcomes.",
    difficulty: "easy",
  },
  {
    prompt: "A factory worker is exposed to asbestos dust over 20 years and develops mesothelioma. This is primarily classified as:",
    imageUrl: img("uni-023-occupational-health.jpg"),
    options: [
      "A communicable disease",
      "A nutritional deficiency",
      "An occupational/environmental lung disease",
      "A genetic condition",
      "A lifestyle-related disease",
    ],
    answer: 2,
    explanation: "Mesothelioma is strongly associated with occupational asbestos exposure and is classified as an environmental/occupational disease.",
    difficulty: "easy",
  },
  {
    prompt: "Which of the following is the most effective public health intervention to prevent the spread of a foodborne outbreak in a community?",
    imageUrl: img("uni-024-food-safety.jpg"),
    options: [
      "Mass antibiotic distribution",
      "Improving food safety and hygiene practices",
      "Closing all restaurants",
      "Vaccinating all food handlers",
      "Issuing a media statement only",
    ],
    answer: 1,
    explanation: "Improving food safety and hygiene is the most effective and sustainable intervention for preventing foodborne disease outbreaks.",
    difficulty: "easy",
  },
  {
    prompt: "In a hospital ward, a patient on IV antibiotics develops Clostridioides difficile infection after 10 days of broad-spectrum antibiotic therapy. This is best described as:",
    imageUrl: img("uni-025-hospital-infection.jpg"),
    options: [
      "Community-acquired infection",
      "Surgical site infection",
      "Healthcare-associated (nosocomial) infection",
      "Vector-borne infection",
      "Congenital infection",
    ],
    answer: 2,
    explanation: "C. difficile infection occurring after ≥48 hours of hospitalisation and associated with prior antibiotic use is a healthcare-associated infection.",
    difficulty: "medium",
  },
  {
    prompt: "The concept of 'herd immunity' in a population is most directly relevant to which public health strategy?",
    imageUrl: img("uni-026-herd-immunity.jpg"),
    options: [
      "Water fluoridation",
      "Vaccination programmes",
      "Tobacco cessation campaigns",
      "Breastfeeding promotion",
      "Seatbelt legislation",
    ],
    answer: 1,
    explanation: "Herd immunity occurs when a sufficient proportion of a population is immune (often through vaccination), reducing transmission and protecting non-immune individuals.",
    difficulty: "easy",
  },
  {
    prompt: "Which micronutrient deficiency is the leading cause of preventable childhood blindness worldwide?",
    imageUrl: img("uni-027-vitamin-a-deficiency.jpg"),
    options: [
      "Iron deficiency",
      "Iodine deficiency",
      "Vitamin A deficiency",
      "Vitamin D deficiency",
      "Zinc deficiency",
    ],
    answer: 2,
    explanation: "Vitamin A deficiency is the leading cause of preventable childhood blindness and significantly increases morbidity and mortality from infections.",
    difficulty: "medium",
  },
  {
    prompt: "A community health worker notices that the rate of malnutrition in children under 5 has increased following a prolonged drought and crop failure. This situation best illustrates:",
    imageUrl: img("uni-028-food-security.jpg"),
    options: [
      "A genetic disorder",
      "An epidemic of infectious disease",
      "A food security crisis linked to environmental change",
      "Over-nutrition from processed food",
      "A vaccination failure",
    ],
    answer: 2,
    explanation: "Drought and crop failure directly threaten food security, and food insecurity is a major determinant of malnutrition in vulnerable populations.",
    difficulty: "medium",
  },
  {
    prompt: "The standard precautions in infection control include all of the following EXCEPT:",
    imageUrl: img("uni-029-standard-precautions.jpg"),
    options: [
      "Hand hygiene",
      "Use of personal protective equipment",
      "Proper handling of sharps and clinical waste",
      "Treating all patients with antibiotics prophylactically",
      "Safe injection practices",
    ],
    answer: 3,
    explanation: "Standard precautions include hand hygiene, PPE, sharps safety, safe injection, and environmental cleaning—but do not include prophylactic antibiotics for all patients.",
    difficulty: "easy",
  },
  {
    prompt: "Which of the following social determinants is most strongly associated with health inequalities between high-income and low-income countries?",
    imageUrl: img("uni-030-sdoh-global.jpg"),
    options: [
      "Access to private health insurance",
      "Level of economic development and poverty",
      "Number of pharmaceutical companies",
      "Patient compliance with treatment",
      "Availability of alternative medicine",
    ],
    answer: 1,
    explanation: "Economic development and poverty are fundamental social determinants that drive health inequalities globally, affecting access to healthcare, nutrition, education, and sanitation.",
    difficulty: "medium",
  },
];
